### ISSUE TITLE
A conversion of png with transparency, to jpg replaces the transparency with black instead of white.

### ISSUE THREAD

**Issue by cameronkendall** [minimagick/minimagick#104]
I'm running a conversion using img.format('jpg'), but when the original image is .png with transparency, the transparency becomes black in the converted jpeg. It should be white.

manipulate! do |img|
  img.resize "200x200"
  img.background "rgba(255,255,255,0.0)"
  img = yield(img) if block_given?
  img.format('jpg')
  img
end

**Comment by chr1s1** [comment]
Thanks a lot! @fivedigit

**Comment by duecorda** [comment]
@fivedigit thx!

**Comment by ermenkov** [comment]
This is an old issue but anyway. I couldn't find what I was searching for.

Here is a simple **Rails** solution directly taken from a controller:
```ruby
...
def resize_before_upload
    pipeline = ImageProcessing::MiniMagick.source(params[:blog_post][:cover].tempfile.path)
    params[:blog_post][:cover].tempfile = pipeline.convert('jpg').background('white').alpha('remove').resize_to_fill(1500, 800).saver(quality: 90, interlace: 'Line').call
end
...
```
Key part: ```...background('white').alpha('remove')...```
You can adapt it to your needs, e.g. **plain ruby**.
