### ISSUE TITLE
Resizing an animated gif corrupts it

### ISSUE THREAD

**Issue by mixonic** [minimagick/minimagick#127]
Howdy all. I've got an animated gif:

![](http://f.cl.ly/items/3z0v3W1O3c2o2B0e2t2F/davidope_1.gif)

This is is after calling `img.resize('100x100')`:

![](http://f.cl.ly/items/1U2v1H2l0T2p0C2d013n/min.gif)

I'm looking into the arguments imagemagick needs to successfully do this. Any insight from y'all would be very helpful!

**Comment by zdavis** [comment]
For the next unfortunate soul who ends up trying to solve this problem...

The code I was working with set the configuration using the `apply` method, like this:
```
ImageProcessing::MiniMagick.apply(config).call(source.open)
```

I found that the order of properties in that config object made a difference. The coalesce and repage piece had to come first.

The following configuration led to an incorrect output
```
config = {"resize"=>"320x320", "background"=>"none", "gravity"=>"north", "coalesce"=>true, "repage"=>"0x0"}
```
![example-2](https://user-images.githubusercontent.com/255909/67809528-17816c00-fa56-11e9-8f01-f3ce69483866.gif)

While this config led to the correct output:
config = {"coalesce"=>true, "repage"=>"0x0", "resize"=>"320x320", "gravity"=>"north", "background"=>"none"}

![example-1](https://user-images.githubusercontent.com/255909/67809595-3849c180-fa56-11e9-8476-8255e618cfb8.gif)

Hope this saves someone a little time! 

Another relevant, useful resource here: https://collectiveidea.com/blog/archives/2017/01/06/cropping-animated-gifs-with-minimagick
