### ISSUE TITLE
tmp/mini_magick[something].jpg missing

### ISSUE THREAD

**Issue by alecguintu** [minimagick/minimagick#141]
Hi guys,

How do I really write the manipulate! method? In this [rdoc](http://carrierwave.rubyforge.org/rdoc/classes/CarrierWave/MiniMagick.html) it says:

``` ruby
manipulate! do |img|
  img = img.sepiatone
  img = img.auto_orient
  img = img.radial_blur blur_factor
end
```

where they return it to the img (variable?). I tried this out but when I used this on my rails app - it had an error: `undefined method 'crop' for "":String`.

What I usually have is:

``` ruby
process :resize_and_crop
def resize_and_crop
  manipulate! do |img|
    img.resize("#{model.jrac_image_width}x#{model.jrac_image_height}") # resize_to_fit
    img.crop("442x190+#{model.jrac_crop_x}+#{model.jrac_crop_y}") # cropper
    img
  end
end
```

but with this I sometimes get this error: `Errno::ENOENT: No such file or directory - /tmp/mini_magick20130319-2-3wq6l6.jpg` which I think happens when `crop` is getting executed and can't find the temp file again.

Do you guys know of a fix for these? Help. I can provide further information if this is not clear.

Note:
  I haven't actually encountered this error on development and happens only on production (deployed to Heroku) experienced by other users.

Note:
  I also use rails, carrierwave+minimagick and deployed on heroku. I posted this question at SO (http://stackoverflow.com/questions/16270926/heroku-carrierwave-minimagick-random-tmp-file-missing), which I think is more clear.

**Comment by wangchenOS** [comment]
@lexruee ,This really helpful ,the problem is solved,thank you

**Comment by samnissen** [comment]
I tried @aivils solution which worked, in the sense that it caused MiniMagick to work perfectly.

However, it also caused Rails to pick up the system Ruby, ignoring Bundler and RVM. [You can see more details about that here](https://github.com/bundler/bundler/issues/5478).

The solution that worked for me, without causing Rails to use the wrong Ruby version, is to symlink mogrify to the relevant user's local bin, which is already in the path:

```bash
$ sudo ln -s /usr/bin/mogrify /usr/local/bin/mogrify
```
