### ISSUE TITLE
Is it possible to migrate from rmagick when using ImageList class and montage method?

### ISSUE THREAD

**Issue by abitdodgy** [minimagick/minimagick#144]
Can MiniMagick handle creating collages? `rmagick` provides an `ImageList` class and a `montage` method for this purpose. Does MiniMagick have an equivalent?

I looked through the Ruby Docs, but I couldn't find anything. Is it possible to migrate with those requirements?

**Comment by janko-m** [comment]
I will close this "issue", since this is extremely difficult to implement `ImageList` in a performant way (RMagick failed, that's why it had the memory leaks), so I can't see it being part of MiniMagick.
