### ISSUE TITLE
how to add a label to an image?

### ISSUE THREAD

**Issue by jedschneider** [minimagick/minimagick#150]
From reading the source I would think I would use the combine_options method to invoke the internal CommandBuilder class, but I'm getting a little lost in the metaprogramming there and I don't know imagemagick that well to have a feel for how it might look.

here's my attempt that doesn't seem to work.

``` ruby
image.combine_options("label") do |c|
  c.label = "foo"
end
```

maybe I overlooked an example in the readme that does something similar. if not, perhaps an addition would be handy, which i'd be happy to write once I know how it works. thanks.

**Comment by lanrion** [comment]
@jedschneider It can't support ZH-CN, any other suggestions， e.g:
```ruby
res_img = MiniMagick::Image.new("tmp/test_qrcode1.jpg")
res_img.combine_options do |i|
  i.font "Helvetica"
  i.pointsize 14
  i.encoding "GB2312"
  i.label:"我.utf8"
  i.draw "text 110,180 'DHH我.utf8'"
end
```

**Comment by coderliu** [comment]
@lanrion 
```
img.combine_options do |i|
    i.font "#{Rails.root}/public/Songti.ttc"  #path to font file which support ZH-CN
    i.pointsize 14
    i.encoding "GB2312"
    i.label:"我.utf8"
    i.draw "text 110,180 'DHH我.utf8'"
end
```
