### ISSUE TITLE
Warnings on stderr are breaking identify

### ISSUE THREAD

**Issue by jondoveston** [minimagick/minimagick#151]
This is the latest imagemagick on ubuntu raring (homebrew imagemagick works)

```
Version: ImageMagick 6.7.7-10 2013-02-25 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2012 ImageMagick Studio LLC
Features: OpenMP
```

One particular png (only after being resized by imagemagick!) gives

```
identify -quiet -ping -format \%m\\n resized.png

wx=0.280560, wy=0.295820, rx=0.639090, ry=0.339920
gx=0.318310, gy=0.641930, bx=0.124060, by=0.043880
PNG
```

The first two lines are on stderr and this is despite the quiet flag. MiniMagick uses subexec and subexec doesnt seem to have any way to separate stdout and stderr. But this prevents MiniMagick from identifying the correct mime_type, width and height.

**Comment by kml** [comment]
I'm locked on MiniMagick 3.8.1 with modified Subexec that always redirects STDERR to STDOUT (https://github.com/kml/subexec/commit/c2bea879d229b730ce9295c8ec95313ccf38b7cb#diff-727aed1973a92b3eedfb314e85fc8264R60).

My quick fix is adding prefix to format:
```ruby
# $ identify -quiet -format "mini_output:%w %h\n" 1561469481559109ca48426.png
# wx=0.312690, wy=0.328990, rx=0.639990, ry=0.330000
# gx=0.210000, gy=0.710000, bx=0.149990, by=0.059990
# mini_output:750 500
```
Patch: https://gist.github.com/kml/64c383e1ac0904c4bbaf
