### ISSUE TITLE
MiniMagick::Error (Command ("mogrify -size /tmp/mini_magick20131024-8415-1ue1kct.png") 

### ISSUE THREAD

**Issue by novito** [minimagick/minimagick#172]
Trying to get the size of an image that I open from a URL under a Ruby on Rails application, I got an error.

Here is what I do:

```
image = MiniMagick::Image.open("http://www.google.com/images/logos/logo.png")
      p "IMAGE SIZE >><<"
      p image.size
```

And got this:

MiniMagick::Error (Command ("mogrify -size /tmp/mini_magick20131024-8415-1ue1kct.png") failed: {:status_code=>1, :output=>"mogrify.im6: invalid argument for option `/tmp/mini_magick20131024-8415-1ue1kct.png': -size @ error/mogrify.c/MogrifyImageCommand/5689.\n"}):

I don't see any file on my tmp folder btw.

I am assuming the methods that are available are the ones that can be seen here http://www.imagemagick.org/script/mogrify.php

**Comment by frankpinto** [comment]
I'm running into this too, could you document what you it ended up being @novito to help others?

**Comment by janko-m** [comment]
@frankpinto Are you running the latest version of MiniMagick?

**Comment by AbhisekGIT** [comment]
I got the image size by running
> image[:size]
instead of image.size

**Comment by fabellonnoe** [comment]
how about image resize?
is it >image[:resize]?
