### ISSUE TITLE
Caption encode error

### ISSUE THREAD

**Issue by ghost** [minimagick/minimagick#191]
When getting trying to enter a caption...using the below

  image = MiniMagick::Image.open("public/output4.jpg")
  image.combine_options do |c|
    c.pointsize '30'
    c.gravity "center"
    c.size '360x'
    c.fill 'white'
    c.caption "this is a multi-line text paragraph this is a multi-line text paragraph"
  end
  image.write "public/output8.jpg"

I get the following error...

MiniMagick::Error (Command ("mogrify -pointsize 30 -gravity center -size 360x -fill white caption:this is a multi-line text paragraph this is a multi-line text paragraph /var/folders/1s/dh01tgyn3j39f673v1d_xywc0000gn/T/mini_magick20140103-15012-11w3xtz.jpg") failed: {:status_code=>1, :output=>"mogrify: no encode delegate for this image format `this is a multi-line text paragraph this is a multi-line text paragraph' @ error/constitute.c/WriteImage/1195.\n"}):

**Comment by revolter** [comment]
I have the same problem.

**Comment by janko-m** [comment]
Seems like `caption` and `label` should be regular options (`-caption '...' -label '...'`) instead of creation operators (`caption:'...' label:'...'`). I just pushed a fix with switched to this behaviour, @revolter can you try whether it works on master?

**Comment by revolter** [comment]
Any idea how can I do this in a `.gemspec`?

**Comment by janko-m** [comment]
It's not possible to pull from GitHub in a `.gemspec`. But you can actually apply the patch manually on your current MiniMagick (before executing any commands):

```rb
MiniMagick::Tool::CREATION_OPERATORS.delete("caption")
```

**Comment by revolter** [comment]
Ok, will do tonight and let you know.

**Comment by revolter** [comment]
I have

**Comment by janko-m** [comment]
@revolter Ah, sorry, I forgot that `CREATION_OPERATORS` is used already on load time to metaprogram methods. Maybe just try whether the `-caption` option works:

```rb
MiniMagick::Image.new(icon) do |builder|
  builder << "-caption" << "test"
end
```

**Comment by revolter** [comment]
@janko-m, This way doesn't cause a crash anymore.

Though, having:

```ruby
MiniMagick::Tool::Convert.new do |convert|
  convert << '-background' << '#0008'
  convert << '-fill' << 'white'
  convert << '-gravity' << 'center'
  convert << '-size' << "#{width}x#{height / 2}"
  convert << 'caption:test'
  convert << icon
  convert << '+swap'
  convert << '-gravity' << 'south'
  convert << '-composite'
  convert << icon
end
```

correctly adds a transparent bar with the text `test` over the bottom part of the image, but:

```ruby
MiniMagick::Image.new(icon) do |builder|
  builder.background('#0008')
  builder.fill('white')
  builder.gravity('center')
  builder.size("#{width}x#{height / 2}")
  builder << "-caption" << "test"
  builder << icon
  builder << '+swap'
  builder.gravity('south')
  builder.composite()
  builder << icon
end
```

doesn't.

**Comment by revolter** [comment]
@janko-m, When will you release a new version?
