### ISSUE TITLE
Not all return codes different from 0 are errors

### ISSUE THREAD

**Issue by danielalves** [minimagick/minimagick#257]
When  using the `compare` tool with `-metric AE`, image magick will return the number of different pixels. From the [docs](http://www.imagemagick.org/Usage/compare/):

**_The special "-metric" setting of 'AE' (short for "Absolute Error" count), will report (to standard error), a count of the actual number of pixels that were masked, at the current fuzz factor.**_

So mini magick should not raise an exception on this scenario.

**Comment by sensorsasha** [comment]
That's how you can do it now.

```ruby
result = nil
compare.call(false) do |stdout, stderr, status|
  result = stderr
end
result
```
