### ISSUE TITLE
let whiny = false in a configuration setting

### ISSUE THREAD

**Issue by giuseb** [minimagick/minimagick#281]
JPEGs produced by my Canon Pixma scanner are reported as corrupt by IM, in spite of the fact that they can be read and manipulated by any commonly available software, including IM itself.

Thus, the errors raised by mini_magick are disruptive and there should be an easily accessible way to override the behavior.

From what I gathered in the README, setting whiny=false can only be done when directly invoking  close-to-the-metal commands.

If so, it seems to me that a global configuration option shoud instead be available.

Unless I am missing something...

Cheers,
Giuseppe

**Comment by janko-m** [comment]
I completely agree. I really mind that ImageMagick returns status code 1 when it can actually process the image just fine, but I this configuration should be ok for working around this.

**Comment by janko-m** [comment]
4.0.2 [released](https://github.com/minimagick/minimagick/releases/tag/v4.0.2) with the fix.

**Comment by giuseb** [comment]
Thank you, much appreciated! Very nice gem.
Giuseppe
