### ISSUE TITLE
Complex convert command doesn't get executed properly. Possibly char escape issue.

### ISSUE THREAD

**Issue by hiromipaw** [minimagick/minimagick#286]
I am trying to execute the following command through minimagick:
    
    convert image1.jpg \( -clone 0 -background gray -shadow 80x5+5+5 \) -reverse -background none -layers merge +repage image2.png
    
I am sending it like this:

    MiniMagick::Tool::Convert.new do |builder|
        builder << jpg_image
        builder << '( -clone 0 -background gray -shadow 80x5+5+5 )'
        builder << '-reverse'
        builder << '-background none -layers merge +repage'
        builder << png_image
    end
    
It doesn't matter how I try to escape the parentheses I still get the following error:

    convert: unable to open image `( -clone 0 -background gray -shadow 80x5+5+5 )': No such file or directory
    
Any idea?

The command works from bash so it is a matter of sending it correctly through minimagick.

Thanks,
Silvia

**Comment by janko-m** [comment]
Does the following work?

```rb
MiniMagick::Tool::Convert.new do |builder|
  builder << jpg_image
  builder << '('
  builder.clone(0).background('gray').shadow('80x5+5+5')
  builder << ')'
  builder.reverse
  builder.background('none').layers('merge').repage.+
  builder << png_image
end
```

**Comment by hiromipaw** [comment]
:+1: Thanks!!

**Comment by janko-m** [comment]
I added a convenience method for this in the latest version, so now you can write it like this:

```rb
MiniMagick::Tool::Convert.new do |builder|
  builder << jpg_image
  builder.stack do |stack|
    stack.clone(0).background('gray').shadow('80x5+5+5')
  end
  builder.reverse
  builder.background('none').layers('merge').repage.+
  builder << png_image
end
```

**Comment by zealoushacker** [comment]
Why would `clone(0)` throw the following error:

`./convert.rb:12:in `clone': wrong number of arguments (1 for 0) (ArgumentError)`

when having the following code block:

```
#!/usr/bin/env ruby

require 'mini_magick'

MiniMagick.configure do |config|
  config.debug = true
end

MiniMagick::Tool::Convert.new do |convert|
  convert << 'input.png'
  convert.stack do |stack|
    stack.clone(0).fill('#292929').colorize(100)
  end
  convert.compose('overlay')
  convert.composite('output.png')
end
```

**Comment by lyonscchen** [comment]
same problem:

clone(0) throw the "wrong number of arguments (1 for 0) (ArgumentError)"

any ideas?
