### ISSUE TITLE
Converting pdf and resizing page

### ISSUE THREAD

**Issue by hiromipaw** [minimagick/minimagick#288]
Hello,
I am trying to convert the first page of a pdf to png so I am using the following:
   
    pdf = MiniMagick::Image.open(File.expand_path(path))
    pdf.pages.each_with_index do |page, index|
        save_png_images(to_images_tmp_path, index, page)
    end

    def save_png_images(to_images_tmp_path, index, page)
        image = "#{to_images_tmp_path}/#{index+1}.png"
        page.resize("1800x1800")
        page.write(image)
        images_upload(image, "#{index+1}", "png")
        @tmp_files << image
    end

Although pdf.resize doesn't work. And the file is saved with a 72dpi resolution. Any idea?

The error I receive is the following:
    
    `mogrify -resize 1800x1800 /tmp/mini_magick20150219-3-164ita9.pdf[1]` 
    failed with error:\nmogrify.im6: Postscript delegate failed `/tmp/mini_magick20150219-3-164ita9.pdf': 
    No such file or directory @ error/pdf.c/ReadPDFImage/677.\n", "error_class"=>"MiniMagick::Error", 
    "failed_at"=>1424351925.721004, "retry_count"=>9, "retried_at"=>1424356713.365212}
    2015-02-19T14:44:06Z 3 TID-hzurg WARN: `mogrify -resize 1800x1800   
    /tmp/mini_magick20150219-3-6r5cgw.pdf[1]` failed with error:
    2015-02-19T14:44:06.971201+00:00 app[worker.1]: mogrify.im6: Postscript delegate failed   
    `/tmp/mini_magick20150219-3-6r5cgw.pdf': No such file or directory @ error/pdf.c/ReadPDFImage/677.

**Comment by janko-m** [comment]
Does `pdf.resize` throw an error? If yes, include the backtrace.

**Comment by hiromipaw** [comment]
Thank Janko. I have updated the issue description since it was actually throwing the error in the loop when I try to resize each page.

**Comment by janko-m** [comment]
The thing is that `page` is only a "virtual" image:

```rb
page.path #=> /tmp/mini_magick20150219-3-164ita9.pdf[1]
```

`page.resize` actually uses Mogrify under the hood, which modifies images, so it can only accept real paths (in your case it would be given a "virtual" path which ends with `[n]`). You can, however, use Convert:

```rb
pdf = MiniMagick::Image.open(File.expand_path(path))

pdf.pages.each_with_index do |page, index|
  save_png_images(to_images_tmp_path, index, page)
end

def save_png_images(to_images_tmp_path, index, page)
  image = "#{to_images_tmp_path}/#{index+1}.png"
  MiniMagick::Tool::Convert.new do |convert|   #
    convert << page.path                       #
    convert.resize("1800x1800")                # <--------
    convert << image                           #
  end                                          #
  images_upload(image, "#{index+1}", "png")
  @tmp_files << image
end
```

It's a bit more verbose, but should do the trick.

**Comment by hiromipaw** [comment]
Thanks again! :) :+1:

**Comment by fatuhoku** [comment]
How do you see the commands being executed on the console?

**Comment by fatuhoku** [comment]
Also — surely the DPI is defined when the PDF is first read. Resizing the images coming out of `open` just stretches the image, right?

How can I say "read this PDF at 300dpi please?"

**Comment by janko-m** [comment]
@fatuhoku https://github.com/minimagick/minimagick#logging
