### ISSUE TITLE
`image.composite` produces a different result than `Tool::Composite.new`

### ISSUE THREAD

**Issue by notalex** [minimagick/minimagick#290]
I am running mini_magick version 4.1.0.

For the given example the output when using `Tool::Composite` retains the background transparency of the original image. When using `image.composite`, the transparency is lost.

```ruby
image_viewer = 'eog'

base = MiniMagick::Image.open('http://png-3.findicons.com/files/icons/1258/warcraft_volume_1/128/alliance_banner.png')
overlay = MiniMagick::Image.open('http://www.panic.com/blog/wp-content/themes/panic/images/icon_smile2.png')

combined_image = base.composite(overlay) do |c|
  c.geometry('+50+5')
end

system("#{ image_viewer } #{ combined_image.path }")

combined_image_result = Tempfile.new('image-')
MiniMagick::Tool::Composite.new do |c|
  c.geometry('+50+5')
  c << overlay.path
  c << base.path
  c << combined_image_result.path
end

system("#{ image_viewer } #{ combined_image_result.path }")
combined_image_result.close
```

This example should work on linux where `eog` is available. For other platforms please replace `eog` with an appropriate image viewer.

**Comment by janko-m** [comment]
First of all, thank you for providing me a great failing example which I can run and clearly see the error :heart: 

I see where the problem is. MiniMagick is defaulting the extension of the output image to "jpg", which doesn't support transparency. Will fix this in a bit.

**Comment by notalex** [comment]
Thanks for the quick response @janko-m
