### ISSUE TITLE
get the verbose info

### ISSUE THREAD

**Issue by lufeihaidao** [minimagick/minimagick#291]
Hi, I want to get the `Image statistics:Overall` information by executing `identify -verbose image.jpg`. How can I get this info besides fetching them from the returned string?

**Comment by janko-m** [comment]
Currently MiniMagick doesn't have this. But I can implementing it easily, as I see that it would really be useful. What do you think about calling it `MiniMagick::Image#details`?

**Comment by lufeihaidao** [comment]
@janko-m nice! And MiniMagick::Image#details is better to be a hash.

One more thing, when I run
```ruby
image = MiniMagick::Image.open("image.jpg")
a = ''
image.identify do |b|
  a = b.verbose
end
```
It seems that it just print out the result rather than assigning it to a. The var a is an instance of Identify. How can I get this verbose info?

**Comment by janko-m** [comment]
```rb
image = MiniMagick::Image.open("image.jpg")
details = image.identify { |b| b.verbose }
# or
details = image.identify(&:verbose)
```

Inside the block, the `identify` command hasn't executed yet, that's why you don't get the output assigned. Inside the block you're "building" the command, and it gets actually executed only when the block ends.

**Comment by lufeihaidao** [comment]
Thank you @janko-m !

**Comment by lufeihaidao** [comment]
I supposed to send a pull request. But I was trapped over when I run `rspec spec`.

```
Failures:

  1) With ImageMagick MiniMagick::Image#layers returns multiple images for GIFs, PDFs and PSDs
     Failure/Error: expect(psd.layers.count).to be > 1 unless MiniMagick.graphicsmagick?
     MiniMagick::Error:
       `identify spec/fixtures/image.psd` failed with error:
     # ./lib/mini_magick/shell.rb:22:in `run'
     # ./lib/mini_magick/tool.rb:92:in `call'
     # ./lib/mini_magick/tool.rb:53:in `new'
     # ./lib/mini_magick/image.rb:472:in `identify'
     # ./lib/mini_magick/image.rb:290:in `layers'
     # ./spec/lib/mini_magick/image_spec.rb:353:in `block (5 levels) in <top (required)>'
```

**Comment by janko-m** [comment]
It's strange that the error wasn't printed. Try doing `identify spec/fixtures/image.psd` on the command-line, and tell me what error you get. It may be that you need to compile ImageMagick with support for PSDs, but ImageMagick gives you a proper error message for that, so MiniMagick should properly transfer it.

**Comment by lufeihaidao** [comment]
I've tested it in my ubuntu machine. It works fine. The version info is
```
Version: ImageMagick 6.6.9-7 2014-03-06 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2011 ImageMagick Studio LLC
Features: OpenMP
```

However it doesn't work in my MAC machine. And executing `identify spec/fixtures/image.psd` return nothing stderr but a error code. The version info is
```
Version: ImageMagick 6.9.0-10 Q16 x86_64 2015-03-19 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: DPC Modules
Delegates (built-in): bzlib freetype jng jpeg ltdl lzma png tiff xml zlib
```

**Comment by janko-m** [comment]
Ok, it's happening only with the version "6.9.0", I will look into it. Could you maybe open it in a separate issue, so that I will remember to solve it?
