### ISSUE TITLE
imagemagick fails to identify psd with version "6.9.0"

### ISSUE THREAD

**Issue by lufeihaidao** [minimagick/minimagick#292]
#291 

`identify spec/fixtures/image.psd`

I've tested it in my ubuntu machine. It works fine. The version info is
```
Version: ImageMagick 6.6.9-7 2014-03-06 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2011 ImageMagick Studio LLC
Features: OpenMP
```

However it doesn't work in my MAC machine. And executing `identify spec/fixtures/image.psd` return nothing stderr but a error code. The version info is
```
Version: ImageMagick 6.9.0-10 Q16 x86_64 2015-03-19 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: DPC Modules
Delegates (built-in): bzlib freetype jng jpeg ltdl lzma png tiff xml zlib
```

**Comment by janko-m** [comment]
Thanks for raising the issue. The problem is that, if ImageMagick can't identify a PSD, there is nothing I can do about it. I'll just remove it from the test suite.
