### ISSUE TITLE
using input-option with convert

### ISSUE THREAD

**Issue by serixscorpio** [minimagick/minimagick#293]
I would like to execute `convert -density 300 input.pdf output.pdf`, but would like to use a stream as input.  So here's what I have tried:
```
image = MiniMagick::Image.read(in_stream)
image.format('pdf') do |convert|
  convert.render
  convert.density('300')
end
```
The resulting command array is: `["convert", "/tmp/mini_magick20150325-28568-1ahs2tp.pdf[0]", "-render", "-density", "300"]`

However, the ouput does not have the resolution at 300 dpi.  I think this might have something to do with the ordering of the `-density 300` argument.  In command line.  I get the desired effect if I do:

`convert -render -density 300 input.pdf output.pdf`

If I order `-density 300` as an output-option, then the output does not have the resolution at 300 dpi:

`convert input.pdf -render -density 300 output.pdf`

Is there some way to 're-order' the contents of the command array to treat '-density' as input-option instead of output-option?

**Comment by janko-m** [comment]
MiniMagick, besides the `MiniMagick::Image` API, also has a more direct API (which `MiniMagick::Image` internally uses), so you could do:

```rb
image = MiniMagick::Image.read(in_stream)
image.format("pdf")
MiniMagick::Tool::Convert.new do |convert|
  convert.render
  convert.density(300)
  convert << image.path
  convert << "ouptut.pdf"
end
```

**Comment by serixscorpio** [comment]
@janko-m thanks for your suggestion.  I confirm that works.  I actualy started with
```ruby
MiniMagick::Tool::Convert.new
```
before posting this question.  Is there some way to use the `Tool::Convert` API to accept a stream instead of a file path?

**Comment by janko-m** [comment]
Unfortunately, this isn't implemented yet. It's on my TODO list, but I never got to it. Maybe you could open a separate issue, so that I don't forget :)

**Comment by nofxx** [comment]
As of 2015, imagemagick's SVG handling isn't state-of-the-art.

First there's this argument order issue (if I got it correctly it's IM fault, not MM).
Side note: scale works, where density fails, strange, no?
Also you'll need to calculate the density (IM won't accept resize for SVG).
And as per some doc I can't find now, the recommended workflow for SVG is density it a lil up and resize down, now as binary, for float issues.

As a solution, and as IM is already using it internally, call `rsvg-converter` directly! 
Maybe, we could use minimagicks shell? Well, it's just a system() call anyways.
