### ISSUE TITLE
Suggestion: fail at gem install if ImageMagick is not installed

### ISSUE THREAD

**Issue by viktorbenei** [minimagick/minimagick#294]
Would be great if `gem install mini_magick` would fail if ImageMagick is not available, to make it harder to mess up the setup. Right now a bundle install or gem install will succeed and only the first run will generate an error. This can be an issue if the gem is used as part of another tool, like https://github.com/KrauseFx/frameit

**Comment by janko-m** [comment]
That's an interesting idea. I was thinking about it, however, it seems to me that Rubygems doesn't have support for checking something on install and preventing it. I was also thinking about asserting existence of ImageMagick/GraphicsMagick on `require "mini_magick"`.

However, I think both would instroduce a big backwards incompatibility. For example, someone might have it in Gemfile in Rails app, and forgot to remove it (and doesn't have ImageMagick/GraphicsMagick installed). Or some other gem could be requiring mini_magick, but only optionally use it (so the user of that gem might not even use the "mini_magick" part, and then updating the gem would also update mini_magick, and the user would get a failure).

**Comment by viktorbenei** [comment]
@janko-m that's absolutely a valid concern - maybe this could be included in a new major version of the gem?

**Comment by janko-m** [comment]
Ok, I will put it on my TODO list.
