### ISSUE TITLE
Can't use the quality operation on mogrify

### ISSUE THREAD

**Issue by erez-rabih** [minimagick/minimagick#297]
Although it is listed in their docs.

This is what I'm getting:

2.1.0 :013 > image.quality=70
NoMethodError: undefined method `quality=' for #<MiniMagick::Image:0x000001015b2410>

Am I missing anything?

**Comment by janko-m** [comment]
In MiniMagick all options are generated with method calls. So, in your case it's

    image.quality(70)

**Comment by erez-rabih** [comment]
Thanks for the prompt help with this ;)
