### ISSUE TITLE
Sometimes `Image::Info#cheap_info` raising meaningless ArgumentError

### ISSUE THREAD

**Issue by PikachuEXE** [minimagick/minimagick#299]
This is due to the result returned by `self["%m %w %h %b"].split(" ")` does not contain all necessary data.
In my case, it's missing `width` (and properly other info like `height` after it`
It raises `ArgumentError` since `Integer(nil)`causes it, but this error is too generic to be caught and handled.

**Comment by janko-m** [comment]
I will release the new version shortly, I just need to fix `MiniMagick::Image#details` to work properly.

**Comment by PikachuEXE** [comment]
Thanks!
