### ISSUE TITLE
Please add CHANGELOG or mention changes on Releases

### ISSUE THREAD

**Issue by PikachuEXE** [minimagick/minimagick#300]

**Comment by janko-m** [comment]
Thanks for reminding me, I kind if rushed these last 2 releases.

**Comment by janko-m** [comment]
Done!

**Comment by PikachuEXE** [comment]
Please add changelog for last 2 versions/releases >:)

**Comment by janko-m** [comment]
Sorry, thanks for reminding me, fixed!
