### ISSUE TITLE
Convert TTF to JPG with minimagick

### ISSUE THREAD

**Issue by frerotg** [minimagick/minimagick#301]
I would like convert my font (ttf) into image(jpg).
In command-line tool, I use this command : 
> convert -background none -fill black -font myfont.ttf -pointsize 300 label:\"a&\" test.png

I don't find in documentation how do it.

I try with this code

>       MiniMagick::Tool::Convert.new do |convert|
             convert << "-background" << "none"
             convert << "-fill" << "black"
             convert << "-font" << "myfont.ttf "
             convert << "-pointsize" << "300"
             convert << "label:\"a&\""
             convert << "output.jpg"
         end

But i have un full black image.

**Comment by janko-m** [comment]
The command

```sh
$ convert -background none -fill black -font myfont.ttf -pointsize 300 label:\"a&\" test.png
```

Is idiomatically implemented in MiniMagick as:

```rb
MiniMagick::Tool::Convert.new do |convert|
  convert.background("none")
  convert.fill("black")
  convert.font("myfont.ttf")
  convert.pointsize(300)
  convert << 'label:"a&"'
  convert << "test.png"
end
```

It should generate the same command as above. If you don't get the same result, turn on

```rb
MiniMagick.debug = true
```

and see on the standard output (logs) which command is being generated, and if it's the same one as the original command.

**Comment by frerotg** [comment]
Thank you, it works !

Now i would like using layer system to create a image compsoed by 2 ttf converted.
It's possible ?

**Comment by janko-m** [comment]
There is the `composite` CLI for ImageMagick, and MiniMagick interfaces with it through `MiniMagick::Tool::Composite`. Also, `MiniMagick::Image` has [`#composite`](https://github.com/minimagick/minimagick#composite) which you can also use.

However, ironically I'm not that experienced in ImageMagick itself, so maybe you could take a look on StackOverflow what are the commands, and then you can easily implement them in MiniMagick.
