### ISSUE TITLE
Pixel cache allocation failed 

### ISSUE THREAD

**Issue by frerotg** [minimagick/minimagick#302]
Hi, i have a problem with my convert command.

>MiniMagick::Tool::Convert.new do |convert|
      convert.background("none").fill(color_rgb.html).font('ttf/'+font2+'.ttf').pointsize(font_size)
      convert << 'label: ¡'
      convert << "test/#{p.id.to_s+'-layer-2'}.png"
  end

When i use this code i have this problem :

>MiniMagick::Error at /generate_pictures
`convert -background none -fill #ffffff -font ttf/SELIS001N.ttf -pointsize 300 label: ¡ test/1-layer-2.png` failed with error:
convert: pixel cache allocation failed ` ¡' @ error/cache.c/OpenPixelCache/3499.
convert: no images defined `test/1-layer-2.png' @ error/convert.c/ConvertImageCommand/3212.

But when i put a character before my '¡' like '&' for example it's work...

**Comment by janko-m** [comment]
You generated an invalid ImageMagick command, it's not a problem with MiniMagick. You have to compose a working command in the command-line, and just translate it directly into MiniMagick. You can set `MiniMagick.debug = true`, and then the shell commands will be logged so you can compare.

I'm not very familiar with `label:` option for ImageMagick, but I think there shouldn't be a space before "¡".
