### ISSUE TITLE
Minimagick gives 'identify.im6: no decode delegate for this image format' error

### ISSUE THREAD

**Issue by THPubs** [minimagick/minimagick#306]
In my Rails app, I just removed `Rmagick` and added `Minimagick`. Rmagick was too heavy. Things worked fine with Rmagick but in minimagick I get the following error :

    MiniMagick::Invalid: `identify /tmp/mini_magick20150518-10411-1qz42x8` failed with error:
    identify.im6: no decode delegate for this image format `/tmp/mini_magick20150518-10411-1qz42x8' @ error/constitute.c/ReadImage/544.
    from /home/pubudu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mini_magick-4.2.4/lib/mini_magick/image.rb:200:in `rescue in validate!'

The file url :

    [8] pry(main)> file.file.file
    => "/home/pubudu/Projects/istockseller/public/store/photos/thpubs/istockseller-13642162-wallhaven-61582.jpg"

The code im trying to run :

    MiniMagick::Image.read(file.file.file).first

**Comment by janko-m** [comment]
It seems like that ImageMagick itself doesn't recognize the format of the file you've given to him. Which doesn't make sense, because you're obviously passing in a JPEG image. What happens is that MiniMagick validates every image by default, and if it's something ImageMagick doesn't recognize, it throws an error. I would appreaciate if you could post a self-contained example showing the failure (maybe put the erroneous image on dropbox or something, so I can run it as well).

ImageMagick has been known to not be able to `identify` an image, but still be able to work with it (change its size etc). That's in my opinion an error with ImageMagick, but you can get around that by telling MiniMagick not to do any validation.

```rb
MiniMagick.configure do |config|
  config.validate_on_create = false
  config.validate_on_write = false
end
```

**Comment by NomNomCameron** [comment]
Part of what I store when I upload an image is the dimensions so when I run `image.width` (image being set to MiniMagick.read(file_path)) I get the same kind of `identify: no decode delegate for this image format` error.

Any idea as to what else this could be? Made sure ImageMagick is properly installed natively on both my Mac and Ubuntu machines, same result on both.

**Comment by janko-m** [comment]
That means that this particular image is corrupted (you say that it's a `.jpg`, but the content of the image apparently isn't), and that ImageMagick cannot work with it.

**Comment by THPubs** [comment]
Actually I tried several images taken from different sources. Wallpapers and photos from my own camera and phone.

**Comment by janko-m** [comment]
Does the error give you the format? If I `identify` a Ruby file, I get

```
identify: no decode delegate for this image format `RB' @ error/constitute.c/ReadImage/501.
```

Notice the `RB`. If you don't get any extension in your error message, it means the this image is corrupted. If you do get it, you may have to precompile ImageMagick with support for that format.

**Comment by THPubs** [comment]
Ah I think it can't recognize the format... In my above error it gives the format as : 
     `/tmp/mini_magick20150518-10411-1qz42x8'
Similar error for png files. Here's the format I got from a png file :
    `/tmp/mini_magick20150525-9454-7js2pz'

**Comment by janko-m** [comment]
ImageMagick can normally recognize the image by it's **content**, if it doesn't have an extension. So, if it's not able to recognize the image, then it's somehow corrupted. I don't think this is a problem with MiniMagick.

**Comment by THPubs** [comment]
Actually I tried it in two systems Ubuntu 15.04 and 14.04... Same result... With several different images same result. When I use Rmagick instead everything works fine. But when using MiniMagick it gives an error. I think it's a problem in MiniMagick

**Comment by janko-m** [comment]
Can you give me a self-contained example that I can run that reproduces the error?

**Comment by THPubs** [comment]
:-) You mean a working app that gives the issue?

**Comment by janko-m** [comment]
No, isolated, something like this:

```rb
```

**Comment by janko-m** [comment]
No, isolated, something like this:

```rb
require "mini_magick"
MiniMagick::Image.read("http://url-to-the-image.jpg")
# throws the error
```

This would be very helpful to me, because I don't know what image are you working with, or what your app looks like, so I can't debug your error.

**Comment by THPubs** [comment]
Ah sure. Now I think I got it :-) Im using it on my Carrierwave uploader like this :

    include CarrierWave::MiniMagick
    ....
    def store_data
        if file && model
            img = MiniMagick::Image.read(file.file).first
            model.width     = img.columns
            model.height    = img.rows
        end
    end

**Comment by janko-m** [comment]
It's close, but what I meant was if you could compose a code snippet which I can just copy paste into a file and execute with `ruby <failing_example>.rb` on the command-line, which raises the given error. So, without CarrierWave, because then you would have to include the whole Rails as well. You could upload your image that is failing to you to Dropbox or something and just replace the the URL in my previous example.

**Comment by THPubs** [comment]
Sure. Take this code for an example :
 
    img = MiniMagick::Image.read('https://www.google.lk/images/srpr/logo11w.png')

It simply takes the Google's logo... Running this will also fail.

**Comment by THPubs** [comment]
The exact error for the above code :

    MiniMagick::Invalid: `identify /tmp/mini_magick20150525-7064-1m1i9nk` failed with error:
    identify.im6: no decode delegate for this image format `/tmp/mini_magick20150525-7064-1m1i9nk' @ error/constitute.c/ReadImage/544.
    from /home/pubudu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mini_magick-4.2.0/lib/mini_magick/image.rb:200:in `rescue in validate!'

**Comment by janko-m** [comment]
Ah, got it, `MiniMagick::Image.read` accepts either strings or IO. If given a string, it will assume that's the content of an image, not a URL or path (so in the above case ImageMagick will identify a file with the content "https://www.google.lk/images/srpr/logo11w.png"). If you want to open from a path or URL, use `MiniMagick::Image.open`.

**Comment by THPubs** [comment]
Ahaa thanks a lot :-) I will try it and let you know if it fails :-D

**Comment by guikubivan** [comment]
Did this get resolved, why was it closed? I think I'm having a similar issue, where a file with path of "/tmp/cms_file_38.png20160129-23760-heol05" raises this error:
`mogrify: unable to open module file '/usr/lib64/ImageMagick-6.2.8/modules-Q16/coders/png20160129-23760-heol05.la': No such file or directory.`

**Comment by janko-m** [comment]
Can you give me a code snippet that causes this error? Otherwise I don't know what code you're running :)

**Comment by guikubivan** [comment]
Sure, this is what seems to do it in our staging environment `Linux 2.6.18-371.4.1.el5xen` with `ImageMagick 6.2.8 05/07/12 Q16`. Though now that I run the commands individually, it doesn't seem to fail nor raise an error, but it just prints out that message. So maybe it's nothing. 

    image = MiniMagick::Image.open("/tmp/cms_file_58.png20160201-21639-an32k2")
    geom =  "1650x1275>"
    image.resize(geom)
    => mogrify: unable to open module file `/usr/lib64/ImageMagick-6.2.8/modules-Q16/coders/png20160201-21639-an32k2.la': No such file or directory.

**Comment by janko-m** [comment]
The problem is that the file you're opening doesn't have the .png extension. The reason why ImageMagick is not erroring is probably because it recognizes that it's a PNG by the contents.

I'm assuming this file was created using the Tempfile standard library. By default it doesn't create the extension, but you can pass it explixictly:

```rb
Tempfile.new ["base", ".png"]
```

I don't know if you're in control of creating that Tempfile.

**Comment by guikubivan** [comment]
Great tip, will try that, and thank you.
