### ISSUE TITLE
Error about geometry or space

### ISSUE THREAD

**Issue by frerotg** [minimagick/minimagick#308]
I generate images via ttf. Each image has from 1 to 10 layers I then merged to create an image. I get an error on the second layer which I can not find the solution.

>MiniMagick::Error (`convert -background none -fill #000000 -font ttf/SELIS006N.ttf -pointsize 300 label: S public/pictogram_images/873-layer-2.png` failed with error:
      convert.im6: invalid geometry `+3.35542e+07+300.5' @ error/geometry.c/ParsePageGeometry/1407.
      convert.im6: unable to clone cache `/tmp/magick-1r313oY0': No space left on device @ error/cache.c/CloneDiskToDiskPixelCache/852.
      convert.im6: Image width exceeds user limit in IHDR `public/pictogram_images/873-layer-2.png' @ warning/png.c/MagickPNGWarningHandler/1754.
      convert.im6: Invalid IHDR data `public/pictogram_images/873-layer-2.png' @ error/png.c/MagickPNGErrorHandler/1728.
):

**Comment by janko-m** [comment]
What's the code that you ran?

**Comment by frerotg** [comment]
MiniMagick::Tool::Convert.new do |convert|
```                            
convert.background("none").fill(color_rgb2.html).font('ttf/'+font2+'.ttf').pointsize(font_size)
    convert << 'label: '+char2
    convert << "public/pictogram_images/#{p.id.to_s+'-layer-2'}.png"
end
```
becoming that with variable replacement

```                            
convert -background none -fill #000000 -font ttf/SELIS006N.ttf -pointsize 300 label: S public/pictogram_images/873-layer-2.png
```

**Comment by janko-m** [comment]
I'm don't understand, did MiniMagick produce an unexpected result? Do you get a correct result if you run it with ImageMagick on the command-line directly?

**Comment by frerotg** [comment]
I have a error too with command-line imagemagick

**Comment by janko-m** [comment]
It's better than to ask on places like StackOverflow. I can answer questions specific to MiniMagick, but I'm not really experienced in advanced usages of ImageMagick itself (even though it sounds a bit contradictory :smile:).
