### ISSUE TITLE
When calling type getting "private method `format' called"

### ISSUE THREAD

**Issue by anthonator** [minimagick/minimagick#314]
When calling `type` on an image object I am getting the following error:

```
private method `format' called for #<MiniMagick::Tool::Identify:0x007f96898fa878>
```

Here's my code:

```ruby
file_type = MiniMagick::Image.open(user.photo_url)

puts file_type.type
```

**Comment by anthonator** [comment]
Using Ruby 2.2.2p95

**Comment by anthonator** [comment]
This seems to pop up no matter what method I call. I tried `mime_type` and `width` with the same behavior.

**Comment by janko-m** [comment]
Are you using the latest version?
