### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by janko-m** [minimagick/minimagick#320]
I'm having difficulties finding time for MiniMagick maintenance recently, especially since I'm not really using it. I felt like I had my share at it, with the attempt to bring it to the next level with the 4.0 release, I hoped I helped. But now I would be happy if someone could take over :)

**Comment by sdrew** [comment]
I'd be happy to contribute and help maintain MiniMagick.

**Comment by janko-m** [comment]
Awesome! It would be great if you could take a look at the open issues and see if you could help in solving them (issue 312 is an important one, and also see if you can figure out issue 319). I would like at first that you send PRs with any changes you want to make, so that I can review them.

**Comment by janko-m** [comment]
I guess I'm still maintaining MiniMagick :)
