### ISSUE TITLE
Return value type of Image#size

### ISSUE THREAD

**Issue by fukayatsu** [minimagick/minimagick#321]
about #318

[carrierwaveuploader/carrierwave](https://github.com/carrierwaveuploader/carrierwave) requires Integer as a return value of `Image#size`.
So error occurs after https://github.com/minimagick/minimagick/commit/1b6ee9eb1af3acd9194bd7b339ea1cb03142f538

- https://github.com/carrierwaveuploader/carrierwave/blob/37cf31d34fa411db20e99cc654195020b06202c3/lib/carrierwave/sanitized_file.rb#L102
- https://github.com/carrierwaveuploader/carrierwave/blob/37cf31d34fa411db20e99cc654195020b06202c3/lib/carrierwave/sanitized_file.rb#L142
    - => `NoMethodError: undefined method 'zero?' for "76.7KB":String`

I think `#size` implicate that it returns Integer value in Ruby.

My suggestion is:

- Change return type of `Image#size` back to Integer
    - with https://github.com/minimagick/minimagick/commit/1b6ee9eb1af3acd9194bd7b339ea1cb03142f538#commitcomment-12480993 
- (optional) Add `Image#human_size` for  string value like `1.8MB` or `56KB`

**Comment by janko-m** [comment]
Thank you for reporting. Instead of your snippet I decided that, instead of parsing ImageMagick's human-readable size, it's much better to simply use `File.size(@path)`.

I yanked the previous version (4.2.8). I'm really sorry for the sloppy release.

**Comment by fukayatsu** [comment]
Thank you for your quick response :)

> it's much better to simply use File.size(@path).

:+1:
