### ISSUE TITLE
Minimagick always tells "ImageMagick/GraphicsMagick is not installed"

### ISSUE THREAD

**Issue by hailengc** [minimagick/minimagick#324]
Need some help please..., struggled for a whole day....

Ubuntu 14.04 64bit
mini_magick (4.2.3)  (tried with 4.2.10)

I'm pretty sure I installed imagemaick and graphicksmagick since  I can use both of them in command line. 

While in irb,
irb(main):001:0> require 'mini_magick'
=> true
irb(main):002:0> MiniMagick.cli
=> :imagemagick

and then when I do something like this in my code:

      image = MiniMagick::Image.open(origin_full_name)
      ImageVersionBag.each { |version|
        image.format(version[:format])
        image.resize(version[:with])
        version_full_path = "#{save_dir }/#{ naked_name + version[:suffix] }.#{version[:format]}"
        if File.exist?(version_full_path)
          File.delete(version_full_path)
        end
        image.write(version_full_path)
      }
    rescue Exception=>e
      $logger.error("create versions of image failed. #{e.message}")

I always get the exception says : ImageMagick/GraphicsMagick is not installed

**Comment by hailengc** [comment]
Fixed,add env PATH; at the top of  my nginx.conf. solved this.

**Comment by VincentVanGoat** [comment]
Hey how did you do this? I did not understand your second comment. It would be great if you explain this to me.

**Comment by hailengc** [comment]
just put a line before you nginx.conf

user www-data;
worker_processes 4;
pid /run/nginx.pid;
env PATH;   // here it is 

events {
        ...
}

http {
