### ISSUE TITLE
Error while generating an uploader using carrierwave

### ISSUE THREAD

**Issue by VincentVanGoat** [minimagick/minimagick#325]
Hey. I am trying to get users on my website to upload files on a google cloud bucket and for this, I am using Carrierwave which uses mini_magick.

When I try to use the command:

rails g uploader file

I get this error:

c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mini_magick-4.2.10/lib/mini_magick/configuration.rb:127:in cli': ImageMagick/GraphicsMagick is not installed (MiniMagick::Error) from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mini_magick-4.2.10/lib/mini_magick.rb:37:ingraphicsmagick?'
from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mini_magick-4.2.10/lib/mini_magick/tool.rb:111:in executable' from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mini_magick-4.2.10/lib/mini_magick/tool.rb:95:incommand'
from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mini_magick-4.2.10/lib/mini_magick/tool.rb:80:in call' from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mini_magick-4.2.10/lib/mini_magick/tool.rb:252:incli_options'
from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mini_magick-4.2.10/lib/mini_magick/tool.rb:205:in reload_methods' from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mini_magick-4.2.10/lib/mini_magick/tool.rb:191:ininitialize'
from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mini_magick-4.2.10/lib/mini_magick/tool.rb:21:in new' from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mini_magick-4.2.10/lib/mini_magick/tool.rb:21:ininherited'
from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mini_magick-4.2.10/lib/mini_magick/tool/animate.rb:6:in <class:Tool>' from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mini_magick-4.2.10/lib/mini_magick/tool/animate.rb:2:inmodule:MiniMagick'
from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mini_magick-4.2.10/lib/mini_magick/tool/animate.rb:1:in <top (required)>' from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mini_magick-4.2.10/lib/mini_magick/tool.rb:264:inrequire'
from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mini_magick-4.2.10/lib/mini_magick/tool.rb:264:in <top (required)>' from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mini_magick-4.2.10/lib/mini_magick.rb:54:inrequire'
from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mini_magick-4.2.10/lib/mini_magick.rb:54:in <top (required)>' from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/runtime.rb:76:inrequire'
from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/runtime.rb:76:in block (2 levels) in require' from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/runtime.rb:72:ineach'
from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/runtime.rb:72:in block in require' from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/runtime.rb:61:ineach'
from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler/runtime.rb:61:in require' from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler.rb:134:inrequire'
from c:/Users/Kanishka/googleprediction/prediction-app/config/application.rb:7:in <top (required)>' from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:141:inrequire'
from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:141:in require_application_and_environment!' from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:128:ingenerate_or_destroy'
from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:50:in generate' from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:inrun_command!'
from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/commands.rb:17:in <top (required)>' from bin/rails:4:inrequire'
from bin/rails:4:in `

'

Please help!

**Comment by tsmith1024** [comment]
I also saw this with 4.2.10, but while precompiling assets. Had previously been using 4.2.7 (I think) so set that explicitly and precompile works now. Any later versions don't appear to work after testing.

**Comment by VincentVanGoat** [comment]
Yes. It's fixed now because of the version change. Thank you!

**Comment by janko-m** [comment]
I will reopen this, since it needs to work with the latest version.
