### ISSUE TITLE
Infinite loop when `identify -verbose` contains an empty line

### ISSUE THREAD

**Issue by n0nick** [minimagick/minimagick#326]
When the output of ImageMagick's `identify -verbose` contains an empty line (such as the case of the image file attached), the code of `MiniMagick::Image::Info#details` goes into an infinite loop, because

[line 106](https://github.com/minimagick/minimagick/blob/master/lib/mini_magick/image/info.rb#L106) `level = line[/^\s*/].length / 2 - 1` results in `level == -1`
[line 107](https://github.com/minimagick/minimagick/blob/master/lib/mini_magick/image/info.rb#L107) `key_stack.pop until key_stack.size <= level` goes into infinite loop (because `key_stack`'s length will never be <= -1)

![bugreport](https://cloud.githubusercontent.com/assets/206795/9523169/53f770fc-4ce1-11e5-9afe-a822d4863969.png)

**Comment by n0nick** [comment]
The relevant empty line is line 71 in the following `identify -verbose` result:
https://gist.github.com/n0nick/3aacdce92f802f2d58fe

**Comment by janko-m** [comment]
Thanks for reporting. I see that you understand exactly where is the issue, would you care to submit a patch?

**Comment by n0nick** [comment]
I can definitely push a patch PR, the reason I haven't done it is I'm not sure how to test this within your specs...
I'll submit my patch and we can continue discussion there

**Comment by janko-m** [comment]
Hmm, yeah, I'm not sure how to stub this either within my tests. If you don't find a way, it's ok if you submit it without tests, I doubt this method will need any more refactoring.
