### ISSUE TITLE
Kernel.open undefined method gsub for nil:NilClass

### ISSUE THREAD

**Issue by chadwilken** [minimagick/minimagick#329]
I am using MiniMagick with CarrierWave with Ruby 2.2.0. When `Image.open` attempts to open the tempfile [here](https://github.com/minimagick/minimagick/blob/master/lib/mini_magick/image.rb#L89). It errors out with `undefined method 'gsub' for nil:NilClass`. The actual method that seems to cause the problem is `Kernal#open_uri_original_open`. I reverted to Ruby 2.1.4 and it worked fine.

**Comment by janko-m** [comment]
Can you show me the full stack trace? So this happens when you pass a *path* to MiniMagick::Image.open, not a URL, right?

**Comment by chadwilken** [comment]
Yea, this happens when I pass in the path to a tempfile. It was actually being passed from CarrierWave when performing calling `manipulate!`. Im at work now but will try to get you a full stacktrace later on tonight.

**Comment by janko-m** [comment]
@chadwilken Have you managed to come up with more details on this issue?

**Comment by chadwilken** [comment]
@janko-m I was trying to get it to reproduce in the current setup. I ended up ditching CarrierWave so I don't have the exact setup anymore. You can probably close this issue for now.

**Comment by janko-m** [comment]
@chadwilken Ok, thanks for the update.

Btw, curious, what gem are you using now instead of CarrierWave?

**Comment by chadwilken** [comment]
I ended up rolling my own solution. I inherited an existing ASP.NET app that I'm converting to Rails and it stores the full url instead of dynamically generating it like in carrierwave.
