### ISSUE TITLE
Suggest moving @info.clear

### ISSUE THREAD

**Issue by wezm** [minimagick/minimagick#330]
In Image [format](https://github.com/minimagick/minimagick/blob/master/lib/mini_magick/image.rb#L335) and [mogrify](https://github.com/minimagick/minimagick/blob/master/lib/mini_magick/image.rb#L495) there is an `@info.clear` call before performing the image manipulation. This is problematic if the block accesses the info and then say resizes the image as the info remains cached at the old dimensions. I think moving the `@info.clear` to after the block has been executed would avoid the issue.

**Comment by janko-m** [comment]
Thanks for reporting, I released 4.3.3 with the fix.
