### ISSUE TITLE
Are the files from image.path removed?

### ISSUE THREAD

**Issue by krzkrzkrz** [minimagick/minimagick#331]
```
image = MiniMagick::Image.open("input.jpg")
image.path #=> "/var/folders/k7/6zx6dx6x7ys3rv3srh0nyfj00000gn/T/magick20140921-75881-1yho3zc.jpg"
image.resize "100x100"
image.format "png"
image.write "output.png"
```

Above stores the files to `/var/folders/k7/6zx6dx6x7ys3rv3srh0nyfj00000gn/T/magick20140921-75881-1yho3zc.jpg`. Are these files removed automatically?

**Comment by janko-m** [comment]
Yes, MiniMagick uses the "tempfile" Ruby standard library, so this file eventually gets deleted (certainly when the Ruby process ends).
