### ISSUE TITLE
How can I pass command-line options directly???

### ISSUE THREAD

**Issue by USvER** [minimagick/minimagick#334]
I have already tested command-line options for imagemagick and now i want to use it but documentation only describes how i can construct command-line options using predefined method wich means i need to reconstruct my options again wich i don't want.

So my question is: Is it possible to somehow pass the command-line options directly to the "Tool"?

**Comment by janko-m** [comment]
You would only first need to transform them into an array, for proper escaping. For `convert` this would be:

```rb
MiniMagick::Tool::Convert.new do |convert|
  convert.merge! ["+antialias", "+distort", "Perspective", "0,0,4,5 89,0,45,46"]
end
```
