### ISSUE TITLE
mogrify: unrecognized option `-to-ary' 

### ISSUE THREAD

**Issue by travisdahlke** [minimagick/minimagick#338]
I'm not sure you'll consider this a bug or not, but it relates to the changes made in f444d28. I ran into it when upgrading to 4.3.x.
When used in combination with carrierwave, I had some code that looks like this:
```ruby
manipulate! do |img, index, options|
  img.combine_options do |c|
    c.gravity "northwest"
    c.crop "#{width}x#{height}+#{x}+#{y}"
    c.repage.+
  end
  img
end
```
This resulted in the error: "mogrify: unrecognized option \`-to-ary'". The problem being that this code was incorrectly using 3 block parameters (leftover from using rmagick at some point), when there should be only 1. So when Carrierwave yields the minimagick image to the block, it calls `to_ary` on the image. And since method_missing no longer filters out that method call, it simply adds it to the mogrify command.

I was able to just remove the errant block parameters in my case. I don't know if there is an obvious fix, but I wanted to at least document my issue somewhere.

**Comment by janko-m** [comment]
This seems to be the same one as https://github.com/minimagick/minimagick/issues/337. The latest version should have the fix, could you try that?

**Comment by travisdahlke** [comment]
I am using the latest version. Try it yourself:
```ruby
img = MiniMagick::Image.open('test.jpg')
img.to_ary
img.blah_de_blah
```
I think you have to override respond_to? also.

**Comment by janko-m** [comment]
Aha, yes, that's right, that was the `respond_to?`, sorry. Yes, that's by design, `MiniMagick::Image` is delegating all unknown methods to `MiniMagick::Tool::Mogrify`, which in turn makes an option out of the unknown method. There is no way to know what `mogrify`'s options are, I've tried the automagically generated methods, but as you saw on the commit description, it was causing thread-safety issues. So that's why all method missing methods are converted as MiniMagick options, I don't think there is any way around it.

**Comment by travisdahlke** [comment]
One option would be to create a blacklist for certain methods. Might be more trouble than it's worth though.

**Comment by janko-m** [comment]
Yeah, unfortunately we can't know what methods will someone call on the image. For example, `to_ary` is already an unexpected method to call on `MiniMagick::Image`.

**Comment by NeMO84** [comment]
Has this issue been fixed or do we have a work around for the error?

**Comment by janko-m** [comment]
I'm not seeing where CarrierWave calls `to_ary`, searching the master code doesn't yield any results. Which version/commit of CarrierWave are you using?

**Comment by NeMO84** [comment]
I am using:
- CarrierWave 0.10.0
- MiniMagick 4.4.0
- GraphicsMagick 1.3.23

Within my uploader, I am using a custom processor: 
```ruby
    def cover
      manipulate! do |frame, index|
        frame if index.zero?
      end
    end
    version :thumb do
      process :cover
      process :resize_to_fit => [200, 200]
    end
``` 
If I comment out the custom processor 'cover' then the error goes away. I have this custom processor because I need to generate thumbnails for PDFs.

**Comment by travisdahlke** [comment]
This is the same issue I was having. The problem is your block can only take one argument. Try something like this:
```ruby
def cover
  manipulate! do |image|
    image.frames.first
  end
end
```

**Comment by janko-m** [comment]
@travisdahlke Thank you so much, I was trying to debug this just now, and was trying to figure out where the `to_ary` was being called, but it was called Ruby when destructuring.

**Comment by NeMO84** [comment]
@travisdahlke , thank you. The `to_ary` problem was solved, but I am having issues generating thumbnails from PDFs. On to the next problem ;)
