### ISSUE TITLE
Trap or rescue SystemExit and cleanup tmpfiles.

### ISSUE THREAD

**Issue by envygeeks** [minimagick/minimagick#339]
When Minimagick gets told to leave and exit it leaves behind tons of tmp files.

**Comment by janko-m** [comment]
Hmm, that would require MiniMagick to record all the Tempfiles that have been created. But isn't the main feature of Ruby's Tempfiles that they automatically get deleted on exit? If not, can you provide me an example where this is not the case?

**Comment by envygeeks** [comment]
That only works in the case of clean signals like signals 1, 2 and 3, but if you send signal 9 (SIGKILL) then no, it won't cleanup because the GC does not run, which ultimately means you must ensure with your own insurance policy that it's unlinked or closed.

That's why in our own source we always ensure at the highest level through tracking some way that we unlink everything we create so that cruft is not left behind in the event we get told to exit now or else.

**Comment by envygeeks** [comment]
You can demonstrate this own your own:

```
jordon ~/development (master *) % pry; ll /tmp
[1] pry(main)> a = Tempfile.new("hello");
[2] pry(main)> .kill -9 $(pgrep -f pry);
Killed
total 72K
drwxrwxrwt  8 root   root    36K Oct 28 20:36 ./
drwxr-xr-x 24 root   root   4.0K Oct 28 05:36 ../
-rw-------  1 jordon jordon    0 Oct 28 20:36 hello20151028-13918-19qwtd7
```

```
jordon ~/development (master *) % pry; ll /tmp
[1] pry(main)> begin; a = Tempfile.new("hello"); ensure a.unlink if a; end;
[2] pry(main)> .kill -9 $(pgrep -f pry);
Killed
total 72K
drwxrwxrwt  8 root   root    36K Oct 28 20:38 ./
drwxr-xr-x 24 root   root   4.0K Oct 28 05:36 ../
```

**Comment by janko-m** [comment]
I see what you mean. I could add an `at_exit` hook (which is basically the same as `trap("EXIT")`), which gets executed on `kill`. However, if you're using `kill -9` like in your example, this cannot be trapped.

**Comment by envygeeks** [comment]
AFAIW the only way to do it is with `ensure` which does get ran no matter what.

**Comment by janko-m** [comment]
Hmm, but where would I put that `ensure` block? I cannot really wrap a `begin..rescue..end` around the whole Ruby process, that's mostly why `trap` exists (Avdi Grimm's latest RubyTapas).

**Comment by envygeeks** [comment]
That's a good question.  I'd have to look at the source to see because I don't know if you can by the nature of the way the lib works, which would be fair since we can do it ourselves since we can ensure what we do since we are the user.

**Comment by envygeeks** [comment]
We went ahead and just addressed this inside of our source because you brought up some good points, you are a lib and we are using you, it should be our job to cleanup where you can reliably cleanup since we are the one who created the mess through you but we created it none-the-less.
