### ISSUE TITLE
converting multi-layered tiff does not work

### ISSUE THREAD

**Issue by pejuko** [minimagick/minimagick#340]
Hi,

I've created multilayered tiff with a command:

    convert file.pdf -compress LZW file.tif

Then I'm trying to work with the multilayered tiff from minimagick like:
```ruby
    image.layers.each_with_index do |layer, idx|
          image_output = "#{local_file_path}_#{idx}_working_copy.png"
          layer.auto_orient
          layer.format 'png'
          layer.write image_output
    end
```
and with debugging turned on I'm getting following errors:

    identify /tmp/mini_magick20151105-32093-28ygod.tif
    identify /tmp/mini_magick20151105-32093-28ygod.tif
    mogrify -auto-orient /tmp/mini_magick20151105-32093-28ygod.tif[0]
    convert /tmp/mini_magick20151105-32093-28ygod.tif[0][0] /tmp/mini_magick20151105-32093-28ygod.tif[0]
    convert /tmp/mini_magick20151105-32093-28ygod.tif[0][0] /tmp/mini_magick20151105-32093-28ygod.tif[0]` failed with error:
    convert: unable to open image `/tmp/mini_magick20151105-32093-28ygod.tif[0]': No such file or directory

So I see the problem with double [0][0] at the end of filename. Can you fix this or am I doing something wrong?

Thanks

**Comment by janko-m** [comment]
Thanks for reporting, this should fix it.

**Comment by pejuko** [comment]
Don't hurry :-) We are just one step closer. Now I'm getting this errors:
```
[0.05s] identify /tmp/mini_magick20151105-12167-17qaa4s.tif
[1.06s] identify /tmp/mini_magick20151105-12167-17qaa4s.tif
[0.06s] mogrify -auto-orient /tmp/mini_magick20151105-12167-17qaa4s.tif[0]
[0.06s] convert /tmp/mini_magick20151105-12167-17qaa4s.tif[0] /tmp/mini_magick20151105-12167-17qaa4s.tif_0.png
[0.02s] mogrify -auto-orient /tmp/mini_magick20151105-12167-17qaa4s.tif[1]
/home/devel/.rvm/gems/ruby-2.1.5/bundler/gems/minimagick-32b4c328159b/lib/mini_magick/shell.rb:18:in `run': `mogrify -auto-orient /tmp/mini_magick20151105-12167-17qaa4s.tif[1]` failed with error: (MiniMagick::Error)
        from /home/devel/.rvm/gems/ruby-2.1.5/bundler/gems/minimagick-32b4c328159b/lib/mini_magick/tool.rb:79:in `call'
        from /home/devel/.rvm/gems/ruby-2.1.5/bundler/gems/minimagick-32b4c328159b/lib/mini_magick/tool.rb:40:in `new'
        from /home/devel/.rvm/gems/ruby-2.1.5/bundler/gems/minimagick-32b4c328159b/lib/mini_magick/image.rb:498:in `mogrify'
        from /home/devel/.rvm/gems/ruby-2.1.5/bundler/gems/minimagick-32b4c328159b/lib/mini_magick/image.rb:392:in `method_missing'
        from multilayered-tiff.rb:9:in `block in <main>'
        from multilayered-tiff.rb:7:in `each'
        from multilayered-tiff.rb:7:in `each_with_index'
        from multilayered-tiff.rb:7:in `<main>'
```

**Comment by janko-m** [comment]
Yeah, sorry, that was too rushed, I didn't even run your example after the alleged fix. I will take a look at this in the evening and try to provide an actual fix.

**Comment by janko-m** [comment]
Ok, dived into this finally. So, the problem isn't in MiniMagick, it generated the expected ImageMagick command `mogrify -auto-orient /tmp/mini_magick20151105-12167-17qaa4s.tif[1]`, but that command is for some reason failing (the .tif file still exists). I don't understand why it works for the first page, but not for the second page.

However, you probably want to use convert here instead of mogrify, here is the modified script that works:

```rb
image = MiniMagick::Image.open("file.tif")
image.layers.each_with_index do |layer, idx|
  MiniMagick::Tool::Convert.new do |convert|
    convert << layer.path
    convert.auto_orient
    convert << "#{local_file_path}_#{idx}_working_copy.png"
  end
end
```
