### ISSUE TITLE
Color tinting overlay not working as expected

### ISSUE THREAD

**Issue by zealoushacker** [minimagick/minimagick#341]
To my understanding, the following:

```
MiniMagick::Tool::Convert.new do |convert|
  convert << 'input.png'
  convert.stack do |stack|
    stack.clone.+
    stack.fill('#292929')
    stack.colorize(100)
  end
  convert.compose('overlay')
  convert.composite('output.png')
end
```

should result in:

```
convert input.png \( +clone -fill '#292929' -colorize 100 \) -compose overlay -composite output.png
```

Instead, this is what happens:

```
[0.07s] convert input.png ( -fill #292929 -colorize 100 ) -compose overlay -composite output.png
/Users/alex/.rvm/gems/ruby-2.1.0/gems/mini_magick-4.3.6/lib/mini_magick/shell.rb:18:in `run': `convert input.png ( -fill #292929 -colorize 100 ) -compose overlay -composite output.png` failed with error: (MiniMagick::Error)
convert: no images defined `output.png' @ error/convert.c/ConvertImageCommand/3230.
	from /Users/alex/.rvm/gems/ruby-2.1.0/gems/mini_magick-4.3.6/lib/mini_magick/tool.rb:79:in `call'
	from /Users/alex/.rvm/gems/ruby-2.1.0/gems/mini_magick-4.3.6/lib/mini_magick/tool.rb:40:in `new'
	from ./convert.rb:9:in `<main>'
```

This smells like a bug, because `+clone` does not get added inside the generated stack. Please advise.

I've also opened a [question](http://stackoverflow.com/questions/33557104/why-is-color-tinting-overlay-using-the-ruby-minimagick-gem-running-on-top-of-ima) on StackOverflow.

**Comment by janko-m** [comment]
Thanks for reporting this. I realize now what's going on. `MiniMagick::Tool::Convert` is using `#method_missing` to generate CLI options. However, the method `#clone` is already defined on `Object`, so instead of triggering `#method_missing`, the convert object is simply duplicated (because that's what `#clone` does). `MiniMagick::Tool::Convert` should really inherit from `BasicObject`, rather than from `Object`, so that these erors are prevented.

A temporary workaround is doing `convert << '+clone'` instead.

**Comment by zealoushacker** [comment]
Yep, I just came to this realization myself, when I did:

```
#!/usr/bin/env ruby

require 'mini_magick'

MiniMagick.configure do |config|
  config.debug = true
end

Dir.chdir(__dir__) do
  MiniMagick::Tool::Convert.new do |convert|
    convert << 'input.png'
    convert.stack do |stack|
      stack << '-clone'
      stack << 0
      stack.fill('#292929')
      stack.colorize(100)
    end
    convert.compose('overlay')
    convert.composite('output.png')
  end
end
```
Of course, I don't need `-clone 0`, as `+clone` is a good shortcut :+1: 

I'll go ahead and close out my StackOverflow question as well with your answer.

**Comment by zealoushacker** [comment]
@janko-m you will lose `attr_reader` and will have issues if you subclass `BasicObject`, because that and other methods you're using are in `Module`, which are included in `Object`. Perhaps `def clone` on `MiniMagick::Tool::Convert` instead?
