### ISSUE TITLE
Handle redirects from http:// to https://

### ISSUE THREAD

**Issue by chr1s1** [minimagick/minimagick#342]
Hi, 

we encountered a problem in our implementation and I would like to get your input on how to solve it. 

We currently use Mini Magick in the following way: 
```
image = MiniMagick::Image.open(img_url)
```

In this case the img_url is a url from a partner website (e.g. http://www.google.de/img/1.jpg). If a partner decides to get a ssl certificate, most of them do not change the urls. So they keep the http:// url but redirect it with a 302 or 301 redirect to the https version. 

That is where the current Mini Magick implementation fails as the URL returns a redirect and Mini Magick basically ignores it. Is there any solution to follow redirects inside Mini Magick, except catching the standard error and trying to get the image with https instead? 

Best
Chris

**Comment by janko-m** [comment]
MiniMagick uses the `open-uri` standard library for fetching images, and I think `open-uri` specifically forbids http <=> https redirects as it [considers it unsafe](https://github.com/ruby/ruby/blob/fbe967ec02cb65a7efa3fb8f3d747cf6f620dde1/lib/open-uri.rb#L245-L254) (in the documentation it says that it only forbids https => http, but it actually forbids both).

You could make a PR where you rescue `RuntimeError`, and check if the [message matches](https://github.com/ruby/ruby/blob/fbe967ec02cb65a7efa3fb8f3d747cf6f620dde1/lib/open-uri.rb#L226), parse the redirect out of the error messsage, and retry again with the redirected URL.

Alternatively (and the best solution) is to make a PR to Ruby core to enable https => http redirects (it's in Ruby, so it shouldn't be too difficult).

**Comment by chr1s1** [comment]
Instead of catching the RuntimeError I caught the Standard Error and run the same code with a https url. This works, but it does not seem to be the best and most efficient way.

**Comment by janko-m** [comment]
Yeah, I think you should try to catch specifically that "forbidden redirect" RuntimeError, and make the request to an actual redirect, like I described above.

**Comment by chr1s1** [comment]
thanks a lot! :+1:
