### ISSUE TITLE
Caption method not working

### ISSUE THREAD

**Issue by francisneedham** [minimagick/minimagick#344]
I'm trying to build a rails app that generates an image by overlaying a text over a default image.

I'm almost there - by using carrierwave + mini magick i have this method working :

    def generate_image
            message = self.description.upcase
            image = MiniMagick::Image.open('public/base.jpg')
            image.combine_options do |c|
                c.size '400x500'
                c.gravity 'NorthWest'
                c.fill 'black'
                c.strokewidth '2'
                c.pointsize '48'
                c.interline_spacing '-9'
                c.font "#{Rails.root}/public/black.ttf"
                c.draw "text 40,40 '#{message}'"
                c.antialias
            end
            self.image = image
end
the problem is that i want my text to fit the size i've specified - but I had no luck !

reading the Image Magick documentation I know that I should use the "caption" method instead of draw - but when I do so it throws out an orrible error :) :

failed with error: mogrify: no encode delegate for this image format `CAPTION' @ error/constitute.c/WriteImage/1167.

any clues ?

thanks !

**Comment by janko-m** [comment]
Have you tried generating this command in the command-line directly succesfully? Because although I am familiar with ImageMagick itself, I don't know the solution to this particular problem. However, if MiniMagick makes your result deviate from what you'd expect, I'd be happy to help. You can turn on logging to see what command MiniMagick generates.

**Comment by francisneedham** [comment]
Hi Janko - the problem is that the caption option is only for the convert command line and not the mogrify.

I've solved the issue - that was quite difficult - by using the MiniMagick::Tool::Convert

in the end I've generated the image in tmp folder using the convert command - and then merge it by using composite.

Thanks !

Francis

**Comment by revolter** [comment]
Why is `minimagick` using `mogrify` even when using `open` instead of `new`?

**Comment by janko-m** [comment]
@revolter Because `MiniMagick::Image.open` internally makes a copy of the file on initialization, and then uses `mogrify` on it. This allows it to continue sharing all the same logic as when `MiniMagick::Image.new` is used.

**Comment by revolter** [comment]
So is `convert` ever automatically used? Or it always uses `mogrify` behind the scenes?

**Comment by janko-m** [comment]
@revolter `convert` is essentially used only in `MiniMagick::Image#format`, otherwise it's all `mogrify`.

**Comment by revolter** [comment]
@janko-m Understoop, thanks for the explanation. Could you also please help me with https://github.com/minimagick/minimagick/issues/191#issuecomment-370275573?
