### ISSUE TITLE
Resize does not work properly with carrierwave

### ISSUE THREAD

**Issue by Sajonara** [minimagick/minimagick#345]
Hello,

I have a rails development project running within a docker container. It has ruby 2.2.3, rails 4.2.5 uses carrierwave 0.10.0 and mini_magick 4.3.6. I created an uploader

```
class ImageUploader < CarrierWave::Uploader::Base
 include CarrierWave::MiniMagick
 if Rails.env.production?
    storage :fog
  else
    storage :file
  end

  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end

  process :resize_to_fill => [200, 300]

  def extension_white_list
    %w(jpg jpeg gif png)
  end

end
```

and everything seems to work fine. At least I get no errors. The webserver is giving me no error as output. The file is uploaded but it is not resized accordingly. As it seems the system tries to resize them but the result is a picture with original dimensions which only shows the first 40 to 60 pixels and the rest of it stays blank.

Kind regards

**Comment by janko-m** [comment]
This is probably not a MiniMagick issue. MiniMagick deals only with the Ruby code that deviates from the equivalent ImageMagick command-line code. I'm assuming that CarrierWave generated incorrect ImageMagick logic itself here, so I will close this. If the ImageMagick command for this is actually incorrectly generated, I will reopen.

**Comment by Sajonara** [comment]
I can add to this that every "version" I create works fine. Only if I try to resize the uploaded file itself it does not work properly.
