### ISSUE TITLE
MiniMagick::Image.open('file.jpg') does not see updates/changes to 'file.jpg'

### ISSUE THREAD

**Issue by DanNordness** [minimagick/minimagick#354]
So say I have a file in my FS called `/home/dan/file.jpg` (let's say it's a picture of a dog) and I want to generate a new image from it – say `/home/dan/dog.jpg` – using MiniMagick.

```ruby
require 'mini_magick'
image = MiniMagick::Image.open('/home/dan/file.jpg')
image.write('/home/dan/dog.jpg')
exit
```

I open up `dog.jpg` in my image viewer and everything looks great - it's just a duplicate of the original. Exactly what I'd expect.

The problem however, is when I change or replace `/home/dan/file.jpg` with a modified or different file (say a picture of a cat)  – keeping the same exact path/filename – and repeat my code.

```ruby
require 'mini_magick'
image = MiniMagick::Image.open('/home/dan/file.jpg')
image.write('/home/dan/cat.jpg')
exit
```

When I open up `cat.jpg` - it's a picture of the same dog - as though it'd been created from the original `file.jpg` that no longer exists.

So I investigate further thinking maybe I'm screwing up and do a `puts image.path` and open up the temporary image file that MiniMagick creates in my image viewer. 

*Still a picture of a dog.* Then I think well maybe GC isn't working somehow and it's caching the temp file on the file name or something and then not deleting the temporary file.

Nope again - I replace `file.jpg` with something else and try again - new temp file path but same old picture of a dog.

Anyways it's driving me crazy so I try to reproduce on my Macbook (whereas this had all been in my ArchLinux VM) and it seems to be working without issue.

Is it possible this is a MiniMagick issue or is this something to do with something crazy going on with my file system or Arch?

**Comment by janko-m** [comment]
MiniMagick always creates a new tempfile from the file, so if you repeat `MiniMagick::Image.open` after you've modified `file.jpg`, it should create a Tempfile of whatever `file.jpg` currently is. It might be the problem with the filesystem or Arch, although it sounds like a really strange error. Did you try seeing if the `file.jpg` reads properly at the beginning of the script, before calling `MiniMagick::Image.open`?

I will close this as it doesn't seem to be a problem with MiniMagick.
