### ISSUE TITLE
mpc .cache files Left Behind

### ISSUE THREAD

**Issue by ylg** [minimagick/minimagick#358]
Here's a rough approximation of my use case.

    composite_data = MiniMagick::Image.new('foo.mpc')
    begin
      composite_data.run_command(:convert, '-size', '50x50', 'xc:white', 'foo.mpc')
      %w(https://upload.wikimedia.org/wikipedia/commons/7/70/Example.png https://upload.wikimedia.org/wikipedia/commons/7/70/Example.png).each do |item|
        item_data = MiniMagick::Image.open(item)
        begin
          item_data.combine_options do |c|
            c.gravity('center')
            c.resize('50x50!')
            c.rotate('90')
          end
          
          composite_data = composite_data.composite(item_data) do |c|
            c.geometry("+0+0")
          end
          
        ensure
          item_data.destroy!
        end
      end

      composite_data.format('png')
      composite_data.write('foo.png')
      
    ensure
      composite_data.destroy!
    end

After something like what this code ran, there would be several .cache files left behind in /var/folders, each roughly the size of the main composite image. In my case I'm trying to composite several hundred image files and finding the 40GB of space I've free is inadequate to the task due to several hundred files like 'mini_magick20160207-85825-1cblu43.cache' weighing 210MB each hanging around. Note that the filename in details.Artifacts.filename is does not even partially match the cache files being left around, so one can't forcibly delete them that way either.

**Comment by janko-m** [comment]
It seems that these *.cache files are specific to the .mpc format. Thanks for reporting, I'll push a fix shortly.

**Comment by janko-m** [comment]
Note that you're still not destroying one intermediate .mpc file, so I think you'll want to modify your code with the following:

```rb
composite_data = MiniMagick::Image.new('foo.mpc')
begin
  composite_data.run_command(:convert, '-size', '50x50', 'xc:white', 'foo.mpc')
  %w(https://upload.wikimedia.org/wikipedia/commons/7/70/Example.png https://upload.wikimedia.org/wikipedia/commons/7/70/Example.png).each do |item|
    item_data = MiniMagick::Image.open(item)
    begin
      item_data.combine_options do |c|
        c.gravity('center')
        c.resize('50x50!')
        c.rotate('90')
      end

      old_composite_data = composite_data # <----
      composite_data = composite_data.composite(item_data) do |c|
        c.geometry("+0+0")
      end

    ensure
      item_data.destroy!
      old_composite_data.destroy! # <----
    end
  end

  composite_data.format('png')
  composite_data.write('foo.png')

ensure
  composite_data.destroy!
end
```

**Comment by ylg** [comment]
Thank for the point about intermediary files from compositing, I was wondering how those worked.
