### ISSUE TITLE
MiniMagick loads image rotated at 90 degrees?

### ISSUE THREAD

**Issue by scande3** [minimagick/minimagick#360]
I've been using MiniMagick for some time now without issue... but recently a certain particular set of images keep auto-rotating when loaded into the library. I'm unsure what is causing this behavior so I thought I'd ask for any help on what the issue might be. Is it something with my installation of ImageMagick perhaps or am I missing something obvious?

Sample image: http://static.digitalcommonwealth.org/samples/test.tif

Code to duplicate:
`img = MiniMagick::Image.open('test.tif')`
`img.width`
`img.height`

(The above has the width as 6521 and the height as 2803. This is reversed from what a properties inspection of the file would reveal along with it being different than when you open it).

Thanks!

**Comment by janko-m** [comment]
Which dimensions does `identify test.tif` output? They should be the same as what MiniMagick returns, otherwise it's a bug in MiniMagick.

**Comment by scande3** [comment]
Running that returns:
`test.tif TIFF 6521x2803 6521x2803+0+0 16-bit sRGB 109.7MB 0.000u 0:00.000`

Trying exiv2 gives the same dimensions. However, opening up the image in a viewer gives me a 2803X6521 image. Anyone have a guess on why the discrepancy as I'd appreciate it? (Also fine with this being closed as indeed not anything with MiniMagick itself).

Verbose output:

> Image: test.tif
  Format: TIFF (Tagged Image File Format)
  Mime type: image/tiff
  Class: DirectClass
  Geometry: 6521x2803+0+0
  Resolution: 400x400
  Print size: 16.3025x7.0075
  Units: PixelsPerInch
  Type: TrueColor
  Base type: TrueColor
  Endianess: LSB
  Colorspace: sRGB
  Depth: 16-bit
  Channel depth:
    red: 16-bit
    green: 16-bit
    blue: 16-bit
  Channel statistics:
    Pixels: 18278363
    Red:
      min: 0 (0)
      max: 65535 (1)
      mean: 48025.5 (0.732822)
      standard deviation: 14459 (0.220631)
      kurtosis: 3.98561
      skewness: -2.37344
      entropy: 0.87261
    Green:
      min: 0 (0)
      max: 64657 (0.986603)
      mean: 44153.7 (0.673743)
      standard deviation: 13433.2 (0.204978)
      kurtosis: 3.23977
      skewness: -2.14401
      entropy: 0.908356
    Blue:
      min: 0 (0)
      max: 64444 (0.983352)
      mean: 38278.9 (0.584098)
      standard deviation: 12186.7 (0.185958)
      kurtosis: 1.70189
      skewness: -1.65803
      entropy: 0.945685
  Image statistics:
    Overall:
      min: 0 (0)
      max: 65535 (1)
      mean: 43486 (0.663554)
      standard deviation: 13391.9 (0.204348)
      kurtosis: 3.03384
      skewness: -2.01678
      entropy: 0.908884
  Rendering intent: Perceptual
  Gamma: 0.454545
  Chromaticity:
    red primary: (0.64,0.33)
    green primary: (0.3,0.6)
    blue primary: (0.15,0.06)
    white point: (0.3127,0.329)
  Background color: white
  Border color: srgb(223,223,223)
  Matte color: grey74
  Transparent color: black
  Interlace: None
  Intensity: Undefined
  Compose: Over
  Page geometry: 6521x2803+0+0
  Dispose: Undefined
  Iterations: 0
  Compression: None
  Orientation: RightTop
  Properties:
    date:create: 2016-03-18T15:34:02-04:00
    date:modify: 2016-03-18T15:32:29-04:00
    exif:DateTimeDigitized: 2013:02:13 09:04:02
    exif:DateTimeOriginal: 2013:02:13 09:04:02
    exif:ExposureTime: 0.0333333
    exif:ISOSpeedRatings: 50
    exif:SensingMethod: 2
    exif:ShutterSpeedValue: 4.90689
    icc:copyright: Copyright 1999 Adobe Systems Incorporated
    icc:description: Adobe RGB (1998)
    icc:manufacturer: Adobe RGB (1998)
    icc:model: Adobe RGB (1998)
    signature: 11870e1f796f8d4d8f2f05d693244b28c9b19356ae5f91f574927d337df7c58a
    tiff:alpha: unspecified
    tiff:artist: Sinar2
    tiff:endian: lsb
    tiff:make: Sinar Photography AG
    tiff:model: Sinarback eVolution 86, Sinar m
    tiff:photometric: RGB
    tiff:rows-per-strip: 1
    tiff:software: Adobe Photoshop Lightroom 4.3 (Macintosh)
    tiff:timestamp: 2013:02:13 15:12:57
  Profiles:
    Profile-8bim: 5970 bytes
    Profile-icc: 560 bytes
    Profile-xmp: 9432 bytes
  Artifacts:
    filename: test.tif
    verbose: true
  Tainted: False
  Filesize: 109.7MB
  Number pixels: 18.28M
  Pixels per second: 182.8MB
  User time: 0.090u
  Elapsed time: 0:01.099
  Version: ImageMagick 6.9.3-5 Q16 x86_64 2016-02-22 http://www.imagemagick.org

**Comment by janko-m** [comment]
Image viewers usually auto-rotate the image if it has some rotation metadata (e.g. you take a photo with a camera vertically). ImageMagick I think doesn't take this into account by default, but applying `-auto-orient` before extracting dimensions should fix it (I didn't try it):

```rb
oriented = image.auto_orient
oriented.width  # should be 2803
oriented.height # should be 6521
```
