### ISSUE TITLE
PseudoClass PNGs get larger on resize?

### ISSUE THREAD

**Issue by senorprogrammer** [minimagick/minimagick#367]
Hi,

When working with PseudoClass PNGs, MiniMagick seems to change them to DefaultClass, which makes them almost three times larger.

As an example, using the attached image and calling `resize` with the original dimensions (no resizing), the result is an increase from `274085` bytes to `816408`.

    file = './bench_guy.png'
    image = MiniMagick::Image.open file
    image.resize "#{image.width}x#{image.height}!"

Is there a way to preserve the PseudoClass? Thanks for any info.

![bench_guy](https://cloud.githubusercontent.com/assets/6413/15378741/fe59b244-1d1a-11e6-84b4-5a8f1d1d3450.png)

**Comment by janko-m** [comment]
The PseudoClass is apparently changed by ImageMagick, not MiniMagick, and honestly I don't know why. The thing is, MiniMagick only serves as a mediator to build an ImageMagick command, so if `mogrify -resize 500x500` (which is generated by your code) changes the class, you need to find out which ImageMagick command will produce the right behaviour, and then just generate it with MiniMagick.

**Comment by senorprogrammer** [comment]
I suspected that might be the case. Thanks for answering, and thanks for MiniMagick!
