### ISSUE TITLE
Return result without disk saving?

### ISSUE THREAD

**Issue by hiun** [minimagick/minimagick#368]
I would do additional manipulation to image (like base64 encoding). It is more efficient to return image in reference format that skips saving image to disk.

Is it possible in current version of minimagick?

**Comment by janko-m** [comment]
Through `MiniMagick::Image` it's not possible (and I don't think it could be). However, you can do it through via the low-level API:

```rb
content = MiniMagick::Tool::Convert.new do |convert|
  convert << path
  convert.resize("500x500")
  convert << "-" # stdout
end

base64 = Base64.encode64(content)
```

You can even read the input file from stdin:

```rb
convert = MiniMagick::Tool::Convert.new
convert << "-"
convert.resize("500x500")
convert << "-" # stdout
processed_content = convert.call(stdin: input_content)
```

**Comment by hiun** [comment]
Thanks for detailed examples! I may could not fully grasp API document before issuing.

**Comment by sairam** [comment]
I was able to use this to write as base64
```ruby
image = MiniMagick::Image.open("https://placehold.it/300x200")
base64 = Base64.encode64(image.to_blob).split("\n").join

```

**Comment by matthewPapke** [comment]
@sairam thank you for that
