### ISSUE TITLE
undefined method `split' for nil:NilClass

### ISSUE THREAD

**Issue by gerryats** [minimagick/minimagick#373]
I get this when I try to open a file for cropping. I have checked and confirm that the File path that I am passing as parameter exists and is vaild.

Error Stack:
mini_magick (4.5.1) lib/mini_magick/utilities.rb:17:in `which'
mini_magick (4.5.1) lib/mini_magick/configuration.rb:107:in`block in processor'
mini_magick (4.5.1) lib/mini_magick/configuration.rb:106:in `each'
mini_magick (4.5.1) lib/mini_magick/configuration.rb:106:in`detect'
mini_magick (4.5.1) lib/mini_magick/configuration.rb:106:in `processor'
mini_magick (4.5.1) lib/mini_magick/configuration.rb:123:in`cli'
mini_magick (4.5.1) lib/mini_magick.rb:38:in `graphicsmagick?'
mini_magick (4.5.1) lib/mini_magick/tool.rb:126:in`executable'
mini_magick (4.5.1) lib/mini_magick/tool.rb:110:in `command'
mini_magick (4.5.1) lib/mini_magick/tool.rb:92:in`call'
mini_magick (4.5.1) lib/mini_magick/tool.rb:40:in `new'
mini_magick (4.5.1) lib/mini_magick/image.rb:488:in`identify'
mini_magick (4.5.1) lib/mini_magick/image.rb:202:in `validate!'
mini_magick (4.5.1) lib/mini_magick/image.rb:113:in`block in create'
mini_magick (4.5.1) lib/mini_magick/image.rb:112:in `tap'
mini_magick (4.5.1) lib/mini_magick/image.rb:112:in`create'
mini_magick (4.5.1) lib/mini_magick/image.rb:34:in `read'
mini_magick (4.5.1) lib/mini_magick/image.rb:90:in`block in open'
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/open-uri.rb:37:in `open'
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/open-uri.rb:37:in`open'
mini_magick (4.5.1) lib/mini_magick/image.rb:89:in `open'

**Comment by maartenvanvliet** [comment]
On line https://github.com/minimagick/minimagick/blob/master/lib/mini_magick/utilities.rb#L17 the split is done on the `PATH` environment variable. It seems it is not set on your system.

Execute `env` in the command line to see the currently set environment variables and look for `PATH`.
