### ISSUE TITLE
minimagick ignores output path and writes  image to the wrong folder

### ISSUE THREAD

**Issue by mankind** [minimagick/minimagick#375]
I am trying to convert a pdf file  to jpeg  image where each page of the pdf will be saved as
an individual jpeg file.

The problem is that the jpeg images are written to the wrong folder . Instead of writing the images to the output path passed to page.write shown bellow, it is writing  the jpeg images to "/home/e/dev-gt/5/filter"

```
  pdf = MiniMagick::Image.open(File.expand_path("~/Downloads/inthewild-sample.pdf"))
  pdf.pages.each_with_index do |page, index| 
    page.write("/home/e/dev-gt/5/filter/public/uploads/upload/doc/1/page#{index}.png") 
  end
```

If this is not a bug what is the best way to make the images save to the correct  outpath.

**Comment by janko-m** [comment]
@mankind I wasn't able to reproduce, the following script produces the correct result:

```rb
require "mini_magick"

pdf = MiniMagick::Image.open("https://www.hikashop.com/media/com_hikashop/upload/pdf.png")
pdf.format("pdf") # convert to PDF
system "mkdir uploads"
pdf.pages.each_with_index do |page, index|
  page.write("uploads/page#{index}.png")
end
```

If this continues not to work, you can call `pdf.format("png", nil)`, and then ImageMagick should automatically convert each page into PNG, appending `-<idx>` to filename of each PNG page.
