### ISSUE TITLE
Reading images from url causes an error

### ISSUE THREAD

**Issue by guyisra** [minimagick/minimagick#376]
Reading an image from url via the following code causes an error

```
url = "https://i.ytimg.com/vi/tntOCGkgt98/maxresdefault.jpg"
image = MiniMagick::Image.new(url)
image.to_blob
Errno::ENOENT: No such file or directory @ rb_sysopen - https://i.ytimg.com/vi/tntOCGkgt98/maxresdefault.jpg
```

Is it possible to read an image from url without saving a copy to disk?

**Comment by guyisra** [comment]
I see in the code that it is not possible
Oh well..

**Comment by maartenvanvliet** [comment]
You can open an url directly through:

```
image = MiniMagick::Image.open("http://example.com/image.jpg")
image.contrast
image.write("from_internets.jpg")
```

**Comment by guyisra** [comment]
thakns @maartenvanvliet 
I thought its possible to to read from a url and not save to file

**Comment by janko-m** [comment]
@guyisra Yes, MiniMagick doesn't support it by itself, but you can do get content using `net/http` and pass it to stdin:

```rb
require "net/http"
uri = URI.parse("https://i.ytimg.com/vi/tntOCGkgt98/maxresdefault.jpg")
image_content = Net::HTTP.get(uri)

convert = MiniMagick::Tool::Convert.new
convert.stdin # or `convert << "-"`
convert << "output.png" # for example
convert.call(stdin: image_content)
```

A downside is that you cannot go through `MiniMagick::Image`, but I think it's often much better to use the command builder directly.

**Comment by achan** [comment]
Is it possible to provide multiple `stdin` parameters? For example I want to `+append` two images, both coming from stdin.

**Comment by janko-m** [comment]
I don't think that's possible, although you can search the ImageMagick documentation. If there is some separator that you can use for stdin to divide multiple images, you can just pass that kind of stdin to MiniMagick.
