### ISSUE TITLE
Graphicsmagick cli_version is nil

### ISSUE THREAD

**Issue by balasankarc** [minimagick/minimagick#377]
Hi,

I am using mini_magick's latest version on a Debian system with the following versions of imagemagick and graphicsmagick

```
$apt-cache policy graphicsmagick
graphicsmagick:
  Installed: 1.3.24+hg20160808-1
  Candidate: 1.3.24+hg20160808-1
$apt-cache policy imagemagick   
imagemagick:
  Installed: 8:6.8.9.9-7.2
  Candidate: 8:6.8.9.9-7.2
```

But, when I try to find the versions of them using cli_version, I get weird results

```
irb(main):001:0> require 'mini_magick'
=> true
irb(main):002:0> test = MiniMagick
=> MiniMagick
irb(main):003:0> test.cli = :imagemagick
=> :imagemagick
irb(main):004:0> test.cli_version
=> "6.8.9-9"
irb(main):005:0> test.cli = :graphicsmagick
=> :graphicsmagick
irb(main):006:0> test.cli_version
=> nil
irb(main):007:0> 

```

**Comment by janko-m** [comment]
[This](https://github.com/minimagick/minimagick/blob/b36339f1ffb2b42ae815d222bffc3b5d797e2281/lib/mini_magick.rb#L45-L48) is the code that's used for parsing out the version. What do you get when you run `gm identify -version`? Can you see from that output why this regex fails?

**Comment by janko-m** [comment]
Ok, I will close this, as I don't have enough information. If anyone continues having problems with this, I will need version outputs from both ImageMagick and GraphicsMagick, so that we can fix the regex.

```sh
$ identify -version    # ImageMagick
$ gm identify -version # GraphicsMagick
```
