### ISSUE TITLE
NoMethodError thrown when trying to call details method on an image

### ISSUE THREAD

**Issue by amishpatel1994** [minimagick/minimagick#379]
```
[45] pry(main)> MiniMagick::Image.open("REU_2242700.jpg").details
NoMethodError: undefined method `<<' for #<Hash:0x007fbdbba21748>
Did you mean?  <
```

The image I am trying to call details on is here:
![14699_reu_2242700](https://cloud.githubusercontent.com/assets/7492026/19041470/34ae125c-8956-11e6-86d0-a25c77a8c8f0.jpg)

**Comment by egh** [comment]
Probably a dup of #372
