### ISSUE TITLE
Carrierwave image magick convert png as white with transparent

### ISSUE THREAD

**Issue by manojvrv** [minimagick/minimagick#380]
Hi
I am using carrierwave(Image Magick) to convert a image as white transparent for Android notification icon.

http://developer.android.com/design/patterns/notifications.html

This my image uploader
```
class IconUploader < CarrierWave::Uploader::Base
  include CarrierWave::MiniMagick
  DIMENSIONS = [48,48]

  process :white_transparent

  def white_transparent
    manipulate! do |img|
      img.combine_options do |cmd|
        cmd.transparent("#ffffff")
        cmd.channel "a"
        cmd.separate
        cmd.negate
      end
      img = yield(img) if block_given?
      img
    end
  end

  def filename
    "notification_icon.png"
  end
end
```
But I am getting the image as 'black on white' instead of "white on black"

This how i want the transparent image to look like 
https://i.stack.imgur.com/knZhA.png

**Comment by janko-m** [comment]
Unfortunately, I'm not that knowledgable of ImageMagick itself, so I don't know how you would achieve the desired behaviour. It's better to ask that on the ImageMagick forum, or StackOverflow.

MiniMagick's only job is to generate ImageMagick shell commands, so I can only help in cases when you don't know how to generate a specific ImageMagick command, or if MiniMagick didn't generate the expected ImageMagick command.

**Comment by manojvrv** [comment]
@janko-m updated my question.
