### ISSUE TITLE
MiniMagick creating Tempfiles with -0 and -1 suffixes, getting confused, throwing an error

### ISSUE THREAD

**Issue by dukedorje** [minimagick/minimagick#39]
In my app, I open an image from a file path, then attempt to do some manipulation to it.  The first one works, the second errors out.

```
irb(main):024:0> img = MiniMagick::Image.open(path(descriptor, options))
=> #<MiniMagick::Image:0xc4b3488 @path="/tmp/mini_magick20110401-5076-1jrms7g.jpg", @tempfile=#<File:/tmp/mini_magick20110401-5076-1jrms7g.jpg (closed)>>
irb(main):025:0> img.resize("300x300")
=> ""
irb(main):026:0> img.resize("300x200")
Errno::ENOENT: No such file or directory - /tmp/mini_magick20110401-5076-1jrms7g.jpg
from /var/www/rails.dreamcatcher.net/shared/bundle/ruby/1.9.1/gems/mini_magick-3.2/lib/mini_magick.rb:369:in `unlink'
from /var/www/rails.dreamcatcher.net/shared/bundle/ruby/1.9.1/gems/mini_magick-3.2/lib/mini_magick.rb:369:in `destroy!'
from /var/www/rails.dreamcatcher.net/shared/bundle/ruby/1.9.1/gems/mini_magick-3.2/lib/mini_magick.rb:352:in `run'
from /var/www/rails.dreamcatcher.net/shared/bundle/ruby/1.9.1/gems/mini_magick-3.2/lib/mini_magick.rb:305:in `combine_options'
```

Yet, in my /tmp/, I see the files:
    mini_magick20110401-5076-1jrms7g-0.jpg
    mini_magick20110401-5076-1jrms7g-1.jpg

I can't tell when it will create multiple temp files, or when it creates just one.  When it creates one it works fine, but when it creates two, it always errors out.

(The server is running Ubuntu.)

**Comment by jayzes** [comment]
I've been wrestling with this same issue, and just stumbled across the cause (https://github.com/minimagick/minimagick/issues/168) - essentially, animated gifs get blown apart into frames, which cause those integer suffixes to get added, which in turn confuse minimagick. FYI in case anyone is still watching this thread.

**Comment by janko-m** [comment]
Yes, that's exactly what happens. When I took over maintaining MiniMagick few months ago, I really got frustrated when I realized that. *Image*Magick itself is doing it, not MiniMagick, so there is nothing we can do about it. But for me it only happened when encoding to a different format.
