### ISSUE TITLE
mogrify: Unrecognized option (-flatten) with graphicsmagick cli

### ISSUE THREAD

**Issue by jenlindner** [minimagick/minimagick#392]
I looked at a similar issue, #338, but my code doesn't have the structure that caused that problem (a block with more than one argument, mine only has one). Should I be doing this as a convert with -flatten as an option? Resize doesn't cause the same problem though, if I comment out 'flatten' 'resize(size)' is executed without any errors.

```        
  create_image do |xfrm|
    if size
       xfrm.flatten
       xfrm.resize(size)
    end
  end 
```
I'm using graphicsmagick 1.3.25 and minimagick 4.5.1, and graphicsmagick is my default cli.

**Comment by janko-m** [comment]
`MiniMagick::Image` uses mogrify under-the-hood, and it seems that while GraphicsMagick's `gm convert` has the `-flatten` CLI option, `gm mogrify` doesn't (it's not listed in `gm mogrify -help`). I don't know what's the reason for this inconsistency in GraphicsMagick, but can use the convert tool directly:

```rb
MiniMagick::Tool::Convert.new do |cmd|
  cmd << image.path # input
  cmd.flatten
  cmd.resize(size)
  cmd << image.path # output
end
```

**Comment by jenlindner** [comment]
Thanks!
