### ISSUE TITLE
Deprecated .details seems to give more accurate results than .data

### ISSUE THREAD

**Issue by 6wl** [minimagick/minimagick#397]
I have a PNG with a Palette Alpha as its color type.

Using identify -verbose <image> from the cli, or .details["Type"] on an instance of a mini_magick I correctly get what I'd expect
'PaletteAlpha'

However, using .data['type'] I get
'TrueColorAlpha'

Does the calling of convert before data is put into the hash and returned lose the palette information?

Thanks
![f22b3421-9bf0-481d-a80f-403b25886531](https://cloud.githubusercontent.com/assets/15330/22115203/05d8cf5e-de64-11e6-9f54-19bfe81651bc.png)

**Comment by janko-m** [comment]
@6wl Hmm, I get a different result locally, for me both `image.data["type"]` and `image.details["Type"]` return `PaletteAlpha` for the above image on latest ImageMagick.

```rb
require "mini_magick"

url = "https://cloud.githubusercontent.com/assets/15330/22115203/05d8cf5e-de64-11e6-9f54-19bfe81651bc.png"

puts "MiniMagick version:  #{MiniMagick.version}"
puts "ImageMagick version: #{MiniMagick.cli_version}"

image = MiniMagick::Image.open(url)

puts image.data["type"]
puts image.details["Type"]
```
```
MiniMagick version:  4.6.0
ImageMagick version: 7.0.4-7
PaletteAlpha
[MiniMagick] MiniMagick::Image#details has been deprecated, as it was causing too many parsing errors. You should use MiniMagick::Image#data instead, which differs in a way that the keys are in camelcase.
PaletteAlpha
```

I will close this as it's very likely that this issue is fixed by upgrading ImageMagick to the newest version.
