### ISSUE TITLE
run deskew?

### ISSUE THREAD

**Issue by alosada** [minimagick/minimagick#398]
Sorry to write an issue about this, but how do I get minimagick to run the deskew command? 
Its listed in MOGRIFY_COMMANDS list inside CommandBuilder but for the life of me I can't access it

**Comment by janko-m** [comment]
You are running an old version of MiniMagick. On the newest MiniMagick version you should be able to normally run `deskew`.

```rb
image.deskew("40%")
# or
image.combine_options do |cmd|
  cmd.deskew("40%")
end
```

If for any reason you cannot upgrade, can you tell me what is the error that you're getting? If it's listed in `MOGRIFY_COMMANDS`, you should be able to normally run it.

**Comment by janko-m** [comment]
I will close this, as this should work on latest MiniMagick.
