### ISSUE TITLE
Carrierwave #Resize_to_fill not working with Minimagick (only works with rMagick)

### ISSUE THREAD

**Issue by sono123** [minimagick/minimagick#402]
I configured my rails app to use Carrierwave for image uploads. As per the docs, I included the appropriate gem version for Multiple File Uploads. Inside the Carrierwave uploader, I included Minimagick. When I try to use the **#resize_to_fill** method, I get the following error, and the upload fails:

```
ActiveRecord::RecordInvalid: Validation failed: Images translation missing: en.errors.messages.mini_magick_processing_error
```

However, when I switch from Minimagick to Rmagick, it works perfectly? I'd prefer to use Minimagick if possible. Another wierd thing is other methods like **#resize_to_fit** work perfectly with both Minimagick and Rmagick.

Here are the important files:

_Gemfile_

```
gem 'rails',                   '5.0.1'
gem 'bcrypt',                  '3.1.11'
gem 'faker',                   '1.6.6'
gem 'carrierwave',              github: 'carrierwaveuploader/carrierwave'
gem 'mini_magick',             '4.5.1'
# gem 'rmagick',              '~> 2.15', '>= 2.15.4'
gem 'fog',                     '1.38.0'
gem 'will_paginate',           '3.1.0'
gem 'bootstrap-will_paginate', '0.0.10'
gem 'bootstrap',            '~> 4.0.0.alpha6'

source 'https://rails-assets.org' do
  gem 'rails-assets-tether', '>= 1.3.3'
end

gem 'puma',                    '3.4.0'
gem 'pg',   '0.18.4'
gem 'sass-rails',              '5.0.6'
gem 'uglifier',                '3.0.0'
gem 'coffee-rails',            '4.2.1'
gem 'jquery-rails',            '4.1.1'
gem 'turbolinks',              '5.0.1'
gem 'jbuilder',                '2.4.1'

group :development, :test do
  gem 'byebug',  '9.0.0', platform: :mri
end

group :development do
  gem 'web-console',           '3.1.1'
  gem 'listen',                '3.0.8'
  gem 'spring',                '1.7.2'
  gem 'spring-watcher-listen', '2.0.0'
end

group :test do
  gem 'rails-controller-testing', '0.1.1'
  gem 'minitest-reporters',       '1.1.9'
  gem 'guard',                    '2.13.0'
  gem 'guard-minitest',           '2.4.4'
end
```

_uploaders/images_uploader.rb_

```
class ImagesUploader < CarrierWave::Uploader::Base
  # Include RMagick or MiniMagick support:

  # include CarrierWave::RMagick (only this one works)
  include CarrierWave::MiniMagick

  process resize_to_fill: [900, 600]

  if Rails.env.production?
    storage :fog
  else
    storage :file
  end

  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end

  def extension_white_list
    %w(jpg jpeg gif png)
  end
end
```
Both Minimagick and Rmagick should support **#resize_to_fill** according to the docs as well as many examples that I've seen online. I also tried using different versions of Carrierwave and Minimagick but nothing worked. I even tried reinstalling Imagemagick. Still nothing. Any thoughts on this.

**Comment by janko-m** [comment]
@sono123 This is probably an issue with CarrierWave, and not MiniMagick, so the issue should be raised there.

Basically you need to find out why does image validation fail. Unfortunately, CarrierWave [swallows](https://github.com/carrierwaveuploader/carrierwave/blob/9ef68325dd5ea465b4d340af9a9def10934cd677/lib/carrierwave/processing/mini_magick.rb#L305) MiniMagick errors, if you're on a relatively new Ruby version (I think Ruby 2.3+) which has `Exception#cause`, you can tell CarrierWave to propagate any processing errors, rescue `CarrierWave::ProcessingError`, and call `#cause` on that error to retrieve the original MiniMagick error, and raise that one to see the command that failed and error message that ImageMagick returned.

```rb
CarrierWave.configure do |config|
  config.ignore_processing_errors = true
end
```
```rb
begin
  # attaching code
rescue CarrierWave::ProcessingError => error
  raise error.cause
end
```

Additionally you could also turn on MiniMagick logging to see exactly what commands are being executed:

```rb
MiniMagick.logger.level = Logger::DEBUG
```

**Comment by jrothrock** [comment]
I'm currently having this issue as well, but on production. I'm getting the following error:
```
MiniMagick::Invalid (`identify /tmp/mini_magick20170301-15568-abuqr9.mov` failed with error:
identify: delegate failed `"ffmpeg" -v -1 -i "%i" -vframes %S -vcodec pam -an -f rawvideo -y "%u.pam" 2> "%Z"' @ error/delegate.c/InvokeDelegate/1310.
identify: unable to open image `/tmp/magick-15578WTub7KbBHjoR.pam': No such file or directory @ error/blob.c/OpenBlob/2712.
```
I have both ffmpeg and imagemagick installed. I'm using Ubuntu

**Comment by janko-m** [comment]
@jrothrock It looks like ImageMagick cannot find some file (`/tmp/magick-15578WTub7KbBHjoR.pam`). When you try to call `identify any-video.mov` directly on the console, do you get the same error or is everything fine?

**Comment by jrothrock** [comment]
Yeah it gave an error. In the end, it turns out I actually didn't have ffmpeg installed. Thanks for replying so quickly

**Comment by frank6060** [comment]
en.errors.messages.mini_magick_processing_error

**Comment by jrothrock** [comment]
How does on use ```MiniMagick.logger.level = Logger::DEBUG```?

**Comment by dented** [comment]
> How does on use `MiniMagick.logger.level = Logger::DEBUG`?

I know this is old, but I came across it when I was having issues with cropping images using minimagick and carrierwave.

To add logs in Rails I made ```config/initializers/minimagick.rb``` and added the below code to get logs from minimagick 
```
MiniMagick.configure do |config|
  config.cli = :imagemagick # or :graphicsmagick or :imagemagick or :imagemagick7
  config.logger = Rails.logger
end
```
