### ISSUE TITLE
Rubyforge is dead

### ISSUE THREAD

**Issue by scarroll32** [minimagick/minimagick#403]
The gem is linking to Rubyforge.

**Comment by janko-m** [comment]
@seanfcarroll Heh, I noticed it just the other day as well, but I don't have permissions to change the project description. @bensie are you maybe able to change remove the RubyForge URL?

**Comment by janko-m** [comment]
@bensie Sorry for pinging again, when you have a moment could just just remove the RubyForge URL from this repository description so that we can close this issue? 😃

**Comment by bibstha** [comment]
I got confused today too, had to go to rubygems.org > mini_magick > Documentation. Would be great to have the changed URL in the description.

**Comment by janko** [comment]
Finally got the owner permissions, removed the dead RubyForge link.

**Comment by bensie** [comment]
@janko Sorry! I'm furious at 2017 me!
