### ISSUE TITLE
incompatible with imagemagick 7

### ISSUE THREAD

**Issue by alex-mayr** [minimagick/minimagick#404]
Hi,

apparently mini_magick doesn't work for imagemagick 7. example:

`MiniMagick::Error: `mogrify -crop! 0 0 0 0 /tmp/mini_magick20170216-2378-13om7q6.jpg` failed with error:
mogrify: unrecognized option `-crop!' @ error/mogrify.c/MogrifyImageCommand/4511.

	from /home/alex/.rvm/gems/ruby-2.4.0/gems/mini_magick-4.6.1/lib/mini_magick/shell.rb:18:in `run'
	from /home/alex/.rvm/gems/ruby-2.4.0/gems/mini_magick-4.6.1/lib/mini_magick/tool.rb:92:in `call'
	from /home/alex/.rvm/gems/ruby-2.4.0/gems/mini_magick-4.6.1/lib/mini_magick/tool.rb:40:in `new'
	from /home/alex/.rvm/gems/ruby-2.4.0/gems/mini_magick-4.6.1/lib/mini_magick/image.rb:515:in `mogrify'
	from /home/alex/.rvm/gems/ruby-2.4.0/gems/mini_magick-4.6.1/lib/mini_magick/image.rb:406:in `method_missing'
`

`]$ mogrify --version
Version: ImageMagick 7.0.3-7 Q16 x86_64 2016-11-18 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2016 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP 
`

will this be updated?

**Comment by alex-mayr** [comment]
please forget about this. must have been picnic I guess

**Comment by alex-mayr** [comment]
reopen. altough you can make it use the correct method (-crop instead of -crop!) the args seem to be wrong apparently:

`MiniMagick::Error (`mogrify -crop 0 0 300 300 /tmp/mini_magick20170216-9690-1y2xr69.jpg` failed with error:
mogrify: unable to open image '0': No such file or directory @ error/blob.c/OpenBlob/2695.
mogrify: no decode delegate for this image format `' @ error/constitute.c/ReadImage/508.
mogrify: unable to open image '300': No such file or directory @ error/blob.c/OpenBlob/2695.
mogrify: no decode delegate for this image format `' @ error/constitute.c/ReadImage/508.
mogrify: unable to open image '300': No such file or directory @ error/blob.c/OpenBlob/2695.
mogrify: no decode delegate for this image format `' @ error/constitute.c/ReadImage/508.
):
`

**Comment by janko-m** [comment]
Can you show me the MiniMagick code you're executing?

**Comment by alex-mayr** [comment]
Hi @janko-m.

thanks for your reply.

here it is:

`			manipulate! do |imgrvm |
				x = model.crop_x.to_i
				y = model.crop_y.to_i
				w = model.crop_w.to_i
				h = model.crop_h.to_i
				img.crop(x,y,w,h)
			end`

**Comment by janko-m** [comment]
If ImageMagick 7 changed `-crop` arguments, that doesn't mean that MiniMagick is incompatible with ImageMagick 7. MiniMagick is just a thin wrapper around ImageMagick, if any breaking changes happen in ImageMagick, you need to update your MiniMagick code.

According to the documentation, the [`-crop`](https://www.imagemagick.org/script/command-line-options.php#crop) ImageMagick options accepts a specific "[geometry](https://www.imagemagick.org/script/command-line-processing.php#geometry)" string, not just a list of arguments. Something like this should work:

```rb
manipulate! do |img|
  x = model.crop_x.to_i
  y = model.crop_y.to_i
  w = model.crop_w.to_i
  h = model.crop_h.to_i
  img.crop("#{w}x{h}+#{x}+#{y}")
end
```

**Comment by alex-mayr** [comment]
ok, thank you. I guess I will go back to rmagick then. I need some encapsulation of breaking changes here.
