### ISSUE TITLE
Animated gif

### ISSUE THREAD

**Issue by hugohow** [minimagick/minimagick#406]
Hello,

Thanks for this great library,
Is there any way to produce an animated gif with mini-magick ? Or do I have to use Rmagick ?
Thanks for your response.

**Comment by janko-m** [comment]
There is no special API planned for producing animated GIFs at the moment. If you know how to create animated GIFs using ImageMagick CLI, then you can do it in MiniMagick as well, otherwise you'd have to use RMagick.
