### ISSUE TITLE
Quality bug when .png?

### ISSUE THREAD

**Issue by brbucci** [minimagick/minimagick#407]
Hi, if i`m not mistaken, there`s a bug when i try to reduce quality image (for images with .png extension), it works only the following: 

    version :rich_quality do
      process quality: 85 90 or 75%
      # process convert: 'jpg'
    end

when it`d jpeg, woorks fine

**Comment by janko-m** [comment]
This is most likely a bug in ImageMagick itself, as MiniMagick simply converts Ruby method calls into ImageMagick command-line options. You should get the same behaviour if you try to process the image directly on the command-line:

```sh
$ mogrify -quality 85 /path/to/image
```
