### ISSUE TITLE
Converting to Grayscale behaves differently based on OS

### ISSUE THREAD

**Issue by SARAN-thala** [minimagick/minimagick#411]
_**Mini Magick Version : 3.8.0**_
_**Ruby Version : 2.3.3**_

```
require 'mini_magick'

image = MiniMagick::Image.open('https://cdn-images-1.medium.com/max/1600/1*eP0V-xfRWfW3QHJhALJ5RA.jpeg')
image.colorspace 'gray'
image.write('output.jpg')
```
I ran the above code in Mac OSX and Ubuntu 14.04 but the ouput seems to different for different operating systems. In Ubuntu i am getting a more darkened image.

Is there a way (like passing any other parameters) where I can get a similar image in Ubuntu like I got in Mac.

(Attached both the output images (Mac and Ubuntu))

**Mac OSX output Image**
![mac](https://cloud.githubusercontent.com/assets/15261261/25226987/81568078-25e4-11e7-82ed-ae959e8a8e7d.jpeg)

**Ubuntu Output Image**
![ubuntu](https://cloud.githubusercontent.com/assets/15261261/25227009/9769174a-25e4-11e7-96f1-38d0c3d318f2.jpg)

**Comment by janko-m** [comment]
MiniMagick only translates Ruby code into the ImageMagick command, if ImageMagick for `-colorspace gray` produces images with different lighting on different operating systems, that bug should be reported on the ImageMagick bug tracker.
