### ISSUE TITLE
working on windows with ImageMagick 7.0.5?

### ISSUE THREAD

**Issue by phuongnd08** [minimagick/minimagick#414]
Look like ImageMagick 7.0.5 Q15 Windows version is not providing mogrify nor gm, instead it is providing "magick" command so minimagick could not use yet?

**Comment by janko-m** [comment]
From [this thread](http://www.imagemagick.org/discourse-server/viewtopic.php?t=29582) it seems that ImageMagick installer provides you the option to install "legacy components" (`mogrify.exe`, `convert.exe` etc), so perhaps you can try that.

**Comment by janko-m** [comment]
I will close this, as choosing "install legacy components" in the ImageMagick Windows installer should resolve the problem.

**Comment by phuongnd08** [comment]
Okay, thank you. I ended up install Graphicsmagick instead.
