### ISSUE TITLE
Supporting SVG files?

### ISSUE THREAD

**Issue by tylerbhughes** [minimagick/minimagick#415]
In your README's examples you use JPG and PNG with `MiniMagick::Image.open`. I don't see any mention of SVG, but I know that ImageMagick supports SVG files. If I pass an SVG file into `MiniMagick::Image.open` will it work the same as if I passed in a PNG or JPG file?

**Comment by janko-m** [comment]
@tylerbhughes Yes, MiniMagick is a fairly thin wrapper around ImageMagick, so anything that ImageMagick supports, MiniMagick should support too.

**Comment by Sohair63** [comment]
Minimagic is not working for svg
```
Image Failed to manipulate with MiniMagick, maybe it is not an image? Original Error: `mogrify -resize 100x100 /tmp/mini_magick20190725-8218-j0jl53.svg` failed with error:\n
```

**Comment by janko** [comment]
Or rather ImageMagick. MiniMagick will raise an exception when the ImageMagick command returns a nonzero status code.

**Comment by Sohair63** [comment]
RMagick is working fine, I used that now.
