### ISSUE TITLE
`mogrify` breaks ruby's method cache

### ISSUE THREAD

**Issue by printercu** [minimagick/minimagick#417]
Hi!

I've found that `#mogrify` defines method every time it's called here https://github.com/minimagick/minimagick/blob/master/lib/mini_magick/image.rb#L559-L564

Every method definition in MRI clears method cache in the whole ruby process. Here is console output with sample call:
```
2.3.3 (main):0[19] > RubyVM.stat[:class_serial]
=> 321219
2.3.3 (main):0[20] > MiniMagick::Image.new('tmp/in.png').mogrify
=> #<MiniMagick::Image:0x007f93453c38d8 @path="tmp/in.png", @tempfile=nil, @info=#<MiniMagick::Image::Info:0x007f93453c38b0 @path="tmp/in.png", @info={}>>
2.3.3 (main):0[21] > RubyVM.stat[:class_serial]
=> 321221
```

Can this `def` be moved to Mogrify class?

**Comment by janko-m** [comment]
I see, that's definitely not ideal. I will probably remove this then, and rely on people knowing the difference between calling methods on `MiniMagick::Image`, and adding options to `mogrify`.

**Comment by printercu** [comment]
It can be kept to save somebody from debugging :) I've moved it to MogrifyRestricted class in my PR.
