### ISSUE TITLE
combine_options not working with a font specified by absolute path

### ISSUE THREAD

**Issue by SammyTbeile** [minimagick/minimagick#419]
I've been using MiniMagick very successfully and happily but recently we've attempted to switch fonts and I'm having issue with the font being recognized. The code were using is:

```rb
    font = "#{::Rails.root}/public/font/brandon_bld.ttf"
    charity_image.combine_options do |image|
      image.font font
      image.fill "white"
      image.pointsize 72
      image.gravity "center"
      image.draw "text 0,0 '#{charity_percent}'"
    end
```

However, any time that I try to run this I get the error:

```
mogrify: unable to read font <font path matching font> @ warning/annotate.c/RenderType/985
```

**Comment by janko-m** [comment]
This is not a bug in MiniMagick, MiniMagick simply generates the ImageMagick command. Your MiniMagick code generates the following ImageMagick command:

```
mogrify -font <path-to-font> -fill white -pointsize 72 -gravity center draw "text 0,0 '<percent>'"
```

If this command fails with an error, than you need to determine what would be the correct ImageMagick command, and then generate that new command with MiniMagick.

It's best to ask ImageMagick-related questions on the ImageMagick forums.
