### ISSUE TITLE
Crop not working

### ISSUE THREAD

**Issue by daveroberts** [minimagick/minimagick#424]
When running the crop command, mogrify splits the image into multiple files:

/tmp/mini_magick20170720-2025-1iiew1z becomes

/tmp/mini_magick20170720-2025-1iiew1z-0 and
/tmp/mini_magick20170720-2025-1iiew1z-1

however, the path and tempfile on the image don't change, so a call to write will fail.

**Comment by janko-m** [comment]
`MiniMagick::Image` doesn't detect when ImageMagick split the file into multiple images (there is no `ImageList` API like in RMagick), so you have to handle that manually. Just curious, if MiniMagick detected that, what would be the correct behaviour of `MiniMagick::Image#write` in that case? The fact that ImageMagick returned multiple images means the destination format was a single-layer format (e.g. JPEG).

**Comment by daveroberts** [comment]
Thank you for your reply.

Is there a way to manually specify which file you want to target using MiniMagick (either -0 or file -1)?

In my specific example, the crop operation was to crop an area 350x350.  Image -0 contained a png of 350x350.  Image -1 contained the rest of the image outside of, which was 350x87 or so.  The behavior I was expecting was for the image returned to be what was inside of the -0 image, the 350x350 crop, but if I'm able to specify manually, that would be sufficient.

**Comment by janko-m** [comment]
Not at the moment, this is the first time I hear that `-crop` can produce multiple files. But you can create a new `MiniMagick::Image`:

```rb
image.crop("350x350+0+0")
image = MiniMagick::Image.new(image.path.sub(/\.\w+$/, '-0\0'))
```

**Comment by daveroberts** [comment]
Thank you again for your reply.

I could get this working with a slight change to your code:

```ruby
image.crop("350x350")
image = MiniMagick::Image.new("#{image.path}-0")
image.write filepath
```

It appears that crop behaves by splitting the image file into many files depending on the size of the original image and the size of crop section.  In my case, the image ending with -0 was what I wanted, but I'm not sure this would be the case for all users.

It might be beneficial to have a short example in the minimagick readme similar to the following:

Crop splits the image into multiple files and removes the orginal image.  The following example throws an error

```ruby
image.crop("50x50")
image.write filepath # ERROR: File not found
```

You must specify which crop section you want to use:

```ruby
image.crop("50x50")
cropped_section_0 = MiniMagick::Image.new("#{image.path}-0")
cropped_section_0.write "/tmp/cropped_section_0.png"
cropped_section_1 = MiniMagick::Image.new("#{image.path}-1")
cropped_section_1.write "/tmp/cropped_section_1.png"
```

**Comment by janko-m** [comment]
@daveroberts I cannot reproduce this behaviour, and as far as I'm concerned that is a bug with ImageMagick, because it's unexpected behaviour, so it should be reported there.
