### ISSUE TITLE
Minimagic doesn't remove alpha channel

### ISSUE THREAD

**Issue by vladi160** [minimagick/minimagick#436]
I am using ImageMagic on Windows with Rails, Minimagic and CarrierWave.
If I run the command: convert -alpha remove logo.png logo2.jpg``, it works fine and removes alpha channel. But in the Rails code:  
`   version :thumb do
    process :process_image
   end

   def process_image
    manipulate! do |image|
      image.combine_options do |img|
        img.alpha 'remove'
        img.trim
        img.resize      "50x50"
      end
         image.format 'jpg'
      end
  end`

It doesn't work and even method `process_image`, doesn't return an image. Without this line `  img.alpha 'remove'`, it works fine. ImageMagic in the console works fine, too.
If I set debug to true: `MiniMagick.logger.level = Logger::DEBUG` I see that is executed this command in the console: 

> gm mogrify -alpha remove -trim -resize 50x50 -resize 50x50 C:/Users/user/AppData/Local/Temp/mini_magick20171125-2308-176bhdp.png

But it not save or upload the image (not process image). If I execute same command in the console, it works fine.
This is debug output from the console with `img.alpha 'remove'`:

> D, [2017-11-25T18:12:35.566448 #2308] DEBUG -- : [0.01s] gm identify C:/Users/MASTER~1/AppData/Local/Temp/mini_magick20171125-2308-tue49m.png
D, [2017-11-25T18:12:35.574469 #2308] DEBUG -- : [0.01s] gm mogrify -alpha remove -trim -resize 50x50 C:/Users/MASTER~1/AppData/Local/Temp/mini_magick20171125-2308-tue49m.png

This is debug output without ` img.alpha 'remove'`:

> D, [2017-11-25T18:13:40.902726 #2308] DEBUG -- : [0.01s] gm identify C:/Users/MASTER~1/AppData/Local/Temp/mini_magick20171125-2308-h0am37.png
D, [2017-11-25T18:13:40.916763 #2308] DEBUG -- : [0.01s] gm mogrify -trim -resize 50x50 C:/Users/MASTER~1/AppData/Local/Temp/mini_magick20171125-2308-h0am37.png
D, [2017-11-25T18:13:40.930812 #2308] DEBUG -- : [0.01s] gm convert C:/Users/MASTER~1/AppData/Local/Temp/mini_magick20171125-2308-h0am37.png[0]
C:/Users/MASTER~1/AppData/Local/Temp/mini_magick20171125-2308-iu5tm5.jpg
D, [2017-11-25T18:13:40.943840 #2308] DEBUG -- : [0.01s] gm identify C:/t/tmp/1511626420-2308-0015-7133/thumb/linkedin.png

**Comment by janko-m** [comment]
Notice that the debug output is showing `gm mogrify`, but you said you were trying out with `convert`. Perhaps there is a differences in behaviour here between ImageMagick and GraphicsMagick.

It wouldn't be possible to debug anything for me from CarrierWave code, if you think there is a bug in MIniMagick please post a self-contained example showing the problem using only MiniMagick. I will close this issue now as I don't think there is a bug in MiniMagick.
