### ISSUE TITLE
Mogrify cannot access https image urls

### ISSUE THREAD

**Issue by safdarzeeshan** [minimagick/minimagick#440]
Hi,
I am trying to use the montage and mogrify tool to create a collage of 4 images. I am able to do so with my image urls that are on a http endpoint but the ones that are on a secure https end point cannot be accessed. I get the this error: 

failed with error:
`gm mogrify: Unable to open file (//blog.apnic.net/wp-content/uploads/2014/11/https-1.jpg)`

This is my code which I am running in my rails console to test:

```
mogrify = MiniMagick::Tool::Mogrify.new
mogrify.resize("100x100")
mogrify.negate
mogrify << "https://blog.apnic.net/wp-content/uploads/2014/11/https-1.jpg"
mogrify << "test1.jpg"
mogrify.call
```
It works if i replace the image url with a non secure http endpoint. Am i missing a configuration option?

**Comment by janko-m** [comment]
@safdarzeeshan Are you getting the same error when using ImageMagick directly on the command-line?

**Comment by safdarzeeshan** [comment]
Hi @janko-m I tested this and you're right. I can't access the url from ImageMagick command line also. Any recommendations? I tried updating the ImageMagick policy.xml but it didn't change anything.

**Comment by janko-m** [comment]
I would recommend just downloading the image yourself using [Down](https://github.com/janko-m/down), pass the path to the downloaded image, and afterwards delete the file. 

I will close this as it’s not an issue with MiniMagick. You could raise that issue on the ImageMagick issue tracker.
