### ISSUE TITLE
Ability to select sequences on the input

### ISSUE THREAD

**Issue by siegy22** [minimagick/minimagick#441]
Hey there! Thanks for nice gem in the first place.

So this is more of a question, than a bug. 
Can I set the sequence like in this example:

```bash
$ convert -density 144 image.pdf[0] -resize 50% image.jpg
```

(the sequence would be the `[0]` after the input's name)

I tried:

```ruby
MiniMagick::Image.new("/some/document.pdf[0]")
```

but that didn't work out 🤔

**Comment by janko-m** [comment]
If you want to `convert`, you cannot use `MiniMagick::Image` since it uses `mogrify`, you should use the direct interface instead:

```rb
MiniMagick::Tool::Convert.new do |convert|
  convert.density(144)
  convert << "/some/document.pdf[0]"
  convert.resize("50%")
  convert << "output.jpg"
end
```

**Comment by siegy22** [comment]
Thanks you very much for the fast answer 👍
