### ISSUE TITLE
MiniMagick::Tool::Convert doesn't apply density command but command line does

### ISSUE THREAD

**Issue by abaird** [minimagick/minimagick#442]
When I use the following command line, I am able to convert a PDF into PNG images that have a dpi of 300
```
convert -verbose -density 300 inputfile.pdf -background white -alpha remove outputfile-%02d.png
```
However, when I use the following code (which I think should do the same thing), it appears that I get the default dpi of 72:
```
MiniMagick::Tool::Convert.new do |convert|
  convert << 'inputfile.pdf'
  convert.verbose
  convert.density(300)
  convert.background('white')
  convert.alpha('remove')
  convert << 'outputfile-%02d.png'
end
```
I've tried re-ordering the commands in the block above and they all had the same effect of getting a dpi of 72. Even when I take out everything except `convert.density(300)` I still get the same result. I've also tried switching the PDF that I'm using to see if it's dependent on that but it is not. You can get the PDF I'm using [here](http://www20.insurance.ca.gov/pdf/REG/200702.pdf).

I'm assuming that if I got the syntax right, then minimagick should be able to change the output density since I can also do it from the command line. Am I doing something wrong here?

**Comment by janko-m** [comment]
Hmm, the following should generate the original ImageMagick command:

```
MiniMagick::Tool::Convert.new do |convert|
  convert.verbose
  convert.density(300)
  convert << 'inputfile.pdf'
  convert.background('white')
  convert.alpha('remove')
  convert << 'outputfile-%02d.png'
end
```

Try putting `MiniMagick.logger.level = Logger::DEBUG` and seeing which ImageMagick command gets printed out. It should be the same one as your original ImageMagick command.

**Comment by abaird** [comment]
@janko-m - thanks for that, it worked! Thanks for the quick response.
```
irb(main):012:0> MiniMagick.logger.level = Logger::DEBUG
=> 0
irb(main):018:0> MiniMagick::Tool::Convert.new do |convert|
irb(main):019:1*   convert.density(300)
irb(main):020:1>   convert << 'inputfile.pdf'
irb(main):021:1>   convert.background('white')
irb(main):022:1>   convert.alpha('remove')
irb(main):023:1>   convert << 'outputfile-%02d.png'
irb(main):024:1> end
D, [2018-01-26T11:18:02.709893 #40369] DEBUG -- : [4.06s] convert -density 300 inputfile.pdf -background white -alpha remove outputfile-%02d.png
=> ""
```

**Comment by henrik** [comment]
I'm having a similar issue – this works fine:

```
MiniMagick::Tool::Convert.new do |convert|
  convert << "-density" << 300
  convert << "my.pdf"
  convert << "my.png"
end
```

But I would like to pass the PDF in as binary data and get binary data out – not file paths or URLs.

When I try

```
image = MiniMagick::Image.read(pdf_data)
image.density 300
image.format "png"
image.to_blob
```
then it doesn't get high resolution.

I've also tried various variations like

```
MiniMagick::Tool::Convert.new do |convert|
  convert << "-density" << 300
  convert.stdin
  convert << "-format" << "png"
  convert.stdout
  convert.call(stdin: image_content)
end
```

but I haven't managed to find anything that won't give me errors.

Would I have to write files to disk to make this work?

**Comment by henrik** [comment]
Ended up doing this:

```
begin
    input = Tempfile.new([ "input", ".pdf" ])
    input.binmode
    input.write pdf_data
    input.close

    png_data =
      MiniMagick::Tool::Convert.new do |convert|
        convert << "-density" << 300
        convert << input.path
        convert << "png:-"  # PNG to STDOUT
      end

    # …
ensure
    input.unlink
end
```

**Comment by aximuseng** [comment]
Same issue here - command line works find using convert and morgify.  I am using this in a Carrierwave uploader.  I am trying to preview the first page of PDFs.

```
    def convert_to_image
      MiniMagick::Tool::Convert.new do |convert|
         convert << "-density" << 150
         convert.flatten
         convert.resize '125%'
         convert << current_path
         convert.quality '100'
         convert << current_path
      end
    end

    version :preview, :if => :pdf? do
      def full_filename(for_file)
        super(for_file).chomp(File.extname(super(for_file))) + '.jpg'
      end
      process :convert_to_image
      process :convert => 'jpg'
    end
```

I added debug to the loglevel:

`magick convert -density 150 -flatten -resize 125% /path_to_temp_file/WEC-1268.pdf -quality 100 /path_to_temp_file/preview/WEC-1268.pdf`

I know this is being processed - if I change the resize the output changes.  If I remove flatten then the jpg output is all black from the alpha etc.  There is no value of density that effects the output.  The images are very low resolution i.e. 72 dpi level.

I then tested another version as per the Carrierwave docs: https://github.com/carrierwaveuploader/carrierwave/wiki/Efficiently-converting-image-formats#full-example

```
    version :test, :if => :pdf? do
      def filename
        'pdf_preview.jpg'
      end
      process :mogrify
    end

  private

  def mogrify
    manipulate! do |img|
      img.format("jpg") do |j|
        j.density 150
        j.flatten
        j.resize '250%'
        j.quality 100
      end
      img
    end
  end
```

and the logs:

```
D, [2020-06-29T17:43:37.789255 #81203] DEBUG -- : [0.27s] magick convert /path_to_temp_file/preview/WEC-1268.pdf -auto-orient /var/folders/zw/j_y1s0tj643gmv4hbh5817wr0000gr/T/image_processing20200629-81203-16k1qhk.jpg
D, [2020-06-29T17:43:38.459790 #81203] DEBUG -- : [0.66s] magick convert /var/folders/zw/j_y1s0tj643gmv4hbh5817wr0000gr/T/mini_magick20200629-81203-g1fhs3.pdf[0] -density 150 -resize 250% -quality 100 /var/folders/zw/j_y1s0tj643gmv4hbh5817wr0000gr/T/mini_magick20200629-81203-otpihs.jpg
D, [2020-06-29T17:43:38.484118 #81203] DEBUG -- : [0.02s] magick identify /path_to_temp_file/test/WEC-1268.pdf
```

same output issues (tried 250% to confirm) and everything EXCEPT density is applied.  Tried again from the CLI and if I skip the density the output looks the same as via Carrierwave.
