### ISSUE TITLE
How to run the 'magick' command?

### ISSUE THREAD

**Issue by 9mm** [minimagick/minimagick#445]
There are some small differences between `magick` and `convert` in ImageMagick 7.

Is it possible to use mini_magic to use the `magick` command line tool instead of `convert`?

**Comment by janko-m** [comment]
Not at the moment, but for now you can add the command yourself:

```rb
class MiniMagick::Tool::Magick < MiniMagick::Tool
  def initialize(*args)
    super("magick", *args)
  end
end
```

I will work on adding the `magick` command to MiniMagick soon.
