### ISSUE TITLE
Low conversion quality

### ISSUE THREAD

**Issue by ldestrooper** [minimagick/minimagick#450]
I'm using MiniMagick with CarrierWave, but it seems to really degrade the quality of the images.

Is there a way to change the compressions settings?

Help would be greatly appreciated, i searched online everywhere but can't get it fixed.

**Comment by janko-m** [comment]
Yes, the `-quality` option specifies the output compression. Now, if you want to ask me how to add that option to your CarrierWave resizers, that's a bit more difficult to answer. I *think* this should work, assuming you're on CarrierWave 1.1.0:

```rb
process resize_to_limit: [500, 500, combine_options: {quality: 100}]
```
