### ISSUE TITLE
if Synthesis 500 picture and out 500 picture is very slow

### ISSUE THREAD

**Issue by Thomastar** [minimagick/minimagick#451]
if Synthesis 500 picture and out 500 picture is very slow
Do you have Solution ？

**Comment by janko-m** [comment]
I have no idea what any of this means. What is Synthesis? What 500? What's the code you're using for processing? In any case, I'm 99% sure that the slowness comes from ImageMagick itself, not MiniMagick. MiniMagick just generates an ImageMagick command, that's it.
