### ISSUE TITLE
How to close file if no changes were made?

### ISSUE THREAD

**Issue by a-ta-ta** [minimagick/minimagick#452]
I can't find out if a file is opened with `image = MiniMagick::Image.new(path)` and no changes were made - is it gonna be closed automatically or there's a method to close it (something like `image.close`)?

I'm asking becase when we use `file = File.open(path)`
We have to `file.close` (or use it as block) when all the processing was made.

_Maybe I'm asking a stupid question (sorry if it is so!), nevertheless I want to put it off my soul. Thanks for your time!_

**Comment by janko-m** [comment]
No file is opened on `MiniMagick::Image.new(path)`. MiniMagick performs processing only using path strings, it doesn't open any files. In case `MiniMagick::Image.open` is used (and/or `MiniMagick::Image#format`), MiniMagick creates a Tempfile but immediately closes it, and then holds the reference to the closed Tempfile.

**Comment by a-ta-ta** [comment]
Thanks a lot!
