### ISSUE TITLE
Read Time out for Images

### ISSUE THREAD

**Issue by faizaankhan** [minimagick/minimagick#459]
```
Started GET "/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--76a9a0f4c61a6ae4fe69117a100098383ae22ba5/789452.jpg" for 127.0.0.1 at 2018-08-14 12:37:15 +0530
Completed 500 Internal Server Error in 127500ms (ActiveRecord: 5.9ms)



Net::ReadTimeout (Net::ReadTimeout):
```

when trying to open large sized images

**Comment by janko-m** [comment]
A `Net::ReadTimeout` exception means that at one point while reading the file response the read took longer than 60 minutes (Net::HTTP's default timeout). There are better ways to handle this problem, e.g. you could set a lower timeout and retry once.

However, this is out of scope for MiniMagick. MiniMagick only provides a simple interface for downloading from URLs using `open-uri`. If the caller needs something more involved, they should handle the downloading themselves. Ideally ActiveStorage should have its own download implementation, and just pass a path to the path on disk to MiniMagick. [Down](https://github.com/janko-m/down) might be useful here.
