### ISSUE TITLE
How do I rotate a png with transparency and keep the background transparent?

### ISSUE THREAD

**Issue by chopps** [minimagick/minimagick#462]
How do I rotate a png with transparency and keep the background transparent?
Rotating renders an opaque border outside of the original image when rotated and combined with another image. Is there a way to maintain transparency around rotated images?

Have tried background("transparent") background("alpha") background("rgba(0,0,0,0,)") to no avail

**Comment by janko-m** [comment]
The following should work:

```rb
image = MiniMagick::Image.open(path)
image.combine_options do |cmd|
  cmd.background "rgba(255,255,255,0.0)" # transparent
  cmd.rotate(degrees)
end
```

Note that this is an ImageMagick question, MiniMagick doesn't deal with this logic, it only provides a thin Ruby layer around ImageMagick's CLI interface.
