### ISSUE TITLE
Facing issue with MiniMagick::Error convert convert: Unrecognized option (-layers).

### ISSUE THREAD

**Issue by nikhilthombare** [minimagick/minimagick#468]
Here is my code and system information. The code is working on local environment but not on ubuntu server.  

full error desc: `convert uploads/tmp/1538654628-28339-2085/thumb_animated_clock.gif -coalesce -resize 100x100 -layers Optimize public/uploads/tmp/1538654628-28339-2085/thumb_animated_clock.gif` 

    def gif_safe_transform!
      MiniMagick::Tool::Convert.new do |image| # Calls imagemagick's "convert" command
        image << @file.path
        image.coalesce # Remove optimizations so each layer shows the full image.

        yield image

        image.layers "Optimize" # Re-optimize the image.
        image << @file.path
      end
    end

    def my_resize(size)
      if @file.content_type == "image/gif"
        gif_safe_transform! do |image|
          image.resize "#{size}x#{size}" # Perform any transformations here.
        end
      else
        # Process other filetypes if necessary.
      end
    end

```System info:
~/repo/xyz# convert --version
Version: ImageMagick 6.7.7-10 2018-07-10 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2012 ImageMagick Studio LLC
Features: OpenMP

**Comment by janko-m** [comment]
I appears that `-layers` option is not available on your version of ImageMagick. You can verify that by doing `convert -help | grep '-layers'`.

**Comment by nikhilthombare** [comment]
I checked and layers method found 

 
 #### $convert -help | grep layers
    -layers method       optimize, merge,  or compare image layers 

I comment layer part of the line but still gif image break. What is the soltuion for compress gif without breaking the layer. All code work properly on locally what i need to check with server side. 

//image.layers "Optimize" # Re-optimize the image.

**Comment by janko-m** [comment]
@nikhilthombare Have you checked this on the ImageMagick version on your *server*? It's not possible that "Unrecognized option (-layers)" error is thrown, but `-layers` option does exist (if that's the case you should raise an issue in the ImageMagick forums). MiniMagick is just forwarding exceptions from ImageMagick, it doesn't know which options exist and which don't.

**Comment by nikhilthombare** [comment]
@janko-m  Yes, I checked ImageMagick version on the server. Is there any other gem version dependencies so I need to check that too. Can you help me?

**Comment by janko-m** [comment]
Can you try executing the same ImageMagick command directly on your server with a dummy image?

```
$ convert uploads/tmp/1538654628-28339-2085/thumb_animated_clock.gif -coalesce -resize 100x100 -layers Optimize /path/to/dummy/image.jpg
```

Because I'm 100% sure this is not a MiniMagick issue, but that your installed ImageMagick version doesn't support the `-layers` option. So if you execute the above shell command on your server and you get the same error, then that rules out MiniMagick.

**Comment by nikhilthombare** [comment]
Here my o/p comes after fire the above command on server

```
convert /home/ubuntu/cartoon_birds_blue_flying_animation_clipart.gif -coalesce -resize 100x100 -layers Optimize /home/ubuntu/image123.gif

and image is created without any error. Where is the problem now

**Comment by janko-m** [comment]
@nikhilthombare Could you create an Ubuntu Docker container with `ImageMagick 6.7.7-10` installed in which you were able to reproduce this issue, and share the steps that I can run on my local computer? Because I have an ImageMagick version much newer than 6.7.7 installed (7.0.8), and there your MiniMagic command executes without errors, so I cannot reproduce your issue.

**Comment by nikhilthombare** [comment]
@janko-m I found issue and issue is related it taking old version (graphmagic not imagemagick ) from my server. 

Check version install in our system.

> convert --version (show me imagemagick)

below command shows, you currently used version by the system. 

> identify --version ( it show me graphmagick)

I uninstall graphmagick from system using following command and install imagemagick and it works for me.

http://installion.co.uk/ubuntu/vivid/universe/g/graphicsmagick/uninstall/index.html

Thanks for quick help... 👍

**Comment by janko-m** [comment]
Great, I'm glad it's resolved.
