### ISSUE TITLE
In the case of PDF, an error occurs because the dimension method raised ghostscript

### ISSUE THREAD

**Issue by ryosuke-endo** [minimagick/minimagick#472]
Hello.

By raising the version of ghostscript, it is no longer possible to create a PDF file that we were able to create.

## Software version

- ubuntu 16.04
- minimagick 4.9.2
- ghostscript 9.25
- ImageMagick 6.8.9-9

## Target file

[ng.pdf](https://github.com/minimagick/minimagick/files/2485539/ng.pdf)

## procedure

```ruby
irb(main):001:0> path = 'ng.pdf'
=> "ng.pdf"
irb(main):002:0> MiniMagick::Image.new(path).dimensions
Traceback (most recent call last):
       12: from bin/rails:9:in `<main>'
       11: from bin/rails:9:in `require'
       10: from /var/www/crevo/shared/bundle/ruby/2.5.0/gems/railties-5.0.7/lib/rails/commands.rb:18:in `<top (required)>'
        9: from /var/www/crevo/shared/bundle/ruby/2.5.0/gems/railties-5.0.7/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        8: from /var/www/crevo/shared/bundle/ruby/2.5.0/gems/railties-5.0.7/lib/rails/commands/commands_tasks.rb:78:in `console'
        7: from /var/www/crevo/shared/bundle/ruby/2.5.0/gems/railties-5.0.7/lib/rails/commands/console_helper.rb:9:in `start'
        6: from /var/www/crevo/shared/bundle/ruby/2.5.0/gems/railties-5.0.7/lib/rails/commands/console.rb:65:in `start'
        5: from (irb):2
        4: from /var/www/crevo/shared/bundle/ruby/2.5.0/gems/mini_magick-4.8.0/lib/mini_magick/image.rb:132:in `block in attribute'
        3: from /var/www/crevo/shared/bundle/ruby/2.5.0/gems/mini_magick-4.8.0/lib/mini_magick/image/info.rb:17:in `[]'
        2: from /var/www/crevo/shared/bundle/ruby/2.5.0/gems/mini_magick-4.8.0/lib/mini_magick/image/info.rb:43:in `cheap_info'
        1: from /var/www/crevo/shared/bundle/ruby/2.5.0/gems/mini_magick-4.8.0/lib/mini_magick/image/info.rb:62:in `rescue in cheap_info'
MiniMagick::Invalid (image data can't be read)
irb(main):003:0> image = MiniMagick::Image.new(path)
=> #<MiniMagick::Image:0x00005576795d4630 @path="tmp/ng.pdf", @tempfile=nil, @info=#<MiniMagick::Image::Info:0x00005576795d4608 @path="tmp/ng.pdf", @info={}>>
irb(main):004:0> image.pages
=> [#<MiniMagick::Image:0x00005576795dabe8 @path="tmp/ng.pdf[0]", @tempfile=nil, @info=#<MiniMagick::Image::Info:0x00005576795dabc0 @path="tmp/ng.pdf[0]", @info={}>>, #<MiniMagick::Image:0x00005576795dab20 @path="tmp/ng.pdf[1]", @tempfile=nil, @info=#<MiniMagick::Image::Info:0x00005576795daaf8 @path="tmp/ng.pdf[1]", @info={}>>, #<MiniMagick::Image:0x00005576795daa58 @path="tmp/ng.pdf[2]", @tempfile=nil, @info=#<MiniMagick::Image::Info:0x00005576795daa30 @path="tmp/ng.pdf[2]", @info={}>>, #<MiniMagick::Image:0x00005576795da990 @path="tmp/ng.pdf[3]", @tempfile=nil, @info=#<MiniMagick::Image::Info:0x00005576795da968 @path="tmp/ng.pdf[3]", @info={}>>, #<MiniMagick::Image:0x00005576795da8c8 @path="tmp/ng.pdf[4]", @tempfile=nil, @info=#<MiniMagick::Image::Info:0x00005576795da8a0 @path="tmp/ng.pdf[4]", @info={}>>, #<MiniMagick::Image:0x00005576795da800 @path="tmp/ng.pdf[5]", @tempfile=nil, @info=#<MiniMagick::Image::Info:0x00005576795da7d8 @path="tmp/ng.pdf[5]", @info={}>>, #<MiniMagick::Image:0x00005576795da738 @path="tmp/ng.pdf[6]", @tempfile=nil, @info=#<MiniMagick::Image::Info:0x00005576795da710 @path="tmp/ng.pdf[6]", @info={}>>, #<MiniMagick::Image:0x00005576795da670 @path="tmp/ng.pdf[7]", @tempfile=nil, @info=#<MiniMagick::Image::Info:0x00005576795da648 @path="tmp/ng.pdf[7]", @info={}>>, #<MiniMagick::Image:0x00005576795da5a8 @path="tmp/ng.pdf[8]", @tempfile=nil, @info=#<MiniMagick::Image::Info:0x00005576795da580 @path="tmp/ng.pdf[8]", @info={}>>, #<MiniMagick::Image:0x00005576795da4e0 @path="tmp/ng.pdf[9]", @tempfile=nil, @info=#<MiniMagick::Image::Info:0x00005576795da4b8 @path="tmp/ng.pdf[9]", @info={}>>, #<MiniMagick::Image:0x00005576795da418 @path="tmp/ng.pdf[10]", @tempfile=nil, @info=#<MiniMagick::Image::Info:0x00005576795da3f0 @path="tmp/ng.pdf[10]", @info={}>>]
irb(main):006:0> image.identify
=> "   **** Error reading a content stream. The page may be incomplete.\n               Output may be incorrect.\n   **** Error: Form stream has unbalanced q/Q operators (too many q's)\n               Output may be incorrect.\nError: Ignoring invalid annotation, output may be incorrect.\n   **** Error reading a content stream. The page may be incomplete.\n               Output may be incorrect.\n   **** Error: Form stream has unbalanced q/Q operators (too many q's)\n               Output may be incorrect.\nError: Ignoring invalid annotation, output may be incorrect.\ntmp/ng.pdf PBM 595x841 595x841+0+0 16-bit Bilevel Gray 63.1KB 0.000u 0:00.000"

```

## Description

It is a cause.

By raising the version of ghostscript, the contents outputted in the error log will be returned as the result of standard output.

https://github.com/minimagick/minimagick/blob/master/lib/mini_magick/shell.rb#L14

|  |stdout  |stderr  | status|
|---|---|---|---|
|ghostscript(9.18)  |"PBM 595 841 63139B"  |"   **** Error reading a content stream. The page may be incomplete.\n   **** Warning: Form stream has unbalanced q/Q operators (too many q's)\n   **** Error reading a content stream. The page may be incomplete.\n   **** Warning: Form stream has unbalanced q/Q operators (too many q's)\n\n   **** This file had errors that were repaired or ignored.\n   **** The file was produced by: \n   **** >>>> Adobe PDF library 7.77 <<<<\n   **** Please notify the author of the software that produced this\n   **** file that it does not conform to Adobe's published PDF\n   **** specification.\n\n"  |0|
|ghostscript(9.25)  |   **** Error reading a content stream. The page may be incomplete.\n               Output may be incorrect.\n   **** Error: Form stream has unbalanced q/Q operators (too many q's)\n               Output may be incorrect.\nError: Ignoring invalid annotation, output may be incorrect.\n   **** Error reading a content stream. The page may be incomplete.\n               Output may be incorrect.\n   **** Error: Form stream has unbalanced q/Q operators (too many q's)\n               Output may be incorrect.\nError: Ignoring invalid annotation, output may be incorrect.\nPBM 595 841 63139B"  |""  |0|

As a result, parsing on minimagick side fails and it is an error.

https://github.com/minimagick/minimagick/blob/master/lib/mini_magick/image/info.rb#L45

```ruby
[3] pry(#<MiniMagick::Image::Info>)> self["%m %w %h %b"].split(" ")
=> ["****",
 "Error",
 "reading",
 "a",
 "content",
 "stream.",
 "The",
 "page",
 "may",
 "be",
...
```

## Approach

approach

- Look at the version of ghostscript and change parse processing
→ Originally it is a problem of ghostscript
- Expect ghostscript to be modified
→ It will be a problem that software can not be used until then

I think whether the former is good.

To be honest, since the output of ghostscript has been changed, it is not easy to deal with it here

**Comment by janko-m** [comment]
Thank you for the detailed error report, it helps so much to have all the information so clearly presented. It's a shame that GhostScript move its errors from the appropriate channel (stderr) to the inappropriate channel (stdout). 

It sounds to me like this issue can be worked around by fetching only the last line of the output, and printing the potential warning to stderr. So we could change

```rb
self["%m %w %h %b"].split(" ")
```

to

```rb
output = self["%m %w %h %b"].split("\n")
result = output.pop

$stderr.puts(output.join("\n")) if output.any?

result.split(" ")
```

What do you think?

**Comment by ryosuke-endo** [comment]
No problem at all.

I was impressed because it was an approach I could not think of at all.

It would be great if you could make changes.

**Comment by phoet** [comment]
some of my tests on CI just started failing and i was wondering if this could be related. 

```
D, [2018-11-28T09:55:16.319649 #17344] DEBUG -- : [0.12s] identify /tmp/mini_magick20181128-17344-5gzeqg.pdf
D, [2018-11-28T09:55:16.408434 #17344] DEBUG -- : [0.09s] convert /tmp/mini_magick20181128-17344-5gzeqg.pdf[0] -density 300 -quality 99 /tmp/mini_magick20181128-17344-1pdfd3p.png
E
Error:
Broker::AddressChangesControllerTest#test_address_change_succeeds_with_selected_contract:
CarrierWave::ProcessingError: Verarbeitung mit MiniMagick fehlgeschlagen, vielleicht ist es kein Bild? Original Fehler: `convert /tmp/mini_magick20181128-17344-5gzeqg.pdf[0] -density 300 -quality 99 /tmp/mini_magick20181128-17344-1pdfd3p.png` failed with error:
convert-im6.q16: FailedToExecuteCommand `'gs' -sstdout=%stderr -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 '-sDEVICE=pngalpha' -dTextAlphaBits=4 -dGraphicsAlphaBits=4 '-r72x72' -dFirstPage=1 -dLastPage=1 '-sOutputFile=/tmp/magick-17982AIpQLTg0smlm%d' '-f/tmp/magick-17982kuxOtOCPQBSb' '-f/tmp/magick-17982EUZRukgPnXp1'' (-1) @ error/delegate.c/ExternalDelegateCommand/462.
convert-im6.q16: no images defined `/tmp/mini_magick20181128-17344-1pdfd3p.png' @ error/convert.c/ConvertImageCommand/3258.
```

```
circleci@20ba85244752:~/repo$ ghostscript --version
9.26
circleci@20ba85244752:~/repo$ convert --version
Version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP
Delegates (built-in): bzlib djvu fftw fontconfig freetype jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png tiff wmf x xml zlib
```

this is with latest `circleci/ruby:2.5.3-stretch-node-browsers` docker image

**Comment by neilbartley** [comment]
@phoet yeah, looks like 9.26 [is the only version available](https://packages.debian.org/search?keywords=ghostscript&searchon=names&suite=stretch&section=all) on Debian Stretch now.

@janko-m happy to put a PR together based on your response to @ryosuke-endo but I'll be very much copy/pasting what you suggest.

**Comment by berislavbabic** [comment]
The problem with processing PDF's is twofold. One issue is the imagemagick update, that disabled PDF rendering inside the `/etc/ImageMagick-6/policy.xml` file. Be sure to check that one as well. Alongside that, `ghostscript` 9.2.6 fails with on CircleCI, and on the latest OSX, while 9.2.5 works like a charm.

**Comment by phoet** [comment]
@berislavbabic we already learned about `policy.xml` the hard way 😢

**Comment by phoet** [comment]
as of recent events we actually have a status-check that generates processes pdfs through minimagick to add visibility

**Comment by mrsellars** [comment]
We have the same issue that @phoet describe. Looks like that the gs9.26 introduced a incompatibility with the ImageMagick delegates (delegates.xml). Everything works fine with gs9.25.

Versions:

GPL Ghostscript 9.26
ImageMagick 7.0.8-14

**Comment by janko** [comment]
It seems this should be fixed in https://github.com/minimagick/minimagick/pull/522.
