### ISSUE TITLE
Odd error on AWS lambda

### ISSUE THREAD

**Issue by Jakanapes** [minimagick/minimagick#477]
Trying to create an AWS lambda to resize images pulled from a URL.

I copied some of the process from here.

```ruby
require 'base64'
require "mini_magick"

def handle_request(event:, context:)
  url = "https://cdn.simpli.fi/missing_feed_image.png"
  base_64 = event["queryStringParameters"]["image_path"]

  url = Base64.decode64(base_64)
  @img = MiniMagick::Image.open(url)
  @img.resize("400x400")

  { isBase64Encoded: true,
    statusCode: 200,
    headers: { 'Content-Type' => "*/*",
               'Cache-Control' => 'max-age=2592000' }, # 30 day
    body: Base64.encode64(@img.to_blob) }
end
```

This is a bit stripped down, but the gist is there.

I'm getting the following errors and having trouble tracking down root cause.

```
wrong number of arguments (given 1, expected 0)
/var/task/handler.rb:32:in `resize'
/var/task/vendor/bundle/ruby/2.5.0/gems/mini_magick-4.9.3/lib/mini_magick/image.rb:456:in `block in method_missing'
/var/task/vendor/bundle/ruby/2.5.0/gems/mini_magick-4.9.3/lib/mini_magick/image.rb:565:in `block in mogrify'
/var/task/vendor/bundle/ruby/2.5.0/gems/mini_magick-4.9.3/lib/mini_magick/tool.rb:37:in `new'
/var/task/vendor/bundle/ruby/2.5.0/gems/mini_magick-4.9.3/lib/mini_magick/image.rb:564:in `mogrify'
/var/task/vendor/bundle/ruby/2.5.0/gems/mini_magick-4.9.3/lib/mini_magick/image.rb:455:in `method_missing'
/var/task/handler.rb:16:in `handle_request'
```

Using version 4.9.3

I imagine it's something lambda related, but has anyone come across this error?

**Comment by janko** [comment]
My guess from the stack trace is that you have a `#resize` global method defined in your `handler.rb`. Defining global methods is dangerous, because they get added to each Ruby object. In this case it appears that `MiniMagick::Image#resize` ends up calling your `#resize` method in the end.

**Comment by Jakanapes** [comment]
OMG.  I'm an idiot.  I've been digging into the gem source and driving myself crazy when it was so simple.  

Thanks!
