### ISSUE TITLE
How to replace a color in the image?

### ISSUE THREAD

**Issue by laoyouzi** [minimagick/minimagick#481]
Hi, I want to replace a certain color in the picture, what should I do?

**Comment by laoyouzi** [comment]
Hi, I want to replace a certain color in the picture, what should I do?

**Comment by janko** [comment]
You should first find out how to achieve this with _ImageMagick_ on the command-line (i.e. the shell command), then you can generate that ImageMagick command with MiniMagick. MiniMagick is basically just a thin wrapper around generating ImageMagick commands, it doesn't really contain any extra logic.

**Comment by laoyouzi** [comment]
> You should first find out how to achieve this with _ImageMagick_ on the command-line (i.e. the shell command), then you can generate that ImageMagick command with MiniMagick. MiniMagick is basically just a thin wrapper around generating ImageMagick commands, it doesn't really contain any extra logic.

Thank you very much for your answer.
