### ISSUE TITLE
Latest version hangs on CI

### ISSUE THREAD

**Issue by revolter** [minimagick/minimagick#488]
References:

1. https://travis-ci.community/t/build-times-out-with-no-apparent-reason/5083/4
2. https://github.com/AFNetworking/AFNetworking/pull/4439

The second one is related to fastlane, which added `mini_magick` as a dependency after `2.109.1`, which also [failed the build](https://travis-ci.org/AFNetworking/AFNetworking/jobs/590405728), hence why he [pinned that version](https://github.com/AFNetworking/AFNetworking/pull/4439/files#diff-354f30a63fb0907d4ad57269548329e3R40).

**Comment by janko** [comment]
I don't believe this is related to MiniMagick, as its build is passing – https://travis-ci.org/minimagick/minimagick

**Comment by revolter** [comment]
Maybe not directly, but for my code, it started failing after simply [replacing](https://github.com/revolter/fastlane-plugin-icon_versioning/commit/144b25734307ca67339da498a79806255bd89089#diff-273091a9b01dbb6a3d1275bbf6b2ffcfR22) `spec.add_dependency('mini_magick', '~> 4.5.1')` with `spec.add_dependency('mini_magick', '>= 4.5.1')`, and nothing more. That's why I assumed it's a `mini_magick` issue.

And this is my entire [`.travis.yml` file](https://github.com/revolter/fastlane-plugin-icon_versioning/blob/8fbe0650ca39d7d78fd790fc18c6bc69f07e5f19/.travis.yml):

```yaml
# os: osx # enable this if you need macOS support
language: ruby
rvm:
  - 2.2.4
```

Maybe it's related to the Ruby version? I think that `AFNetworking` is [using `2.0.0`](https://travis-ci.org/AFNetworking/AFNetworking/jobs/590609066#L58).

**Comment by janko** [comment]
Yeah, it could be that some change in MiniMagick caused hanging, combined with some specific MiniMagick usage. However, I can only help with fixing specific issues, someone else will need to triage where the hanging is happening.

**Comment by tjanela** [comment]
@janko @revolter does this happen if the os is **not** osx?
If it does happen on other operating systems then one could locally run travis on a docker instance and see what's up.
If it only happens on osx then Apple's licensing prevents travis from distributing osx docker images so another strategy needs to be devised.
Regarding running travis on docker, locally, I came across this while investigating the issue:
https://stackoverflow.com/a/49019950/854959
Maybe it helps.

**Comment by tjanela** [comment]
Hey @janko and @revolter, since **it seems** that we were able to reproduce this issue on AFNetworking let me add that this was happening on older osx versions, namely osx10.11 as indicated here (look at the jobs that failed):
https://travis-ci.org/AFNetworking/AFNetworking/jobs/590405728

Since this hang was related with a particular fastlane version maybe the changes between fastlane's versions might help shedding some light on what's happening (I'm just not sure if the issue still manifests itself on 2.110.0, haven't had time to test):
https://github.com/fastlane/fastlane/compare/2.109.1...2.110.0

**Comment by appwebtech** [comment]
They should add dependencies and re- run again the code.

Cheers,

Joseph

**Comment by appwebtech** [comment]
Never mind about my previous e-mail, I was writing to someone else. ✌

**Comment by revolter** [comment]
I don't think it's related to macOS at all, since I'm [not using it](https://github.com/revolter/fastlane-plugin-icon_versioning/blob/master/.travis.yml).

**Comment by tjanela** [comment]
Interesting, @revolter. A longshot but could a particular ruby/rvm version be causing this behavior?

**Comment by revolter** [comment]
I think that it was a Travis _(update?)_ issue. [This](https://github.com/revolter/fastlane-plugin-icon_versioning/commit/74aff11e962dd005ca426d00e89f9415125517c5) fixed it.

**Comment by revolter** [comment]
Though I don't know how it works for fastlane without this. Because it was failing without ghostscript on Circle CI too. Which makes me think that it was actually **not** a Travis issue.
