### ISSUE TITLE
Fail to open(MiniMagick::Image.open) a local image resource when its file name not URI friendly

### ISSUE THREAD

**Issue by LittleTwoCheng** [minimagick/minimagick#492]
**GIVEN**
I have a local image resource named like this `orange is good.jpg`

**WHEN**
I try to access this image resource by calling `MiniMagick::Image.open("path/to/orange is good.jpg")` or with escaping `MiniMagick::Image.open("path/to/orange\ is\ good.jpg")`

**EXPECTED**
This can be discussed, but I'd expect it should just work as expected.

**CURRENTLY**
It raise an error with message like this:
`URI::InvalidURIError: bad URI(is not URI?): path/to/orange is good.jpeg`

**Comment by LittleTwoCheng** [comment]
**MY GUESS**
here:
https://github.com/minimagick/minimagick/blob/4cd5081e58810d3394d27a67219e8e4e0445d851/lib/mini_magick/image.rb#L85
it directly take advantage of URI constructor to help parsing the inputted `path_or_url`, which create an expectation that inputted `path_or_url` must be URI friendly(like no spacing?).

**Comment by janko** [comment]
Are you using the latest MiniMagick version?

**Comment by LittleTwoCheng** [comment]
Oh, my fault. We use version 4.9.4 suggested by `dependabot`.
It look like the implementation has changed after this version. Will check again after further update.

Close and sorry about that🙌🏻
