### ISSUE TITLE
Can't find a way to user connected-components

### ISSUE THREAD

**Issue by DrLuthor** [minimagick/minimagick#493]
Hi,

I'm trying to identify areas in a picture using conected-components. 
The code doesn't crash but I can't find a way to print the results.

```rb
MiniMagick.configure do |config|
  config.logger.level = Logger::DEBUG
end

picture = MiniMagick::Image.open(picture_path)

picture.combine_options do |processing|
  processing.define 'connected-components:verbose=true'
  processing.define 'connected-components:area-threshold=100'
  processing.connected_components 8
  processing.auto_level
end
```

The log:

`D, [2019-12-12T19:55:55.982887 #10192] DEBUG -- : [0.24s] mogrify -define connected-components:verbose=true -define connected-components:area-threshold=100 -connected-components 8 -auto-level /var/folders/6x/920d7m217hxgq9pz_nyhy03w0001gg/T/mini_magick20191212-10192-1rwgeer.png`

Do you have any idea how to retrieve the identified objects?

**Comment by janko** [comment]
The output is printed on stdout, so you want to build the command using `MiniMagick::Tool::Magick` directly (`Magick.new` will return the standard output string from the shell command):

```rb
output = MiniMagick::Tool::Mogrify.new do |magick|
  magick.define "connected-components:verbose=true"
  magick.define "connected-components:area-threshold=100"
  magick.connected_components 8
  magick.auto_level
  magick << "/path/to/image.png"
end

puts output
```

Example output:

```
Objects (id: bounding-box centroid area mean-color):
  0: 256x171+0+0 119.3,80.7 33148 srgb(0,0,0)
  1: 120x135+104+18 159.5,106.5 8690 srgb(85,85,85)
  2: 50x36+129+44 154.2,63.4 1529 srgb(170,170,170)
  3: 21x23+0+45 8.8,55.9 409 srgb(255,255,255)
```
