### ISSUE TITLE
Compatibility with Ruby 2.7?

### ISSUE THREAD

**Issue by pedrofurtado** [minimagick/minimagick#494]
I am getting the warning using this gem with ruby 2.7:

```bash
/usr/local/rvm/gems/ruby-2.7.0@myapp/gems/mini_magick-4.9.5/lib/mini_magick/image.rb:105: warning: Using the last argument as keyword parameters is deprecated
```

**Comment by sqbell** [comment]
My attempt at fixing it looks like so: https://github.com/minimagick/minimagick/compare/master...sqbell:ruby-2.7-deprecation-warnings. This however will not work on ruby 1.9.3 (because of the double splat operator, which was introduced later).

**Comment by janko** [comment]
This was fixed in https://github.com/minimagick/minimagick/pull/496.
