### ISSUE TITLE
validate_on_write is not used anymore

### ISSUE THREAD

**Issue by krzysiek1507** [minimagick/minimagick#497]
It looks like `validate_on_write` has been removed with this commit (back in 2014) but it still is in readme. https://github.com/minimagick/minimagick/commit/b2aa5e300b46fb888729251318fda1f3f90fa341#diff-da493690b64035c0e30726e3e29b5b93

**Comment by janko** [comment]
Thanks for reporting. I wish now I included the rationale of that change, and that I didn’t use the word “refactor” to describe it.
