### ISSUE TITLE
feature: list formats

### ISSUE THREAD

**Issue by D3MZ** [minimagick/minimagick#498]
This would be helpful so we can only work on files that the system can handle.

In my use case, `.gif` are typically replaced by `.webm` and `.mp4` despite being tagged as "images". Image Magick today works with `.gif` but not with the movie formats, which may be a future update. 

Right now you can get the available format list via this command:
`$ identify -list format`

**Comment by janko** [comment]
Yeah, I would like to add this feature, but `identify -list format` is the only way I know how to retrieve it, and the output is really not in an easy-to-parse format.

For now the only way is to retrieve the output and parse it yourself:

```rb
output = MiniMagick::Tool::Identify.new do |cmd|
  cmd.list("format")
end

output #=> "..."
```
