### ISSUE TITLE
`immutable_image.rb` included in 4.10.x gem cut

### ISSUE THREAD

**Issue by abrom** [minimagick/minimagick#500]
Not sure if this was intentional, but I noticed that file `lib/mini_magick/immutable_image.rb` has been included in the 4.10.x gem cut, despite not being in the git repo?

See https://diff.coditsu.io/gems/mini_magick/4.9.5/4.10.1#d2h-294600

I don't see it being loaded anywhere so suggests it may have been a mistake? Especially given it appears to be monkey patching the `Image` class..

**Comment by janko** [comment]
Thanks for reporting, this was a local experiment that was accidentally released. It shouldn't affect any code, as that file is not required anywhere. It will get removed in the next version.

**Comment by abrom** [comment]
:+1: yep thought as much, all good
