### ISSUE TITLE
MiniMagick gives exception for image having .webp extension

### ISSUE THREAD

**Issue by IamSantosh** [minimagick/minimagick#502]
MiniMagick works perfectly for image URL having .jpg extension but it gives exception on image URL having .webp extension. 

**Here's the code I'm using:**
object_image = "https://images.jumpseller.com/store/outlet-del-profumo/4523375/MISS.webp?0"
frame = MiniMagick::Image.open object_image

**and this is the error which I'm getting:**
MiniMagick::Invalid: `identify /tmp/mini_magick20200217-11229-1sm5v1j.webp` failed with error:
identify-im6.q16: delegate failed `'dwebp' -pam '%i' -o '%o'' @ error/delegate.c/InvokeDelegate/1919.
identify-im6.q16: unable to open file `/tmp/magick-11274LBWXiPU4f7y5': No such file or directory @ error/constitute.c/ReadImage/544.

**on using .jpg image, this works:**
object_image = "https://images.jumpseller.com/store/outlet-del-profumo/4523327/chloe-2.jpg?0"
frame = MiniMagick::Image.open object_image

Please help me out or tell me what can I do for handling .webp image URL.

**Comment by janko** [comment]
I don't get this error, for me it works just fine:

```rb
remote_url = "https://images.jumpseller.com/store/outlet-del-profumo/4523375/MISS.webp?0"
image = MiniMagick::Image.open(remote_url)
system "identify #{image.path}"
```
```
/var/folders/k7/6zx6dx6x7ys3rv3srh0nyfj00000gn/T/mini_magick20200217-87145-1hnmxux.webp WEBP 500x500 500x500+0+0 8-bit sRGB 47114B 0.010u 0:00.008
```

**Comment by IamSantosh** [comment]
> I don't get this error, for me it works just fine:
> 
> ```ruby
> remote_url = "https://images.jumpseller.com/store/outlet-del-profumo/4523375/MISS.webp?0"
> image = MiniMagick::Image.open(remote_url)
> system "identify #{image.path}"
> ```
> 
> ```
> /var/folders/k7/6zx6dx6x7ys3rv3srh0nyfj00000gn/T/mini_magick20200217-87145-1hnmxux.webp WEBP 500x500 500x500+0+0 8-bit sRGB 47114B 0.010u 0:00.008
> ```

I'm using MiniMagick version 4.9.5 on my project and its happening for me every time.

**Comment by janko** [comment]
Upgrade to latest MiniMagick and ImageMagick and let me know if the error still happens. 

Otherwise I don't know what could be the difference between our configurations.

**Comment by IamSantosh** [comment]
I just run this command "sudo apt-get install webp" in my system and it starts working. Thankyou @janko  for such quick response.
