### ISSUE TITLE
Image Tile does not work

### ISSUE THREAD

**Issue by activestylus** [minimagick/minimagick#503]
In reference to #194

I am getting an error `unable to open image 'true': No such file or directory `

```ruby
file_url = "/some/dir/image.jpg"
background = ::MiniMagick::Image.open(file_url)
img.composite(background) do |c|
   c.compose "overlay"
   c.tile = true
end
```

It seems the new API requires a file path rather than a boolean value. But when I try this

```ruby
img.composite(background) do |c|
  c.compose "overlay"
  c.tile file_url
end
```
All I get is a small, flattened copy of the watermark and no image.

I am simply trying to add a repeat pattern of logos on an image, like stock sites do. Any pointers would be appreciated.

**Comment by janko** [comment]
What is that ImageMagick command generated by this MiniMagick code (you can turn on logging to see)? Is the generated ImageMagick command different than what you expected? I'd recommend finding the correct ImageMagick command you want to generate first.
