### ISSUE TITLE
failed with error: identify-im6.q16: width or height exceeds limit

### ISSUE THREAD

**Issue by johan-smits** [minimagick/minimagick#504]
How are images with a really large size (19190x10790) handeled? Or how to catch this gracefully?

```
A MiniMagick::Error occurred in background at 2020-03-04 01:11:28 UTC :

  `identify -format %[orientation] /tmp/ActiveStorage-81766-20200304-12-1a8fnr4[0]` failed with error:
identify-im6.q16: width or height exceeds limit `/tmp/ActiveStorage-81766-20200304-12-1a8fnr4' @ error/cache.c/OpenPixelCache/3912.

  /var/app/current/vendor/bundle/ruby/2.7.0/gems/mini_magick-4.10.1/lib/mini_magick/shell.rb:17:in `run'
```

**Comment by janko** [comment]
They're not handled within MiniMagick. I thought ImageMagick is able to determine dimensions fast for any size. I'm not sure we can do much about it on MiniMagick side other than parsing error message which I want to avoid.

**Comment by johan-smits** [comment]
So this would be a ImageMagick issue because Minimagic is just a wrapper for it?
