### ISSUE TITLE
Is it possible to set the pixel ? I have an array of array of pixels and want to set the pixels in blank image. What can i do?

### ISSUE THREAD

**Issue by rabinpoudyal** [minimagick/minimagick#510]
https://github.com/minimagick/minimagick/blob/1b3fe5928aeb92a4ddade9f89db4ba610ebbef82/lib/mini_magick/image.rb#L361

**Comment by rabinpoudyal** [comment]
This is the array of pixels i am talking about
`[[[255, 0, 135], [255, 0, 130], [255, 0, 115], [255, 0, 86], [255, 91, 0], [0, 117, 0], [0, 120, 0], [0, 98, 0], [0, 12, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [255, 0, 48], [255, 0, 99], [255, 0, 120]], [[255, 0, 132], [255, 0, 128], [255, 0, 115], [255, 24, 90], [255, 95, 32], [0, 118, 0], [0, 119, 0], [0, 98, 0], [0, 22, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [255, 0, 42], [255, 0, 98], [255, 0, 121]], [[255, 0, 124], [255, 0, 122], [255, 0, 114], [255, 75, 99], [255, 105, 70], [0, 119, 0], [0, 117, 0], [0, 97, 0], [0, 39, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [255, 0, 15], [255, 0, 96], [255, 0, 123]], [[255, 88, 111], [255, 92, 112], [255, 101, 113], [255, 111, 111], [255, 119, 102], [0, 120, 76], [0, 113, 0], [0, 94, 0], [0, 56, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [255, 0, 0], [255, 0, 94], [255, 0, 126]], [[255, 155, 90], [255, 154, 96], [255, 149, 111], [255, 142, 124], [255, 132, 128], [0, 120, 119], [0, 106, 89], [0, 90, 0], [0, 70, 0], [0, 37, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [255, 0, 0], [255, 0, 93], [255, 0, 131]], [[255, 200, 56], [255, 196, 75], [255, 184, 107], [255, 166, 134], [255, 143, 150], [0, 119, 150], [0, 97, 131], [0, 85, 82], [0, 82, 0], [0, 83, 0], [0, 81, 0], [0, 69, 0], [0, 32, 0], [255, 0, 0], [255, 0, 93], [255, 0, 136]], [[255, 232, 0], [255, 227, 39], [255, 210, 102], [255, 184, 142], [255, 151, 166], [0, 114, 173], [0, 84, 160], [0, 76, 123], [0, 89, 0], [0, 108, 0], [0, 119, 0], [0, 118, 0], [0, 103, 0], [255, 68, 0], [255, 0, 97], [255, 0, 141]], [[255, 255, 0], [255, 248, 0], [255, 228, 94], [255, 196, 147], [255, 154, 177], [0, 107, 189], [0, 65, 181], [0, 62, 151], [0, 94, 88], [0, 123, 0], [0, 141, 0], [0, 144, 0], [0, 131, 0], [255, 98, 0], [255, 4, 104], [255, 0, 146]], [[255, 255, 0], [255, 255, 0], [255, 239, 84], [255, 202, 147], [255, 153, 183], [0, 93, 199], [0, 25, 196], [0, 40, 172], [0, 95, 124], [0, 133, 0], [0, 154, 0], [0, 157, 0], [0, 142, 0], [255, 103, 0], [255, 0, 113], [255, 0, 151]], [[0, 255, 0], [0, 255, 0], [0, 243, 69], [0, 202, 144], [0, 146, 184], [255, 72, 204], [255, 0, 205], [255, 0, 187], [255, 92, 151], [255, 137, 92], [255, 159, 0], [255, 162, 0], [255, 141, 0], [0, 86, 65], [0, 0, 125], [0, 0, 155]], [[0, 255, 0], [0, 255, 0], [0, 240, 48], [0, 196, 137], [0, 134, 180], [255, 25, 204], [255, 0, 209], [255, 0, 198], [255, 84, 173], [255, 136, 135], [255, 159, 90], [255, 157, 50], [255, 128, 63], [0, 13, 103], [0, 0, 137], [0, 0, 159]], [[0, 255, 0], [0, 255, 0], [0, 233, 0], [0, 186, 125], [0, 116, 173], [255, 0, 199], [255, 0, 209], [255, 0, 206], [255, 73, 190], [255, 130, 167], [255, 152, 141], [255, 146, 123], [255, 100, 120], [0, 0, 132], [0, 0, 149], [0, 0, 162]], [[0, 255, 0], [0, 251, 0], [0, 221, 0], [0, 171, 111], [0, 90, 161], [255, 0, 191], [255, 0, 207], [255, 0, 211], [255, 57, 205], [255, 122, 192], [255, 142, 176], [255, 128, 163], [255, 39, 156], [0, 0, 156], [0, 0, 160], [0, 0, 165]], [[0, 248, 0], [0, 238, 0], [0, 207, 0], [0, 154, 93], [0, 51, 148], [255, 0, 182], [255, 0, 203], [255, 0, 214], [255, 32, 215], [255, 112, 211], [255, 129, 202], [255, 103, 191], [255, 0, 182], [0, 0, 174], [0, 0, 169], [0, 0, 167]], [[0, 237, 0], [0, 226, 0], [0, 194, 0], [0, 137, 75], [0, 0, 136], [255, 0, 174], [255, 0, 199], [255, 0, 215], [255, 0, 223], [255, 102, 224], [255, 116, 220], [255, 74, 211], [255, 0, 200], [0, 0, 187], [0, 0, 176], [0, 0, 169]], [[0, 228, 0], [0, 217, 0], [0, 184, 0], [0, 123, 59], [0, 0, 127], [255, 0, 167], [255, 0, 196], [255, 0, 216], [255, 0, 228], [255, 94, 232], [255, 105, 230], [255, 40, 222], [255, 0, 210], [0, 0, 195], [0, 0, 181], [0, 0, 169]]]`

**Comment by janko** [comment]
There is a method `MiniMagick::Image.import_pixels` that might help.
