### ISSUE TITLE
How to get width of text

### ISSUE THREAD

**Issue by mystycs** [minimagick/minimagick#512]
I am opening an image and adding text to it. How can i get the width of the text that I added? 

So basically how do I call the metric on minimagick below to get the width of the generated `9:19 PM` ? 

        image = MiniMagick::Image.open("app/assets/images/small.png")

        text = "9:19PM"
        image.combine_options do |c|
          c.font "Arial"
          c.pointsize 17
          c.gravity 'Northwest'
          c.draw "text 7,5 #{text}"
          c.fill("#FFFFFF")
        end

In PHP you were able to just call something like this to get the width. `$metrics = $image->queryFontMetrics ($image, $text);`.  How do I do the same ehre?

**Comment by mystycs** [comment]
I found that rmagick has this functionality. Does minimagick carry it?

**Comment by janko** [comment]
If there is an ImageMagick command that can do it, then it should be possible to translate it into MiniMagick as well.
