### ISSUE TITLE
Density option not being applied

### ISSUE THREAD

**Issue by aximuseng** [minimagick/minimagick#517]
This is the same issue in #442.  The density option is not applied but works fine via the CLI.

Command line works find using convert and morgify.  I am using this in a Carrierwave uploader.  I am trying to preview the first page of PDFs.

```
    def convert_to_image
      MiniMagick::Tool::Convert.new do |convert|
         convert << "-density" << 150
         convert.flatten
         convert.resize '125%'
         convert << current_path
         convert.quality '100'
         convert << current_path
      end
    end

    version :preview, :if => :pdf? do
      def full_filename(for_file)
        super(for_file).chomp(File.extname(super(for_file))) + '.jpg'
      end
      process :convert_to_image
      process :convert => 'jpg'
    end
```

I added debug to the loglevel:

`magick convert -density 150 -flatten -resize 125% /path_to_temp_file/WEC-1268.pdf -quality 100 /path_to_temp_file/preview/WEC-1268.pdf`

I know this is being processed - if I change the resize the output changes.  If I remove flatten then the jpg output is all black from the alpha etc.  There is no value of density that effects the output.  The images are very low resolution i.e. 72 dpi level.

I then tested another version as per the Carrierwave docs: https://github.com/carrierwaveuploader/carrierwave/wiki/Efficiently-converting-image-formats#full-example

```
    version :test, :if => :pdf? do
      def filename
        'pdf_preview.jpg'
      end
      process :mogrify
    end

  private

  def mogrify
    manipulate! do |img|
      img.format("jpg") do |j|
        j.density 150
        j.flatten
        j.resize '250%'
        j.quality 100
      end
      img
    end
  end
```

and the logs:

```
D, [2020-06-29T17:43:37.789255 #81203] DEBUG -- : [0.27s] magick convert /path_to_temp_file/preview/WEC-1268.pdf -auto-orient /var/folders/zw/j_y1s0tj643gmv4hbh5817wr0000gr/T/image_processing20200629-81203-16k1qhk.jpg
D, [2020-06-29T17:43:38.459790 #81203] DEBUG -- : [0.66s] magick convert /var/folders/zw/j_y1s0tj643gmv4hbh5817wr0000gr/T/mini_magick20200629-81203-g1fhs3.pdf[0] -density 150 -resize 250% -quality 100 /var/folders/zw/j_y1s0tj643gmv4hbh5817wr0000gr/T/mini_magick20200629-81203-otpihs.jpg
D, [2020-06-29T17:43:38.484118 #81203] DEBUG -- : [0.02s] magick identify /path_to_temp_file/test/WEC-1268.pdf
```

same output issues (tried 250% to confirm) and everything EXCEPT density is applied.  Tried again from the CLI and if I skip the density the output looks the same as via Carrierwave.

_Originally posted by @aximuseng in https://github.com/minimagick/minimagick/issues/442#issuecomment-651431075_

**Comment by janko** [comment]
It seems the problem here isn't that MiniMagick isn't behaving as expected, it's that the `-density` option in your CarrierWave context isn't doing what you're expecting it to do. Unfortunately this is something I cannot help with, as it's not a bug in MiniMagick.
