### ISSUE TITLE
Easy way to stub out aspects?

### ISSUE THREAD

**Issue by gerard-kelly-lu** [minimagick/minimagick#527]
I'm trying to ensure that the correct commands are passed to `combine_options` in my application (eg. adding text).

However, I won't have ImageMagick available on my CI server so need to stub out any commands I make. Currently when I call `combine_options` I get an `executable not found` error.

Thanks in advance for any help.

**Comment by janko** [comment]
You could override `MiniMagick::Tool#call` to be a no-op:

```rb
class MiniMagick::Tool
  def call(*args)
  end
end
```
