### ISSUE TITLE
Error when converting GIF to WEBP format

### ISSUE THREAD

**Issue by pipoblak** [minimagick/minimagick#528]
Im trying to convert a GIF format into WEBP with minimagick, but im recieving this error:

ImageProcessing::Error (Source format is multi-layer, but destination format is single-layer. If you care only about the first layer, add `.loader(page: 0)` to your pipeline. If you want to process each layer, see https://github.com/janko/image_processing/wiki/Splitting-a-PDF-into-multiple-images or use `.saver(allow_splitting: true)`.):

**Comment by janko** [comment]
Have you tried doing what the error message suggests?

**Comment by pipoblak** [comment]
It will turn the GIF into WEBP or will split gif into others WEBP?

And sorry for the dumb question, but im using it with "process :convert => 'webp'" in the CarrierWave using CarrierWave:MiniMagick, how i put the allow_splitting ?

**Comment by rikoroku** [comment]
any updates?

**Comment by janko** [comment]
Try the following to convert only the first page/frame of the source file:

```rb
process :convert => ['webp', 0]
```
