### ISSUE TITLE
Warnings when opening TIFF files

### ISSUE THREAD

**Issue by mauroc** [minimagick/minimagick#530]
I am working with a lot of geotiffs and getting a huge stream of warnings in my rails server (puma) whenever I open one of them (which I do tens of times in loops )
`
tif_img = Image.open("sample_geotiff.tif")`

```
irb(main):029:0> tif_img = Image.open("#{ml_tile.source_path}.tif")
identify-im6.q16: Unknown field with tag 33550 (0x830e) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/912.
identify-im6.q16: Unknown field with tag 33922 (0x8482) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/912.
identify-im6.q16: Unknown field with tag 34735 (0x87af) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/912.
identify-im6.q16: Unknown field with tag 34736 (0x87b0) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/912.
identify-im6.q16: Unknown field with tag 34737 (0x87b1) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/912.
identify-im6.q16: Unknown field with tag 42112 (0xa480) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/912.
```

The fields are typical geotiff tags, and I understand the warnings are harmless, but how can I get rid of them? It makes debugging really  cumbersome. I tried changing logging level from DEBUG to INFO, to no avail.
I understand there is a -quiet option in imagemagick but how would I use that in the context of the .open method?
Thank you!
+1 for a great gem!

**Comment by mauroc** [comment]
fixed using `MiniMagick.configure {|config| config.validate_on_create = false} `

**Comment by mauroc** [comment]
I now get more tiff-related warnings when running 

`tif_img.format 'png'`

```
convert-im6.q16: Unknown field with tag 33550 (0x830e) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/912.
convert-im6.q16: Unknown field with tag 33922 (0x8482) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/912.
convert-im6.q16: Unknown field with tag 34735 (0x87af) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/912.
```
I changed the command to: 

`tif_img.format('png', 0, read_opts={quiet: nil})`

but that causes error:

```
MiniMagick::Error (`convert -quiet  /tmp/mini_magick20210526-12695-s5figb.tif[0] /tmp/mini_magick20210526-12695-1u1fh3z.png` failed with error:
convert-im6.q16: no decode delegate for this image format `' @ error/constitute.c/ReadImage/504.
):
```
seems like the `[0]` added to the temp tiff file is what causes the error?

**Comment by mauroc** [comment]
Fixed the issue. The correct command should have been

`tif_img.format('png', nil, read_opts={quiet: nil})`

**Comment by jklemon17** [comment]
@mauroc I realized this is old and you may not remember, but were you able to resolve this?
