### ISSUE TITLE
Convert gif in webp keeping frames

### ISSUE THREAD

**Issue by paul-mesnilgrente** [minimagick/minimagick#534]
Hi,

I wrote something very simple like `@image.format 'webp'`. The image is a gif. But the webp contains only 1 frame. Is there an option to keep the frames?

**Comment by Reinkaos** [comment]
Hey,

Is there any update on this issue? At the moment we are having to resort to using https://github.com/minimagick/minimagick#metal to get this working. Would be great if the animated gif to animated webp conversion was supported by the normal conversion.

Thanks,
Richard

**Comment by janko** [comment]
`MiniMagick::Image#format` by default selects only the first page, to avoid generating arrays of images it doesn't know how to handle, because it doesn't know whether source or destination format are multi-layer or not.

You can pass `nil` for the page argument to process all layers:

```rb
@image.format 'webp', nil
```
