### ISSUE TITLE
Problems with .HEIC

### ISSUE THREAD

**Issue by camiloabrilth1999** [minimagick/minimagick#538]
Hello everybody!
I'm trying to convert a heic image to another image format with the gem but it doesn't recognize the 'image/heif' format.
I get an error when trying to do: 

`MiniMagick::Image.open(path)`

And the error is:

MiniMagick::Invalid: `identify /tmp/mini_magick20220222-7021-sss.heic` failed with error:
identify-im6.q16: no decode delegate for this image format `HEIC' @ error/constitute.c/ReadImage/560.

**Comment by mountriv99** [comment]
+1

**Comment by janko** [comment]
Are you able to process HEIC images with ImageMagick on the command-line? If not, then it's an ImageMagick issue, not MiniMagick.

**Comment by mountriv99** [comment]
Hi janko

So, if I'm getting this:

CarrierWave::ProcessingError: Failed to manipulate with MiniMagick, maybe it is not an image? Original Error: `magick identify /var/folders/pf/131m4xjj64d50m5p_hpqvqs00000gn/T/mini_magick20220616-41322-1tiuli0.heic` failed with error:
identify: no decode delegate for this image format `HEIC' @ error/constitute.c/ReadImage/556.

It means that my ImageMagick is not able to process HEIC images?

**Comment by janko** [comment]
Yes.

**Comment by mountriv99** [comment]
Thanks, will try updating it.

**Comment by jurriaanschrofer** [comment]
Hi @janko,

Thanks for creating this awesome gem.

Are there any known workarounds to this problem?

Or, if not, are there plans to fix this? :)

tnx!

**Comment by janko** [comment]
How would I be able to fix an issue in ImageMagick? If ImageMagick doesn't support HEIC, or isn't compiled with HEIC support, there is nothing a ruby wrapper can do about it.

**Comment by J4cker14** [comment]
How to compile with heic for windows, or where to grab installer supporting that ?
