### ISSUE TITLE
Can't open ico file without extension

### ISSUE THREAD

**Issue by xxiieao** [minimagick/minimagick#539]
Hi,

Not sure this is a bug. We received a `MiniMagick::Invalid` error, when trying to convert an ICO file to PNG. That ico file doesn't has extension name though. It looks like minimagick can't identify an ICO file, if no extension in filename.

Manage to fix it by adding the ext parameter.
```
MiniMagick::Image.open(path, ".ico") 
```

**Comment by janko** [comment]
Yeah, ImageMagick will not always able to recognize the file type just from its contents, that's why image files should generally have extensions. Nothing ImageMagick can do here if the extension wasn't provided.
