### ISSUE TITLE
Please publish a new release

### ISSUE THREAD

**Issue by TRex22** [minimagick/minimagick#545]
I see the latest release is from 2020. There have been a bunch of pull requests in master since then.
Please could you release a new version 🙏🏻 

Thanks 😀

**Comment by navidemad** [comment]
Up

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by janko** [comment]
Just released version 4.12.0 with the latest fixes 🙂

**Comment by n-rodriguez** [comment]
Thank you!
