### ISSUE TITLE
Webp image upload issue

### ISSUE THREAD

**Issue by SRIKANTHAR** [minimagick/minimagick#548]
webp images upload not supported it's giving this error message when trying to upload webp images has below

avatar_2_3_webp = open(image_ur)

at paperclip method "open" we are getting this error

ImageSpec::Error (#Paperclip::Tempfile:/tmp/18c5a2261d1d178068acb724a8a967b720221108-1242657-rpwwg520221108-1242657-n7zd3k.webp is not a supported image format. Sorry bub :():

we are using Rails 4.2 and ruby 2.3.0
paperclip (4.2.4)
paperclip-compression (0.3.11)
paperclip-optimizer (2.0.0)
ImageMagick 6.9.10-23

please help on this to how to fix this issue

**Comment by janko** [comment]
Is your ImageMagick compiled with webp support? Can you convert webp images directly via ImageMagick command-line?

**Comment by SRIKANTHAR** [comment]
convert -version

Version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP 
Delegates (built-in): bzlib djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png tiff webp wmf x xml zlib

Yes ImageMagick support webp in command-line. we have checked with convert command has below

convert  rose.jpg  rose.webp 

webp conversion working in command-line

**Comment by janko** [comment]
Can you reproduce the bug without Paperclip? Is Paperclip even using MiniMagick? I thought it just shelled out to ImageMagick directly.
