### ISSUE TITLE
Ruby 3.2.2: Open3.popen3 doesn't return a Process::Status - NoMethodError for exitstatus

### ISSUE THREAD

**Issue by jpr5** [minimagick/minimagick#556]
Recently tried to upgrade to Ruby 3.2.2 (from 2.7.8) using mini_magick 4.12.0, ran into a bunch of `NoMethodErrors` from [shell.rb#L31](https://github.com/minimagick/minimagick/blob/master/lib/mini_magick/shell.rb#L31): 

```
#<NoMethodError: undefined method `exitstatus' for nil:NilClass> mini_magick-4.12.0:lib/mini_magick/shell.rb:31>14>, mini_magick-4.12.0:lib/mini_magick/tool.rb:92>38>, mini_magick-4.12.0:lib/mini_magick/image.rb:589>219>131>, <internal::kernel>>, mini_magick-4.12.0:lib/mini_magick/image.rb:130>34>108>108>108>108>
...
```

Poking around [shell.rb#L59](https://github.com/minimagick/minimagick/blob/master/lib/mini_magick/shell.rb#L59), I see: 
```
       [stdout_reader.value, stderr_reader.value, thread.value]
```
where the retval for `thread#value` is [supposed](https://docs.ruby-lang.org/en/3.2/Open3.html#method-c-popen3) to be a `Process::Status` object.  

This isn't true for some reason -- it's `nil`:
```[57, 66] in /usr/local/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/mini_magick-4.12.0/lib/mini_magick/shell.rb
   57:           raise Timeout::Error, "MiniMagick command timed out: #{command}"
   58:         end
   59: 
   60:         byebug
   61: 
=> 62:         [stdout_reader.value, stderr_reader.value, thread.value]
   63:       end
   64:     end
   65: 
   66:     def execute_posix_spawn(command, options = {})
(byebug) thread.inspect
"#<Process::Waiter:0x0000ffff90f1c670 dead>"
(byebug) p thread.value
nil
```
which, of course, does not have an `#exitstatus`. 

If I run the command myself, I get: 
```
(byebug) command
["gm", "identify", "/tmp/mini_magick20230911-35098-1957om.bin"]
(byebug) system(command.join(" "))
/tmp/mini_magick20230911-35098-1957om.bin JPEG 1728x1028+0+0 DirectClass 8-bit 74.5Ki 0.000u 0m:0.000003s
true
```
so it's not a question of the command existing.

Given that it works when I invoke it via `system()`, I'm at a loss.  🤷  Would have loved to come with a solution to the problem, but alas...

Ideas?

**Comment by jpr5** [comment]
Even the [latest Ruby 3.2.2 docs](https://ruby-doc.org/3.2.2/stdlibs/open3/Open3.html#method-c-popen3) appear to be wrong...

Is there some sort of contributory setting that could cause `thread#value` to be `nil`?

**Comment by jpr5** [comment]
I traced it into the `open3` lib, where `Process.detach` is indeed returning a `Process::Waiter` that has a nil value, however when I run via `system()` it works fine: 
```
[220, 229] in /usr/local/rbenv/versions/3.2.2/lib/ruby/3.2.0/open3.rb
   220: 
   221:   def popen_run(cmd, opts, child_io, parent_io) # :nodoc:
   222:     pid = spawn(*cmd, opts)
   223:     wait_thr = Process.detach(pid)
=> 224:     child_io.each(&:close)
   225:     result = [*parent_io, wait_thr]
   226:     if defined? yield
   227:       begin
   228:         return yield(*result)
   229:       ensure

(byebug) wait_thr.value
nil
(byebug) cmd
["gm", "identify", "/tmp/mini_magick20230911-37977-gox420.bin"]
(byebug) opts
{:in=>#<IO:(closed)>, :out=>#<IO:(closed)>, :err=>#<IO:(closed)>}
(byebug) pid = spawn(*cmd)
38111
(byebug) t =  Process.detach(pid)
#<Process::Waiter:0x0000ffff8306de88 run>
(byebug) t.value
nil
(byebug) system(cmd.join(" "))
/tmp/mini_magick20230911-37977-gox420.bin JPEG 1504x1667+0+0 DirectClass 8-bit 83.3Ki 0.000u 0m:0.000002s
true
```

I'm stumped...

**Comment by janko** [comment]
As far as I remember, as subprocess will have no exit status when it was terminated by the OS. I will try to work around this, probably by using `$MAGICK_TIME_LIMIT` instead of `Thread#join` with a timeout, to let ImageMagick itself time out.

**Comment by janko** [comment]
I didn't figure out how to use `MAGICK_TIME_LIMIT=...` or `-limit time ...` yet, the timeout is simply not applied 🤷🏻‍♂️
