### ISSUE TITLE
Webp image upload issue

### ISSUE THREAD

**Issue by SRIKANTHAR** [minimagick/minimagick#557]
webp images upload not supported it's giving this error message when trying to upload webp images has below

avatar_2_3_webp = open(image_ur)

at paperclip method "open" we are getting this error

ImageSpec::Error (#Paperclip::Tempfile:/tmp/18c5a2261d1d178068acb724a8a967b720221108-1242657-rpwwg520221108-1242657-n7zd3k.webp is not a supported image format. Sorry bub :():

we are using Rails 4.2 and ruby 2.3.0

mini_magick (4.12.0)
paperclip (4.2.4)
paperclip-compression (0.3.11)
paperclip-optimizer (2.0.0)

please help on this to how to fix this issue

**Comment by janko** [comment]
Do you get the same error when using ImageMagick directly on the command-line? Because this error indicates that your ImageMagick installation is not compiled with WEBP support.
