### ISSUE TITLE
Well here's an SVG that kills MiniMagick

### ISSUE THREAD

**Issue by majikthys** [minimagick/minimagick#568]
Happened across an SVG that tanks MiniMagick, attached.

Here's a repro:
```
require 'mini_magick'
file_path = '/tmp/foo.svg'
puts "about to open #{file_path}"
image = MiniMagick::Image.open(file_path)
puts "I never get here"
puts image.inspect # I don't get here either
```
And the image:
![header-new-785x110-textToPath](https://github.com/minimagick/minimagick/assets/1882379/fee73c31-1d24-49fa-a8f0-a3ea9e2777ff)

**Comment by janko** [comment]
Seems like a regression from the previous release, caused by https://github.com/minimagick/minimagick/pull/559. I'll revert this and publish a release.
