### ISSUE TITLE
Getting deprecation warning when using Image.format

### ISSUE THREAD

**Issue by ErikWallstrom** [minimagick/minimagick#571]
Hello!

I want to convert a PNG image to JPEG, but when I do this: 

```ruby
image = MiniMagick::Image.open('test.png')
image.format('JPEG')
image.write('test.jpg')
```

the following warning gets outputted:

`WARNING: The convert command is deprecated in IMv7, use "magick" instead of "convert" or "magick convert"`

I am not very familiar with ImageMagick. How should I do this in a way that is not deprecated?

Thanks

**Comment by janko** [comment]
This has been fixed in the latest version.
