### ISSUE TITLE
WARNING: The convert command is deprecated in IMv7, use "magick" instead of "convert" or "magick convert"

### ISSUE THREAD

**Issue by fukayatsu** [minimagick/minimagick#574]
This is similar to #560 (fixed by https://github.com/minimagick/minimagick/commit/c39fbefc99f3c63d063a5c208f9bb9c4bbd92860), but the warning text has changed on IM 7.1.1-34.
So the warning appears again.

- https://github.com/ImageMagick/ImageMagick/compare/7.1.1-33...7.1.1-34#diff-bc8390ae45732341327c1ccfd1c67e194b8dfdaa9142af3c296ca66a4b3d5eba

```diff
- "The convert command is deprecated in IMv7, use \"magick\"\n");
+ "The convert command is deprecated in IMv7, use \"magick\" instead of \"convert\" or \"magick convert\"\n");
```

## Possible Solution

- https://github.com/minimagick/minimagick/blob/fcd7600fe88e582431e7fef3c732accb8a42273e/lib/mini_magick/shell.rb#L20

```diff
- $stderr.print(stderr) unless options[:stderr] == false || stderr.strip == %(WARNING: The convert command is deprecated in IMv7, use "magick") 
+ $stderr.print(stderr) unless options[:stderr] == false || stderr.strip.start_with?(%(WARNING: The convert command is deprecated in IMv7, use "magick"))
```

**Comment by janko** [comment]
Thanks for the report. I believe the proposed solution would also silence legitimate warnings that appear after the deprecation warnings, but it shouldn't be too difficult to handle that. I'll work on it and release another minor release.

**Comment by janko** [comment]
Should be fixed in 4.13.2.

**Comment by jaredbeck** [comment]
Thanks for the quick fix, Janko.

**Comment by fukayatsu** [comment]
@janko thank you　!
