### ISSUE TITLE
Create a new image from scratch

### ISSUE THREAD

**Issue by vivien** [minimagick/minimagick#59]
Hi,

If I'm not mistaken, it is not possible to create a new image (which doesn't exist on the disk yet) with MiniMagick, while it is possible with the `convert` tool. It would be useful, especially for canvas and composite. Here's a dirty hack I'm using:

    def new_image(width, height, format = "png", bgcolor = "transparent")
      tmp = Tempfile.new(%W[mini_magick_ .#{format}])
      `convert -size #{width}x#{height} xc:#{bgcolor} #{tmp.path}`
      MiniMagick::Image.new(tmp.path, tmp)
    end

It would be interesting to add this feature in MiniMagick unless something similar already exists.

Best,
Vivien.

**Comment by nofxx** [comment]
Should this be reopened? I encoutered this issue trying to create an image.
Did like the OP to monkey patch it, but ended up creating a 1px transparent png and loading it when needed. Kinda ugly.

**Comment by janko-m** [comment]
I've read through the discussion now, but haven't quite understood what should MiniMagick do. Isn't it already possible to create images on disk with ImageMagick itself (if it is, could someone remind me how)? Do you want MiniMagick to provide some convenient API for it?

**Comment by mattbearman** [comment]
This can be done using the bare metal, eg:

    # Create a white png, 1024 x 768 pixels
    MiniMagick::Tool::Convert.new do | new_image |
      new_image.size "1024x768"
      new_image << "image.png"
    end

But it would be nice to have a proper API wrapper for it :)

**Comment by janko-m** [comment]
Since I'm never creating images (I never needed it so far), I'm not exactly sure hiw the wrapper should look like. I'd gladly take suggestions or better yet PRs :)

**Comment by janko-m** [comment]
I gave it some more thought, and I think this is actually out of scope of MiniMagick. It would make much more sense to have a library on top of MiniMagick for generating images.
