### ISSUE TITLE
No such file or directory - identify -ping /tmp/somefile

### ISSUE THREAD

**Issue by mlainez** [minimagick/minimagick#69]
Hi, 

I've been struggling on an error we have on our staging server and I'd hope anybody could help me.

We are using **mini_magick 3.4** together with **ImageMagick 6.6.9-7**

Carrierwave was configured to send images through s3 but I don't think this is relevant (correct me if it is :)

We upload the image file by sending it through ajax in the post raw data and grab it in this controller action:

``` ruby
def create
  filename   = params[:qqfile]
  attachment = create_file_to_upload(request.body, filename)
  content    = File.open(attachment.path)
  current_user.media.create(:attachment => content)
  attachment.delete
  render :json => {success: true}, :status => 200
end
```

The create_file_to_upload method uses a tempfile to store the request raw data payload:

``` ruby
def create_file_to_upload(body, name)
  basename  = File.basename(name)
  extension = File.extname(name)
  file      = Tempfile.new([basename, extension])
  file.binmode
  file.write(body.read)
  file.close
  file
end
```

It works great in development and test environment but however, on our staging server, it fails with:

```
Completed 500 Internal Server Error in 29ms

Errno::ENOENT (No such file or directory - identify -ping /tmp/mini_magick20120112-14991-1gw63m2.png):
  app/controllers/media_controller.rb:6:in `create'
```

I've checked that the identify command was accessible to the user with which the app is being run and it is. I have also run the command in a terminal on our server and it works like a charm.

I'm a bit lost and would be open to any suggestion, so if you have a few minutes to think about this or to point me in any direction, I'd really appreciate it.

Thanks

**Comment by scottbullard** [comment]
+1 @aminhotob:
Mac OSX 10.10.1
Rails 4.2
mini_magic 3.8.1
carrierwave 0.10.0

**Comment by janko-m** [comment]
@scottbullard Could you try to isolate the problem? Because it could be the problem with CarrierWave. Try upgrading MiniMagick to the latest version, 4.0.2, and see if you still get the error.

**Comment by scottbullard** [comment]
@janko-m - just posting for informational purposes should someone else need the help.  My rails app required mini_magic 3.8.1 but am working on the updates to bring it current with mini_magic 4.0.2.

**Comment by RaginiD** [comment]
i am working on windows and got same problem what to do

**Comment by janko-m** [comment]
@RaginiD I need more information. How did you get the error, and what version of MiniMagick are you using?

**Comment by RaginiD** [comment]
Hello


i am learning ruby on rails using Michael Hartl's book.
<https://www.google.co.in/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&sqi=2&ved=0ahUKEwj6ltCpisrKAhVO0WMKHQwXDV8QFggeMAA&url=https%3A%2F%2Fwww.railstutorial.org%2F&usg=AFQjCNED9ehr1_wkLzGaohKUPTwJ_OE1gQ&sig2=Hx4GGc6iQkpoayHmb5f5XQ&bvm=bv.112766941,d.cGc>
i am working on windows 7
but in chapter 11 i have added 3 gem files

gem 'carrierwave',             '0.10.0'gem 'mini_magick',
'3.8.0'gem 'fog',                     '1.36.0'

i followed all steps as they mentioned

but after addition of image resize code i am getting error


class PictureUploader < CarrierWave::Uploader::Base  include
CarrierWave::MiniMagick  process resize_to_limit: [400, 400]
  storage :file

  # Override the directory where uploaded files will be stored.
  # This is a sensible default for uploaders that are meant to be mounted:
  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end

  # Add a white list of extensions which are allowed to be uploaded.
  def extension_white_list
    %w(jpg jpeg gif png)
  endend

befor image resize its working ok but images taking large size.
so i tried to resize image but its giving error.

<https://www.google.co.in/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&sqi=2&ved=0ahUKEwj6ltCpisrKAhVO0WMKHQwXDV8QFggeMAA&url=https%3A%2F%2Fwww.railstutorial.org%2F&usg=AFQjCNED9ehr1_wkLzGaohKUPTwJ_OE1gQ&sig2=Hx4GGc6iQkpoayHmb5f5XQ&bvm=bv.112766941,d.cGc>

**Comment by janko-m** [comment]
Try updating MiniMagick to the latest version.

```rb
gem "mini_magick", "~> 4.3"
```

**Comment by Iazel** [comment]
Just for future reference, I had this problem with Nginx + Passenger + Rails. The problem was the `ENV['PATH']` variable. The solution for me was adding the following line in the nginx vhost definition:
```
passenger_env_var PATH <path-to-rails>/vendor/bundle/<ruby-version>/bin:/usr/local/bin:/usr/bin
```

**Comment by jerturowetz** [comment]
Any Windows 10 users with this issue falling on this thread: installing ImageMagick as admin fixed my issue.
