### ISSUE TITLE
label in MOGRIFY_COMMANDS & IMAGE_CREATION_OPERATORS

### ISSUE THREAD

**Issue by robertjwhitney** [minimagick/minimagick#80]
'label' has different behaviors for the different syntaxes. The first is to add the label as meta-data, the second draws it as text on the image. I don't think there is a way to specify use of -label arg or label:arg so it never gets past elsif MOGRIFY_COMMANDS.include?

``` ruby
    def method_missing(symbol, *options)
      guessed_command_name = symbol.to_s.gsub('_','-')
      if guessed_command_name == "format"
        raise Error, "You must call 'format' on the image object directly!"
      elsif MOGRIFY_COMMANDS.include?(guessed_command_name)
        add_command(guessed_command_name, *options)
        self
      elsif IMAGE_CREATION_OPERATORS.include?(guessed_command_name)
        add_creation_operator(guessed_command_name, *options)
        self
      else
        super(symbol, *args)
      end
    end
```

label arg
http://www.imagemagick.org/script/command-line-options.php#label

label:arg
http://www.imagemagick.org/Usage/text/#label

As far as I can tell, label:arg is the best way to add text that dynamically resizes to dimensions given by -size

**Comment by corristo** [comment]
So, no way to use `label:` or `caption:`?

**Comment by janko-m** [comment]
MiniMagick 4 supports it, if you're using that:

```rb
image = MiniMagick::Image.new(...)
image.combine_options do |cmd|
  cmd.label "foo" # adds "label:foo"
  cmd.caption "bar" # adds "caption:bar"
end
```

**Comment by corristo** [comment]
@janko-m thanks!

**Comment by corristo** [comment]
@janko-m unfortunately `c.caption` is turned into `-caption`, not `caption:`

**Comment by janko-m** [comment]
Which version if MiniMagick are you using? Is it the latest?

**Comment by corristo** [comment]
@janko-m ah, sorry, it was dependency of a gem I'm working on, so it was a bit dated. Updated to 4.3.*, now it's okay.
